### ISSUE TITLE
PostgreSQL OID Bit column type issue on Rails 5

### ISSUE THREAD

**Issue by morgoth** [rails/rails#26137]
On upgrade to Rails 5, I have issue with Postgres `bit` column type and overwriting reader method
You can see the issue: https://gist.github.com/morgoth/1d3725b3e73b91e164d5e20a81221e8f

It was working fine on Rails 4.2, now it raises:
```
NoMethodError: undefined method `[]' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Bit::Data:0x00557ede32d2c0>
```
### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

**Comment by alexcameron89** [comment]
From a git bisect, it looks like this was introduced by 07723c23a7dc570beae73c074ad37227e3e8a06e. 

Cc @sgrif since he committed the changes.

**Comment by alexcameron89** [comment]
Hey @sgrif, I did lots of digging, and I created an additional [test script](https://gist.github.com/alexcameron89/145d6e7d55c6caa71f29a5a5b2ff89d9) to show that this is happening after save.

I think I pinpointed issue to being a call to serialize the value(stacktrace to the issue line below). `OID::Bit` serializes by creating a Data object. 

In `save`, `changes_applied` calls `store_original_attributes`.
`store_original_attributes` tries to map `forgetting_assignment` to each att in `@attributes`.
`forgetting_assignment` calls `value_for_database` which is where the serialization happens(**Line 51** of `activerecord/lib/active_record/attribute.rb`:
```
--> #0  ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Bit.serialize(value#String) at rails/activerecord/lib/active_record/connection_adapters/postgresql/oid/bit.rb:24
    #1  ActiveRecord::Attribute.value_for_database at rails/activerecord/lib/active_record/attribute.rb:51
    #2  ActiveRecord::Attribute.forgetting_assignment at rails/activerecord/lib/active_record/attribute.rb:63
    #3  block in Hash.block in transform_values at rails/activesupport/lib/active_support/core_ext/hash/transform_values.rb:18
    ͱ-- #4  Hash.each at rails/activesupport/lib/active_support/core_ext/hash/transform_values.rb:17
    #5  Hash.transform_values at rails/activesupport/lib/active_support/core_ext/hash/transform_values.rb:17
    #6  ActiveRecord::AttributeSet.map(&block#Proc) at rails/activerecord/lib/active_record/attribute_set.rb:93
    #7  ActiveRecord::AttributeMethods::Dirty.store_original_attributes at rails/activerecord/lib/active_record/attribute_methods/dirty.rb:131
    #8  ActiveRecord::AttributeMethods::Dirty.changes_applied at rails/activerecord/lib/active_record/attribute_methods/dirty.rb:55
    #9  block in ActiveRecord::AttributeMethods::Dirty.block in save!(*args) at rails/activerecord/lib/active_record/attribute_methods/dirty.rb:31
    ͱ-- #10 Kernel.tap at rails/activerecord/lib/active_record/attribute_methods/dirty.rb:30
    #11 ActiveRecord::AttributeMethods::Dirty.save!(*args) at rails/activerecord/lib/active_record/attribute_methods/dirty.rb:30
    #12 block in ActiveRecord::Transactions.block in save!(*args) at rails/activerecord/lib/active_record/transactions.rb:324
    #13 block in ActiveRecord::Transactions.block in with_transaction_returning_status at rails/activerecord/lib/active_record/transactions.rb:395
    #14 block in ActiveRecord::ConnectionAdapters::DatabaseStatements.block in transaction(requires_new#NilClass, isolation#NilClass, joinable#TrueClass) at rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233
    #15 ActiveRecord::ConnectionAdapters::TransactionManager.within_new_transaction(options#Hash) at rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:186
    #16 ActiveRecord::ConnectionAdapters::DatabaseStatements.transaction(requires_new#NilClass, isolation#NilClass, joinable#TrueClass) at rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:233
    #17 ActiveRecord::Transactions::ClassMethods.transaction(options#Hash, &block#Proc) at rails/activerecord/lib/active_record/transactions.rb:211
    #18 ActiveRecord::Transactions.with_transaction_returning_status at rails/activerecord/lib/active_record/transactions.rb:392
    #19 ActiveRecord::Transactions.save!(*args) at rails/activerecord/lib/active_record/transactions.rb:324
    #20 ActiveRecord::Suppressor.save!(*args) at rails/activerecord/lib/active_record/suppressor.rb:46
    #21 ActiveRecord::Persistence::ClassMethods.create!(attributes#NilClass, &block#NilClass) at rails/activerecord/lib/active_record/persistence.rb:51
    #22 BugTest.test_create at postgres-bit-bug.rb:44
```

I'm not sure how to fix this issue? But I hope this help cut down on research time for you, and I'm very glad to help wherever else that I can.
