### ISSUE TITLE
[4.2.5.1] NoMethodError: undefined method `cache' for nil:NilClass

### ISSUE THREAD

**Issue by allenwq** [rails/rails#23254]
```ruby
  render file: 'public/404.html', status: :not_found
```

The above code works fine on 4.2.5, but after upgrade to 4.2.5.1, I get the following exception.
Basically `@cache` in the `resolver` is `nil`

``` ruby
NoMethodError: undefined method `cache' for nil:NilClass
../gems/actionview-4.2.5.1/lib/action_view/template/resolver.rb:151:in `cached'
../gems/actionview-4.2.5.1/lib/action_view/template/resolver.rb:121:in `find_all_anywhere'
../gems/actionview-4.2.5.1/lib/action_view/path_set.rb:68:in `block (2 levels) in _find_all'
../gems/actionview-4.2.5.1/lib/action_view/path_set.rb:66:in `each'
../gems/actionview-4.2.5.1/lib/action_view/path_set.rb:66:in `block in _find_all'
../gems/actionview-4.2.5.1/lib/action_view/path_set.rb:65:in `each'
../gems/actionview-4.2.5.1/lib/action_view/path_set.rb:65:in `_find_all'
../gems/actionview-4.2.5.1/lib/action_view/path_set.rb:50:in `find_file'
../gems/actionview-4.2.5.1/lib/action_view/lookup_context.rb:126:in `find_file'
../gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_file'
../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:32:in `block in determine_template'
../gems/actionview-4.2.5.1/lib/action_view/lookup_context.rb:147:in `with_fallbacks'
../gems/actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `with_fallbacks'
../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:32:in `determine_template'
../gems/actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:8:in `render'
../gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
../gems/actionview-4.2.5.1/lib/action_view/renderer/renderer.rb:23:in `render'
../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:100:in `_render_template'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
../gems/actionview-4.2.5.1/lib/action_view/rendering.rb:83:in `render_to_body'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
../gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:25:in `render'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:16:in `render'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
../gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
../gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
../gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
../gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
```

**Comment by Thalagyrt** [comment]
Seeing this as well in 4.1.14.1

**Comment by allenwq** [comment]
After further inspection, this seems to be a RSpec issue,  their `RSpec::Rails::ViewRendering::EmptyTemplatePathSetDecorator` is not updated.
