### ISSUE TITLE
class_attribute removes existing instance predicate methods, even if instance_predicate: false

### ISSUE THREAD

**Issue by njakobsen** [rails/rails#32736]
This is because the method is removed without first checking to see if the method is desired, here
https://github.com/rails/rails/blob/b1b0a334b8fe3a3fb363d6a4b8a35272231fc4f3/activesupport/lib/active_support/core_ext/class/attribute.rb#L81-L82 and here https://github.com/rails/rails/blob/b1b0a334b8fe3a3fb363d6a4b8a35272231fc4f3/activesupport/lib/active_support/core_ext/class/attribute.rb#L118-L119

### Steps to reproduce

```ruby
module MyModule
  extend ActiveSupport::Concern

  included do
    class_attribute :testing, instance_predicate: false
  end
 
  def testing?
    'Success'
  end
end

class SomeClass
  include MyModule
end

SomeClass.new.testing? # => NoMethodError: undefined method `testing?' for #<SomeClass:0x007f7fc651bab0>
```

This test case fails because the module method is defined before the `included` callback executes, thereby undefining the `testing?` method, even though we don't want to generate an instance predicate method.

### Expected behavior
The `testing?` method should be defined (and return 'Success')

### Actual behavior
The `testing?` method is undefined.

### System configuration
**Rails version**: 5.1

**Ruby version**: 2.3.0p0

**Comment by eugeneius** [comment]
This behaviour was introduced in https://github.com/rails/rails/pull/20026, and appears to be unintentional.

If you're interested, please submit a pull request with a fix!

**Comment by tgturner** [comment]
This is no longer an issue since 5.2, does it make sense to back-port a fix to 5.1?

**Comment by eugeneius** [comment]
Good spot, I should have checked if the problem was still present on master.

https://github.com/rails/rails/pull/32608 proposes to backport that fix to `5-1-stable`.
