### ISSUE TITLE
undefined local variable or method `always_initialized' 

### ISSUE THREAD

**Issue by eclemens** [rails/rails#32385]
I get an ActiveRecord exception after upgrading from Rails 5.1.5 to 5.1.6. Rolling back to 5.1.5 fixes it.

### Steps to reproduce

The error is triggered if I try to retrieve a record from the database:
```
User.find(2)
```

### Expected behavior
I expected to get the User with the ID equals to 2

### Actual behavior
I got the following exception:
```
undefined local variable or method `always_initialized' for #<ActiveRecord::AttributeSet::Builder:0x00000000070f4c98>
```

### System configuration
**Rails version**: 5.1.6

**Ruby version**: ruby-2.4.3

**Comment by eugeneius** [comment]
The token `always_initialized` doesn't appear in Rails 5.1.6 at all; it was removed in https://github.com/rails/rails/commit/1fd67501ce8b55bf9dc42efb119d3ca395c5363c.

This seems more likely to be a problem with a monkey patch or gem than with Rails itself. Could you post the backtrace for the error?

**Comment by eclemens** [comment]
You are right. Another GEM was using the GEM composite_primary_keys that triggered the error. Thank you.

https://github.com/composite-primary-keys/composite_primary_keys/blob/v10.0.3/lib/composite_primary_keys/attribute_set/builder.rb

**Comment by camelot729** [comment]
What step I need to fix at?

**Comment by tommyalvarez** [comment]
@eclemens i'm also using that gem, is there a fix/work around?

**Comment by eclemens** [comment]
@tommyalvarez I just updated it to the beta release and it worked
