### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by famousky** [rails/rails#19692]
This drives me crazy!

Trying to upload an image and getting this error:

![screen shot 2015-04-08 at 8 57 28 pm](https://cloud.githubusercontent.com/assets/4720153/7045921/c1cafd7c-de34-11e4-8f2c-19e624c47ddb.png)

Here is the rails command output when I do this task:

```
Processing by UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"IWPqsQkHUwR2oJUpulqquQCB6ErATTF/hbNQ0U/Vt4XhKZtzFCFoapD/tulAq73M5Qa0p6oMn84Yzfn/SOFf/g==", "user"=>{"name"=>"Evo", "nickname"=>"Famou", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x007f96d4e8d498 @tempfile=#<Tempfile:/var/folders/n4/p168tr216rz7r4_5m78s68x00000gn/T/RackMultipart20150408-18466-1pb3ea9.jpg>, @original_filename="10610626_666671546821437_6940494711136740016_n.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"10610626_666671546821437_6940494711136740016_n.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Save", "id"=>"1"}
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
   (0.2ms)  BEGIN
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
  SQL (0.5ms)  UPDATE "users" SET "avatar" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["avatar", "10610626_666671546821437_6940494711136740016_n.jpg"], ["updated_at", "2015-04-08 13:18:26.287220"], ["id", 1]]
   (0.3ms)  ROLLBACK
Completed 500 Internal Server Error in 184ms

NoMethodError (undefined method `gsub' for nil:NilClass):
  app/controllers/users_controller.rb:53:in `block in update'
  app/controllers/users_controller.rb:52:in `update'


  Rendered /Users/evo/.gem/ruby/2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (8.4ms)
  Rendered /Users/evo/.gem/ruby/2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.3ms)
  Rendered /Users/evo/.gem/ruby/2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.9ms)
  Rendered /Users/evo/.gem/ruby/2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (43.7ms)
Cannot render console with content type multipart/form-dataAllowed content types: [#<Mime::Type:0x007f96d3d579f8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">, #<Mime::Type:0x007f96d3d576b0 @synonyms=[], @symbol=:text, @string="text/plain">, #<Mime::Type:0x007f96d3d54230 @synonyms=[], @symbol=:url_encoded_form, @string="application/x-www-form-urlencoded">]
```

**Comment by sgrif** [comment]
We reserve the issues tracker for bugs in Rails only (e.g. this used to work in Rails 4.1 and is broken in Rails 4.2). Please ask your question on Stack Overflow or the mailing lists.
