### PR TITLE
MemCacheStore: always convert underlying values into an `Entry`

### PR DESCRIPTION
**Pull request by ghiculescu**
There's a bug in the Mem Cache Store on 6.1, I haven't confirmed if it exists on `main` too (since https://github.com/rails/rails/pull/42025).

We came across the bug when upgrading an app from 6.0 to 6.1 that had recently switched from the `dalli_store` to the `mem_cache_store`. https://github.com/petergoldstein/dalli/issues/771 seems similar, but in our case it's specifically to do with caching the value `false`.

To replicate:

- Open a Rails console with the `dalli_store` enabled.
- `Rails.cache.write "test", false`
- Open another Rails console, with the `mem_cache_store` enabled.
- Enable the local cache (starting a Rails server would also achieve this): `ActiveSupport::Cache::Strategy::LocalCache::LocalCacheRegistry.set_cache_for(Rails.cache.send(:local_cache_key), ActiveSupport::Cache::Strategy::LocalCache::LocalStore.new)`
- ` Rails.cache.fetch("test") { false }`

It will crash with

```
NoMethodError (undefined method `dup_value!' for false:FalseClass)
```

The fix is to convert any entry into an `Entry`, even if it's `false`.

### CODE REVIEW

**Comment by ghiculescu** [comment]
@byroot do you think https://github.com/rails/rails/pull/42559 would fix this on main?

**Comment by byroot** [comment]
> do you think #42025 would fix this on main?

Hum, maybe? Best way to know is to check.

**Review by byroot — APPROVED** [review]

**Comment by byroot** [comment]
CI failures seem totally unrelated. Your fix look good to me. Maybe we should add a regression test though?

**Comment by ghiculescu** [comment]
Good idea - regression test added.

File: activesupport/test/cache/stores/mem_cache_store_test.rb [hunk 1]
```diff
@@ -211,6 +211,38 @@ def test_large_object_with_default_compression_settings
...
+  def test_can_read_and_write_falsy_value_with_local_cache
+    key = "test-with-false-value-through-public-api"
+
+    @cache.write(key, false)
+    @cache.with_local_cache do
+      assert_equal false, @cache.read(key)
+    end
+  end
+
+  def test_can_load_raw_values_from_dalli_store
```
Comment (ghiculescu) [inline activesupport/test/cache/stores/mem_cache_store_test.rb:237]:
```suggestion
  def test_can_load_raw_values_from_dalli_store_with_local_cache
```

**Comment by ghiculescu** [comment]
Regression test passes here. It fails on `main` so I will look into that.

**Comment by zzak** [comment]
@ghiculescu @byroot Could you add a changelog? :bow:

**Comment by ghiculescu** [comment]
@zzak would it go here? https://github.com/rails/rails/blob/6-1-stable/activesupport/CHANGELOG.md

**Review by fatash89 — APPROVED** [review]
