### PR TITLE
Fix ActionDispatch::Routing::RouteSet#recognize_path regression against symbols and give clear error for other types

### PR DESCRIPTION
**Pull request by araishikeiwai**
### Motivation / Background

Similar to #47310, I noticed a regression in `ActionDispatch::Routing::RouteSet#recognize_path` against symbols that was introduced in #47262. Rails 7.0 accepted symbols in this method.

Rails 7.0:

```ruby
[1] pry(main)> Rails.application.routes.recognize_path(:accounts)
=> {:controller=>"accounts", :action=>"index"}
[2] pry(main)> Rails.application.routes.recognize_path({ controller: 'test' })
TypeError: no implicit conversion of Hash into String
from /Users/araishikeiwai/.rbenv/versions/3.2.7/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8.5/lib/action_dispatch/routing/route_set.rb:857:in `match?'
```

vs 7.1 and above:

```ruby
[1] pry(main)> Rails.application.routes.recognize_path(:accounts)
NoMethodError: undefined method `include?' for :accounts:Symbol
from /Users/araishikeiwai/.rbenv/versions/3.2.7/lib/ruby/gems/3.2.0/gems/actionpack-7.1.5.1/lib/action_dispatch/routing/route_set.rb:887:in `recognize_path'
[2] pry(main)> Rails.application.routes.recognize_path({ controller: 'test' })
NoMethodError: undefined method `encoding' for {:controller=>"test"}:Hash
from /Users/araishikeiwai/.rbenv/versions/3.2.7/lib/ruby/gems/3.2.0/gems/actionpack-7.1.5.1/lib/action_dispatch/journey/router/utils.rb:19:in `normalize_path'
```

### Detail

This Pull Request keeps the method behaviour similar to previous version when given a symbol, and gives a clear indication of the error when given anything else

### Additional information

Alternative solution would be to outright reject symbols and raise `TypeError`

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: actionpack/lib/action_dispatch/routing/route_set.rb [hunk 1]
```diff
@@ -910,7 +910,10 @@ def call(env)
 
       def recognize_path(path, environment = {})
         method = (environment[:method] || "GET").to_s.upcase
-        path = Journey::Router::Utils.normalize_path(path) unless path&.include?("://")
+
+        raise TypeError, "path must be a String or Symbol" if path && !(path.is_a?(String) || path.is_a?(Symbol))
```
Comment (zzak) [inline actionpack/lib/action_dispatch/routing/route_set.rb:914]: I think if we want to introduce an error for this path, it must be deprecated first.

That is just my feeling though, I haven't looked deeper into the issue.

**Review by skipkayhil — COMMENTED** [review]
Since this method is private API I'm not sure it makes sense to add a type check to it. How are you currently getting a symbol in here?

**Comment by araishikeiwai** [comment]
@skipkayhil we have some API that relies on this method that has breaking tests upgrading to 7.1. I can typecheck in there before calling this method of course but I also noticed the difference in behaviour against symbols which is  a regression and not mentioned in the changelog.

**Comment by araishikeiwai** [comment]
Also I'm not sure what you meant by private API but it's available from Rails routes

```ruby
 Rails.application.routes.method(:recognize_path)
=> #<Method: ActionDispatch::Routing::RouteSet#recognize_path(path, environment=...) /Users/araishikeiwai/.rbenv/versions/3.2.7/lib/ruby/gems/3.2.0/gems/actionpack-7.1.5.1/lib/action_dispatch/routing/route_set.rb:885
```

**Comment by skipkayhil** [comment]
> Also I'm not sure what you meant by private API but it's available from Rails routes

If the method isn't documented in https://api.rubyonrails.org/, then it's private to the framework and can be changed at any time without deprecation/changelog.

**Comment by araishikeiwai** [comment]
That's fair, but the fact remains that it's still a widely used method

Screenshot 2025-03-25 at 14 41 53

If we're not going to add type check I was hoping we could still fix the change in behaviour somehow
