### ISSUE TITLE
NoMethodError: undefined method `delete_at' for #<User::ActiveRecord_Relation:0xc5fba48>

### ISSUE THREAD

**Issue by ArunSakthivel** [rails/rails#19089]
The below code showing error in rails 4.2.0
`User.all.delete_at(0)` 

I'm getting below error:
`NoMethodError: undefined method `delete_at' for #<User::ActiveRecord_Relation:0xc5fba48>`

Any idea? but the above code is working in rails 4.0

**Comment by ellimist** [comment]
`delete_at` is a method of the `Array` class, and you are trying it to call it on an `ActiveRecord_Relation` object. I understand you want to delete the first element in the list of users? If that's the case, you can use `User.first.delete`

**Comment by rafaelfranca** [comment]
Yes. This is what happened. If you want to work in am array call to_a first.
