### PR TITLE
Only de-dup/cache FileSystemResolvers in ViewPaths

### LINKED ISSUE #47449: ActionView::Template::Error: undefined method after recent ActiveView changes
### Steps to reproduce
1. web-console included in gem file
2. Start application in dev environment and trigger something that generates the Rails error page (e.g., navigating to a route that doesn't exist)
3. Hit refresh on the error page

### Expected behavior
The error page should refresh successfully (and assuming no code was changed, show the same error that was given initially.)

### Actual behavior
Upon refresh the detailed error page does not show and instead shows the "We're sorry something went wrong" error page.

It appears that this issue begin on 16 February 2022, resulting from one of the commits related to the ActionView refactor. I've retested and the expected behavior works fine w/ commit https://github.com/rails/rails/commit/a44559679aa26a54ea9867a68a78c5a4a55a3b9f and no longer works in https://github.com/rails/rails/commit/72abd6357d7909c15a460c716840159e5bb97ac7 forward.

The log shows:

`1:23:38 web.1  |   
21:23:38 web.1  | 
21:23:38 web.1  | ActionView::Template::Error: undefined method `__usr_local_rvm_gems_default_gems_web_console_______lib_web_console_templates_index_html_erb__4222570476681288892_26260' for #<ActionView::Base:0x0000000000cfd0>
21:23:38 web.1  |       from /usr/local/rvm/gems/default/bundler/gems/rails-72abd6357d79/actionview/lib/action_view/base.rb:264:in `public_send'
21:23:38 web.1  |       from /usr/local/rvm/gems/default/bundler/gems/rails-72abd6357d79/actionview/lib/action_view/base.rb:264:in `_run'`

### System configuration
**Rails version**: 7.1.0alpha (main)

**Ruby version**: 3.2.0

### PR DESCRIPTION
**Pull request by jhawthorn**
Fixes #47449

Previously I attempted to de-dup and cache any FileSystemResolver under the same path. This created issues because each Resolver caches its templates. Those cached templates only get compiled once into whatever compiled_method_container is passed on its first render. So separate compiled_method_containers must have different copies of a Template, and therefore separate copies of each Resolvers.

I tried a few approaches where I would have a separate cache of resolvers per-compiled-method-container, but I wasn't really successful as in most of the places we performed the casting we did not know or have access to the view context class and therefore compiled method container (it isn't stored in the LookupContext or ViewPath) and trying to add that relating created incompatibilities in some not-quite-public-but-still-widely used APIs for using ActionView directly.

This approach instead limits where we perform the de-dup and cache, to only descendants of ActionView::ViewPaths. These can be assumed to also inherit from ActionView::Rendering (I think ActionController::API is an exception here, which should be addressed in a future refactor) which means that they should all share the same compiled_method_container and therefore can all be cached safely together.

This should continue to ensure we don't leak memory from {append,prepend}_view_path at runtime, while maintaining compatibility with some of the more specialized uses of ActionView::Base as a standalone API. However this leaves open the possibility (which has always existed) of using that standalone API in a "leaky" way.

### CODE REVIEW

**Comment by jhawthorn** [comment]
@rafaelfranca updated this to avoid as many rebuilds of the watcher as possible. Hopefully that addresses the performance regression you saw.

File: actionview/lib/action_view/view_paths.rb [hunk 1]
```diff
@@ -28,14 +28,20 @@ def _prefixes # :nodoc:
         end
       end
 
+      def _build_view_paths(paths) #  :nodoc:
```
Comment (rafaelfranca) [inline actionview/lib/action_view/view_paths.rb:31]:
```suggestion
      def _build_view_paths(paths) # :nodoc:
```

File: actionview/lib/action_view/view_paths.rb [hunk 2]
```diff
@@ -28,14 +28,20 @@ def _prefixes # :nodoc:
...
+        return paths if ActionView::PathSet === paths
```
Comment (rafaelfranca) [inline actionview/lib/action_view/view_paths.rb:32]:
```suggestion
        return paths if ActionView::PathSet === paths

```

**Comment by rafaelfranca** [comment]
I'm not sure I got how this decrease the number of times the file watcher is initialized when a new engine path is added. `prepend_view_path` is always called with an array of strings, and if I got this code correctly, `cast_file_system_resolvers` would still be called for each one of engines. Am I missing some other cache layer?

**Comment by jhawthorn** [comment]
I see. I was hoping that your view paths would be appended as an array. I suppose that doesn't block this (as it fixes the other issue) but may not solve the regression you saw.

**Comment by rafaelfranca** [comment]
The view paths are appended by this code here https://github.com/rails/rails/blob/64ad045e472a60872e5547a381c3af896a546dfd/railties/lib/rails/engine.rb#L603-L609

That doesn't block this fix for sure.

**Review by rafaelfranca — APPROVED** [review]
