### ISSUE TITLE
ActionView : image_loading error

### ISSUE THREAD

**Issue by current-username** [rails/rails#42047]
When I add this following line I get an error. Am I doing something wrong?

### Steps to reproduce
```
# /myapp/config/environments/development.rb
Rails.application.configure do

  ...

  config.action_view.image_loading = "lazy"
end
```
### Actual behavior
We're sorry, but something went wrong.
NoMethodError (undefined method `image_loading=' for ActionView::Base:Class):

### System configuration
**Rails version**:
6.1.3.1

**Ruby version**:
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by lfalcao** [comment]
>  NoMethodError (undefined method `**image_loading=**' for ActionView::Base:Class):

It's missing a white-space between "image_loading" and "="

**Comment by current-username** [comment]
Nope ... The error message mentions 'image_loading=' but in my file I have 'image_loading = "lazy"'

**Comment by current-username** [comment]
Also, when I list all the methods of ActionView::Base
`ActionView::Base.methods`

I cannot find image_loading. Weird ...

**Comment by lfalcao** [comment]
It's not a method, it's just a variable. It could be '_config.action_view.blablabla = 123_' too :)

Try to clean the environment file to see if works. Like this:

config/environments/development.rb
```ruby
require "active_support/core_ext/integer/time"

Rails.application.configure do
  config.action_view.image_loading = "lazy"
end
```

**Comment by current-username** [comment]
I tried your solution but also this one. Both without success. I get the same error.

```
#/myapp/config/initializers/imageloading.rb

require 'active_support/core_ext/integer/time'
Rails.application.config.action_view.image_loading = "lazy"
```

**Comment by current-username** [comment]
I don't see any public example of this setting.
https://github.com/search?l=Ruby&q=action_view+image_loading+lazy&type=Code

Do you use it ?

**Comment by lfalcao** [comment]
@current-username this feature was introduced in https://github.com/rails/rails/pull/40839 and is not available on v6.1.3.1 only edge...

Reference:
- https://edgeguides.rubyonrails.org/configuring.html <- main branch - v7.0.0.alpha
- https://guides.rubyonrails.org/v6.1/configuring.html <- the version you're using - v6.1.3.1

**Comment by current-username** [comment]
@lfalcao my bad ... i thought edge was the last stable version.
I close the issue.
Thanks for your help.
