### ISSUE TITLE
Missing service_name for Disk service

### ISSUE THREAD

**Issue by jankeesvw** [rails/rails#40898]
I'm upgrading our Rails 6.0 app to Rails 6.1 and I'm running into an ActiveStorage issue, when I run my specs I see this error:

```
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "service_name" violates not-null constraint
DETAIL:  Failing row contains (1, j97m6cy8m95lm372pk5lrdkoyydi, file_3.jpg, image/jpeg, {"identified":true}, 59799, iI/7LCZqHqSyOL+vPEJ7JQ==, 2020-12-21 09:19:12.757828, null).
```

This is my `storage.yml`

```yml
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
```

I found [the migration](https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activestorage/db/update_migrate/20190112182829_add_service_name_to_active_storage_blobs.rb) that should add this column, there is this line in the migration which yields no result for me:

```ruby
>> configured_service = ActiveStorage::Blob.service.name
Traceback (most recent call last):
        1: from (irb):3
NoMethodError (undefined method `name' for #<ActiveStorage::Service::DiskService:0x00007f98af1ba2e8>)
```

**Comment by composerinteralia** [comment]
The `service_name` change is now mentioned in the [6.1 release notes](https://edgeguides.rubyonrails.org/6_1_release_notes.html#active-storage-notable-changes). Have you run `bin/rails app:update` to copy the migration into your application?

I am not able to reproduce that NoMethodError in Rails 6.1. Can you confirm the version you are running that on? Here is an example of `ActiveStorage::Service::DiskService#name` working in Rails 6.1

<details>
<summary>Reproduction Script</summary>

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.1.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    service = ActiveStorage::Blob.service

    assert_equal ActiveStorage::Service::DiskService, service.class
    assert_equal :local, service.name
  end
end
```

</details>

**Comment by jankeesvw** [comment]
Hi @composerinteralia, 

I'm so sorry, while I was working on my branch I rebased a couple of times. I think that changed my `Gemfile.lock` which reverted my Rails version to 6.0.3.4. I just changed it back to 6.1 and my errors disappeared.

Sorry for wasting your time. Thanks for the quick response.

**Comment by composerinteralia** [comment]
No worries. I'm glad it worked out!

**Comment by halo** [comment]
This was actually a very helpful hint 😄 Thank you.

(Besides, that "Reproduction Script" was the coolest piece of code I've seen in months).
