### ISSUE TITLE
ActiveSupport::XmlMini cannot use the JDOM backend for JRuby 9.3.x.x

### ISSUE THREAD

**Issue by andreimaxim** [rails/rails#44073]
### Steps to reproduce
When running JRuby you can configure `ActiveSupport::XmlMini` to use the JDOM backend to parse XML files:

```
ActiveSupport::XmlMini.backend = 'JDOM'
```

However, this does not work with JRuby 9.3.0.0 or higher because accessors are no longer bound to Java interface-based constants (see jruby/jruby#5732) and using `Node.<method_name>` (like `Node.TEXT`) raises an `NoMethodError` exception:

```
NoMethodError: undefined method `ATTRIBUTE_NODE' for Java::OrgW3cDom::Node:Module
Did you mean?  attr_reader
    /home/andrei/.rbenv/versions/jruby-9.3.2.0/lib/ruby/gems/shared/gems/activesupport-6.1.4.4/lib/active_support/xml_mini/jdom.rb:28:in `block in XmlMini_JDOM'
    org/jruby/RubyArray.java:1865:in `each'
    /home/andrei/.rbenv/versions/jruby-9.3.2.0/lib/ruby/gems/shared/gems/activesupport-6.1.4.4/lib/active_support/xml_mini/jdom.rb:28:in `<module:XmlMini_JDOM>'
    /home/andrei/.rbenv/versions/jruby-9.3.2.0/lib/ruby/gems/shared/gems/activesupport-6.1.4.4/lib/active_support/xml_mini/jdom.rb:18:in `<module:ActiveSupport>'
    /home/andrei/.rbenv/versions/jruby-9.3.2.0/lib/ruby/gems/shared/gems/activesupport-6.1.4.4/lib/active_support/xml_mini/jdom.rb:17:in `<main>'
    org/jruby/RubyKernel.java:1017:in `require'
    /home/andrei/.rbenv/versions/jruby-9.3.2.0/lib/ruby/gems/shared/gems/activesupport-6.1.4.4/lib/active_support/xml_mini.rb:194:in `cast_backend_name_to_module'
    /home/andrei/.rbenv/versions/jruby-9.3.2.0/lib/ruby/gems/shared/gems/activesupport-6.1.4.4/lib/active_support/xml_mini.rb:101:in `backend='
    jdom.rb:19:in `test_set_jdom_backend'
```

### Executable test case:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  ruby '2.6.8', engine: 'jruby', engine_version: '9.3.2.0'

  gem 'activesupport', '~> 6.1.0'
end

require 'active_support/xml_mini'
require 'minitest/autorun'

class JDOMTest < Minitest::Test
  def test_set_jdom_backend

    assert_raises(NoMethodError) do
      ActiveSupport::XmlMini.backend = 'JDOM'
    end
  end
end
```

### System configuration

This affects ActiveSupport v3.0.20 or newer with JRuby 9.3.0.0 or newer.

Note that ActiveSupport 7.0.0 and newer require Ruby 2.7.0 and currently JRuby 9.3.x.x tracks the 2.6.8 branch, but this issue will presumably be present later when JRuby will track 2.7.x.

### Proposed solution

Inspecting the `ActiveSupport::XmlMini_JDOM` class, there are two issues:

* [Lines 23-28](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/xml_mini/jdom.rb#L23..L28) which set a `NODE_TYPE_NAMES` variable and populate a `node_type_map` hash, however those are not used at all and should be removed
* [Line 83](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/xml_mini/jdom.rb#L83), [line 159](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/xml_mini/jdom.rb#L159) and [line 175](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/xml_mini/jdom.rb#L175) where `Node.TEXT_NODE` should be replaced with `Node::TEXT_NODE` which, according to @headius, should work fine in any JRuby version

If the two solutions mentioned above are acceptable, I can create a pull request.

Thanks!

**Comment by rafaelfranca** [comment]
Please open the PR

**Comment by SkipKayhil** [comment]
@andreimaxim are you still interested in creating a PR for this? If not, I can make it and add you as a co-author

**Comment by andreimaxim** [comment]
@SkipKayhil I sure am.

@rafaelfranca against which Rails branch should I open the PR, since Rails 7 requires Ruby 2.7.0+ and JRuby 9.3.x.x matches Ruby 2.6.8? Maybe `6-1-stable`?

**Comment by andreimaxim** [comment]
@SkipKayhil thanks for guiding me through the process. I think it's my first contribution to a significant open-source project and it's been a great experience. I'm really happy to be part of the Ruby & Ruby and Rails community.
