### PR TITLE
Fix no method error in utc_to_local

### LINKED ISSUE #40884: undefined method `utc_to_local_returns_utc_offset_times' for ActiveSupport:Module
### Steps to reproduce

```ruby
require 'active_support/time'
TIMEZONE = ActiveSupport::TimeZone.new('UTC')
p TIMEZONE.utc_to_local(Time.now)
```

### Expected behavior

It should print out the local time, with "UTC" appended to it.  Yes, this testcase is a bit bogus, but it was distilled from a larger application that worked with Rails 6.0 but now fails with Rails 6.1.

### Actual behavior

```
Traceback (most recent call last):
	3: from testtime.rb:4:in `<main>'
	2: from /var/lib/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:513:in `utc_to_local'
	1: from /var/lib/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:513:in `yield_self'
/var/lib/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:514:in `block in utc_to_local': undefined method `utc_to_local_returns_utc_offset_times' for ActiveSupport:Module (NoMethodError)
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

### PR DESCRIPTION
**Pull request by 8398a7**
### Summary

Fixes #40884 

This error occurs in v6.1.0 and does not occur in v6.0.3.4.

Reproduction Procedure

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # reproduce
  gem "activesupport", "6.1.0"
  # not reproducing
  # gem "activesupport", "6.0.3.4"
end

require "active_support/time"
require "minitest/autorun"
require "logger"

class BugTest < Minitest::Test
  def test_utc_to_local
    ActiveSupport::TimeZone.new('UTC').utc_to_local(Time.now)
  end
end
```

```
NoMethodError: undefined method `utc_to_local_returns_utc_offset_times' for ActiveSupport:Module
    /.../ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:514:in `block in utc_to_local'
    /.../ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:513:in `yield_self'
    /.../ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:513:in `utc_to_local'
    active_support_gem.rb:25:in `test_timezone'
```

### Other Information

I think this is the effect of this change.
https://github.com/rails/rails/commit/bf34c808f9936ecb160914cace45c655ec0924c7

### CODE REVIEW

**Comment by eugeneius** [comment]
https://github.com/rails/rails/issues/40884#issuecomment-751532211
