### PR TITLE
Fix unscoping association scope on joins not to raise an error

### LINKED ISSUE #38811: Association using unscope: NoMethodError: undefined method `children' for nil:NilClass
### Steps to reproduce
Have the following models:

```ruby
class Post < ApplicationRecord
  has_many :tags, -> { unscope(:where) }
end

class Tag < ApplicationRecord
  default_scope { where(locale: :en) }
end
```

The following code will crash (even if the `default_scope` is removed):

```ruby
Post.joins(:tags).to_sql
```

### Expected behavior
Join tags to posts without the default scope being applied. Should generate a query something like:

```
SELECT "posts".* FROM "posts" INNER JOIN "tags" ON "tags"."post_id" = "posts"."id"
```

This was the behaviour in Rails 5.2.3.

### Actual behavior
```
Exception: NoMethodError: undefined method `children' for nil:NilClass
--
 0: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:39:in `block in join_constraints'
 1: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:30:in `reverse_each'
 2: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:30:in `with_index'
 3: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:30:in `join_constraints'
 4: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:162:in `make_constraints'
 5: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:155:in `block in make_join_constraints'
 6: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:154:in `each'
 7: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:154:in `flat_map'
 8: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:154:in `make_join_constraints'
 9: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:85:in `join_constraints'
10: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1179:in `build_join_query'
11: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1164:in `build_joins'
12: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1044:in `build_arel'
13: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1016:in `arel'
14: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:810:in `block in exec_queries'
15: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:828:in `skip_query_cache_if_necessary'
16: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:797:in `exec_queries'
17: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:615:in `load'
18: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:250:in `records'
19: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:245:in `to_ary'
```

### System configuration
**Rails version**:
Works in 5.2.3, broken in 5.2.4.2 and 6.0.2.2.

**Ruby version**:
2.6.2

### PR DESCRIPTION
**Pull request by kamipo**
#29589 changed merging scope order to allow to unscope default scopes on
association scope (#29611), but that caused a regression #38811 that
accidentally allow join constraint which is required.

```
% bin/test test/cases/associations/has_many_associations_test.rb -n test_unscopes_the_default_scope_of_associated_model_when_used_with_include
Run options: -n test_unscopes_the_default_scope_of_associated_model_when_used_with_include --seed 32978

# Running:

E

Error:
HasManyAssociationsTest#test_unscopes_the_default_scope_of_associated_model_when_used_with_include:
NoMethodError: undefined method `children' for nil:NilClass
    ~/rails/activerecord/lib/active_record/associations/join_dependency/join_association.rb:39:in `block in join_constraints'
    ~/rails/activerecord/lib/active_record/associations/join_dependency/join_association.rb:30:in `reverse_each'
    ~/rails/activerecord/lib/active_record/associations/join_dependency/join_association.rb:30:in `with_index'
    ~/rails/activerecord/lib/active_record/associations/join_dependency/join_association.rb:30:in `join_constraints'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:171:in `make_constraints'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:196:in `block in walk'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:196:in `each'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:196:in `flat_map'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:196:in `walk'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:90:in `block in join_constraints'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:87:in `each'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:87:in `flat_map'
    ~/rails/activerecord/lib/active_record/associations/join_dependency.rb:87:in `join_constraints'
    ~/rails/activerecord/lib/active_record/relation/query_methods.rb:1226:in `build_join_query'
    ~/rails/activerecord/lib/active_record/relation/query_methods.rb:1211:in `build_joins'
    ~/rails/activerecord/lib/active_record/relation/query_methods.rb:1091:in `build_arel'
    ~/rails/activerecord/lib/active_record/relation/query_methods.rb:1063:in `arel'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:419:in `block in limited_ids_for'
    ~/rails/activerecord/lib/active_record/relation.rb:867:in `skip_query_cache_if_necessary'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:419:in `limited_ids_for'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:398:in `apply_join_dependency'
    ~/rails/activerecord/lib/active_record/relation.rb:839:in `block in exec_queries'
    ~/rails/activerecord/lib/active_record/relation.rb:867:in `skip_query_cache_if_necessary'
    ~/rails/activerecord/lib/active_record/relation.rb:834:in `exec_queries'
    ~/rails/activerecord/lib/active_record/relation.rb:639:in `load'
    ~/rails/activerecord/lib/active_record/relation.rb:250:in `records'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:508:in `find_take'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:98:in `take'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:458:in `find_one'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:442:in `find_with_ids'
    ~/rails/activerecord/lib/active_record/relation/finder_methods.rb:69:in `find'
    ~/rails/activerecord/test/cases/associations/has_many_associations_test.rb:2689:in `block in <class:HasManyAssociationsTest>'

bin/test test/cases/associations/has_many_associations_test.rb:2683
```

Required join constraint should not be allowed to unscoping.

Fixes #38811.

### CODE REVIEW

**Comment by alboyadjian** [comment]
Thank you!
