### ISSUE TITLE
partial render failed when rename a local variable use  "as:"

### ISSUE THREAD

**Issue by hwy801207** [rails/rails#26286]
partial render failed when use "as:"  to rename a local variable
 like this
<%= render partial: "product", as: "item" %> 
at the page  http://guides.rubyonrails.org/action_view_overview.html

the error message is 
undefined local variable or method `item' for #<#<Class:0x000000053dc200>:0x007fd688a25740>

when change to 
<%= render partial: "product", object: product, as: "item" %> 
it's ok 

rails version 5.0.1 
ruby version 2.3.0

**Comment by aaronang** [comment]
@hwy801207 I had a quick look at your problem and I can confirm the same problem occurs with Rails version 5.0.0.1. As far as I know there exists no Rails version 5.0.1. I assume it is a typo?

To reproduce these steps I have quickly created a Rails 5.0.0.1 project, which can be found here: [view_locals_as.zip](https://github.com/rails/rails/files/439262/view_locals_as.zip). Just run `rails s` and go to `localhost:3000/products/index` and you will see the error.

PS. I am quite new to Rails and if there are better ways to create reproducible steps for problems related to rendering, I would gladly receive feedback on how to improve.

**Comment by maclover7** [comment]
Hi all,

- @hwy801207: Thank you for reporting this documentation error! Can you please update the documentation to add in the `object:` key, to what we are passing to the `render` method?
- @aaronang: Good work on your first reproduction app! In the future, if you'd like, feel free to use any of Rails' "bug report templates", which are available [here](https://github.com/rails/rails/tree/master/guides/bug_report_templates).

Best recourse here is to update the documentation.

**Comment by aaronang** [comment]
@maclover7 Thank you for your reply! I was just wondering if you could provide me an example of how one of these templates can be used to reproduce rendering-related problems. In specific, how would such reproducible example look like for rendering partials?

**Comment by prakashmurthy** [comment]
Looks like https://github.com/rails/rails/commit/bef9484cf867ab261891d3431782e60c4e17f87f changed the earlier behavior and made the following part of the documentation outdated.

    By default ActionView::Partials::PartialRenderer has its object in a local variable with the same name as the template.

@nygrenh: I don't agree with the statement in your commit message that the behavior is not as intended. I think the documented behavior is useful and should be reverted back.  Please let me know if there are any other considerations in removing the default object in `ActionView::Partials::PartialRenderer`.

**Comment by nygrenh** [comment]
@prakashmurthy The commit you mentioned should not affect the behaviour of  actual local variables. All it does it removes extra values from the `local_assigns` hash in a case when there is *no local variable* with the same name defined inside partial. As far as I know the `local_assigns` hash does not affect what local variables will be defined defined in the view. As the commit does not undefine any local variables, I do not see how this change could cause the problem.

Here's the documentation for the `local_assigns` hash:
```
The local variables passed to sub templates can be accessed as a hash using the local_assigns hash. This lets you access the variables as:

Headline: <%= local_assigns[:headline] %>

This is useful in cases where you aren't sure if the local variable has been assigned. Alternatively, you could also use defined? headline to first check if the variable has been assigned before using it.
```
As why this change was made, it is related to the solution of the locals problem that is blocking https://github.com/rails/rails/pull/19272. Basically, the reason is that if we have a precompiled template that can be used no matter what local variable combination the template is being rendered with, we need to access all passed local variables through the `local_assigns` hash.  So naturally having extra stuff  in that hash would cause our heuristics to think a variable is defined even though it is not.

**Comment by prakashmurthy** [comment]
Thanks @nygrenh for the detailed response. I guess I read too much into the commit message details. 

Let me check further why the defaults are coming up nil / `render partial: "post"` is failing with `undefined local variable or method 'post'` error message.

**Comment by prakashmurthy** [comment]
Haven't been able to devote enough time to work on this issue; won't be able to get back to this soon.

Here is the summary of what I have found so far, should anyone else wants to take up the task of fixing this:
The [behavior documented in the guides](http://guides.rubyonrails.org/action_view_overview.html#the-as-and-object-options) (in the attached image below) work fine in Rails versions <= 3.2.x, and do not work in Rails 4.x and 5.x.

![view_default_local_variable](https://cloud.githubusercontent.com/assets/295689/18189391/bc78ed62-7077-11e6-937d-0eb819ff6202.png)

In Rails 3.x versions, by the time [this line](https://github.com/rails/rails/blob/db63406cb007ab3756d2a96d2e0b5d4e777f8231/actionview/lib/action_view/renderer/partial_renderer.rb#L343) is hit, the instance variable with the same name as the partial is included in the `locals` variable from `@variable` to `as` to `object` to `locals[as]`.

**Comment by maclover7** [comment]
PR to update the docs has been merged, going to close this issue out.
