### PR TITLE
Fully support datetime values in AR::Type::DateTime#type_cast_for_database

### LINKED ISSUE #18296: DateTime handling regression in 4.2.x
It seems DateTime objects are no longer always handled correctly in 4.2.x, for example with those settings (on top of just the default ones for new apps):

```ruby
config.time_zone = 'Berlin'
config.active_record.default_timezone = :local
```

And this table:

```ruby
create_table :tests do |t|
  t.datetime :datetime
end
```

I get:

```ruby
Test.where(datetime: 5.days.ago.to_datetime..DateTime.now).to_a
NoMethodError: undefined method `getlocal' for Sun, 28 Dec 2014 13:19:35 +0100:DateTime
        from /home/jarek/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/type/date_time.rb:14:in `type_cast_for_database'
...
```

The above works correctly in Rails 4.0.x and in Rails 4.1.x. It seems this commit by @sgrif introduced this issue:

https://github.com/rails/rails/commit/d5d734939864fa871daf8cef72b638aebf3b0f37

### PR DESCRIPTION
**Pull request by brainopia**
Fixes #18296

Since this method is inspired by https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L81, I've added the same conditioning to take into account `DateTime`.

Also I think the method should be extracted to be shared across `AR::Type::Time`, `AR::Type::Date` as well. It can be done in a separate commit.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Backported as 3dd29f4

**Comment by rafaelfranca** [comment]
> Also I think the method should be extracted to be shared across AR::Type::Time, AR::Type::Date as well. It can be done in a separate commit.

Could you explain better?

**Comment by brainopia** [comment]
`AR::ConnectionAdapters::Quoting` handles quoting/typecasting of values passed to database. `Date` and `Time` instances (with descendants `DateTime` and `AS::TimeWithZone`) go through `#quoted_date` method of the mentioned module.

There is an effort to move typecast logic to `AR::Type` classes. In d5d734939864fa871daf8cef72b638aebf3b0f37 @sgrif replicated the logic for `AR::Type::DateTime` with `#type_cast_for_database`. Since this effort is probably aimed at eventually removing `#quoted_date` then this method should be shared with `AR::Type::Date`, `AR::Type::Time` as well.

Although I'm not sure how would it be possible to remove `#quoted_date` while `#quote/#type_cast` support invocation without a corresponding column. And until such a removal current situation looks a bit dubious. Both `AR::Type::DateTime#type_cast_for_database`  and `#quoted_date` will be invoked in the same run and repeatedly call `zone_conversion_method`.  May be @sgrif has accidentally added `AR::Type::DateTime#type_cast_for_database`?

**Comment by sgrif** [comment]
No, I will eventually remove `quoted_date`
