### ISSUE TITLE
Issue creating fixtures ActiveRecord::FixtureSet

### ISSUE THREAD

**Issue by hugoerg56** [rails/rails#40301]
### Steps to reproduce
after update from rails 5 to 6 and only running rspec

### Expected behavior
 Should create fixtures without errors

### Actual behavior
```
NoMethodError:
    undefined method `name' for nil:NilClass
    ruby-2.7.1/gems/activerecord-6.0.0/lib/active_record/test_fixtures.rb:205:in block in load_fixtures
```

also found that the issue is on ActiveRecord::FixtureSet create_fixtures method
```
  if fixture_files_to_read.any?
    fixtures_map = read_and_insert(
        fixtures_directory,
        fixture_files_to_read,
        class_names,
        connection,
     )
     cache_fixtures(connection.call, fixtures_map)
   end
   cached_fixtures(connection.call, fixture_set_names)
```

changing that code to this (fix the issue):
```
 c = connection.call
  if fixture_files_to_read.any?
    fixtures_map = read_and_insert(
        fixtures_directory,
        fixture_files_to_read,
        class_names,
        connection,
     )
     cache_fixtures(c, fixtures_map)
   end
   cached_fixtures(c, fixture_set_names)
```

Looks like the call is re-creating the connection and should be cached to match in:
```
    def cache_for_connection(connection)
      @@all_cached_fixtures[connection]
    end
```

any idea to solve this, maybe a missing configuration?

### System configuration
**Rails version**:
rails 6.0.0

**Ruby version**:
ruby-2.7.1

**Comment by p8** [comment]
Hi @hugoerg56,
This is a bit hard to reproduce. Could you output some of the values? For example by changing the code to:

```
  if fixture_files_to_read.any?
    puts fixtures_directory.inspect
    puts fixture_files_to_read.inspect
    puts class_names.inspect

    fixtures_map = read_and_insert(
        fixtures_directory,
        fixture_files_to_read,
        class_names,
        connection,
     )
     cache_fixtures(connection.call, fixtures_map)
   end
   cached_fixtures(connection.call, fixture_set_names)
```

**Comment by hugoerg56** [comment]
Hi @p8 this is the output

`"/Users/xxxxx/Trabajo/project_name/bio/spec/fixtures"`

```
["products", "xero_syncs", "appraisal_results", "customers", "comfy/cms/categories", "comfy/cms/pages", "comfy/cms/categorizations", "comfy/cms/layouts", "comfy/cms/files", "comfy/cms/fragments", "comfy/cms/sites", "addresses", "marketing_materials", "catalogs", "ghosts", "chemical_ingredients", "eresponses", "appraisals", "messages", "gl_accounts", "orders", "brand_localisations", "playlist_items", "users", "condition_ingredients", "user_actions", "thesaurus_items", "front_page_banners", "ingredients", "payments", "selections", "promotions", "suppliers", "activities", "attendances", "localisations", "prices", "samples", "equivalents", "product_buttons", "related_products", "inquiries", "equestions", "attachments", "tasks", "playlists", "movements", "questions", "front_page_tiles", "fyis", "video_chapters", "chemicals", "notes", "coupons", "versions", "brands", "batches", "items", "xeros", "article_products", "contents", "distributions", "enotes", "policies", "stores", "weightings", "packsize_products", "associates", "boms"]
```

```
#<ActiveRecord::FixtureSet::ClassCache:0x00007fd5e0918f80 @class_names={}, @config=ActiveRecord::Base>
```

**Comment by hugoerg56** [comment]
@p8 doing a monkeypatch with this do the trick: 

```
        c = connection.call
        fixture_files_to_read = fixture_set_names.reject do |fs_name|
          fixture_is_cached?(c, fs_name)
        end

       
        if fixture_files_to_read.any?

          fixtures_map = read_and_insert(
            fixtures_directory,
            fixture_files_to_read,
            class_names,
            connection,
          )
          cache_fixtures(c, fixtures_map)
        end
        
        cached_fixtures(c, fixture_set_names)
      end
```
