### ISSUE TITLE
NoMethodError: undefined method `start_with?` for Symbol

### ISSUE THREAD

**Issue by wagenet** [rails/rails#37709]
Looks like this issue was caused by https://github.com/rails/rails/commit/ad767034c968f425c68fc1c9b09f78acfe5a7757#diff-0a2aa4342f48ecd9c863d4f2012f2e0dR8

@kamipo

**Comment by kamipo** [comment]
Will be fixed by #37708.

**Comment by kamipo** [comment]
Fixed
