### PR TITLE
Fix invalid direct upload form attribute

### LINKED ISSUE #43698: file_field helper raises an exception if attribute does not match an active storage attachment
### Steps to reproduce
```ruby
model Gallery
  has_many_attached :images
end
```

```rhtml
<%= form_with model: Gallery.new do |form| %>
  <%= form.file_field :image, direct_upload: true %>
<% end %>
```

```irb
ActionView::Template::Error (undefined method `options' for nil:NilClass):
```

In this case the attachment is called `images`, but we passed the atribute `image`. The bug was introduced in PR #38957, which added per attachment service. The problem happens because this line:
```ruby
attachment_reflection = options[:object].class.reflect_on_attachment(name)
```

... ends with `attachment_reflection = nil` and then this line:
```ruby
service_name = attachment_reflection.options[:service_name] || ActiveStorage::Blob.service.name
```

... causes the `nil` exception.

### Expected behavior
The page is rendered using the default service

### Actual behavior
An exception is raised.

### System configuration
**Rails version**: 193289dbbe146c56ec16faf8dd1a2c88611feb83
**Ruby version**: 3.0.2

cc: @DmitryTsepelev @gmcgibbon

### PR DESCRIPTION
**Pull request by gmcgibbon**
https://github.com/rails/rails/pull/38957

Closes https://github.com/rails/rails/issues/43698

### CODE REVIEW

**Comment by brenogazzola** [comment]
Found another possible problem (not sure if I should open another issue). If the form is not given a `model`, only a `scope`, it will not generate the `data-direct-upload-token` and the upload will not work.

**Comment by gmcgibbon** [comment]
> Found another possible problem (not sure if I should open another issue). If the form is not given a model, only a scope, it will not generate the data-direct-upload-token or data-direct-upload-attachment-name, and the upload will not work.

I think we should raise in that situation. Supplying the `direct_upload` key is clear intent that the developer wants to use Active Storage. I'll add that to this PR. Thanks!

**Comment by brenogazzola** [comment]
Might be a good idea to add this to the upgrade guide so others can prepare in advance, as well as a notice about the change in the JS library. If I had not checked the discussion in the original PR I’d have been pretty confused.

**Comment by brenogazzola** [comment]
I'm not sure if I'm missing something in the code, or if it was not considered in the original PR: 

How do I handle form objects, which are simply POROs and not active record models?

**Comment by brenogazzola** [comment]
One more thing: Would it be possible to turn off the token, at least in the test env? Since we upgraded, some system tests that we never had a problem with are now flakky due to `InvalidDirectUploadTokenError`.

**Comment by gmcgibbon** [comment]
> I'm not sure if I'm missing something in the code, or if it was not considered in the original PR:
> How do I handle form objects, which are simple POROs and not active record models?

It wasn't considered. Since upload tokens are coupled to Active Record models, you need a model and attachment to tie an upload to. I don't think plain Active Model would work with currently either. Can you provide an example snippet or test case to show how this previously worked?

**Comment by gmcgibbon** [comment]
> One more thing: Would it be possible to turn off the token, at least in the test env? Since we upgraded, some system tests that we never had a problem with are now flakky due to InvalidDirectUploadTokenError.

We can make multi-service uploads opt-in depending on how much it is breaking apps. The feature seems to still need some work on the action view integration end.

**Comment by brenogazzola** [comment]
> It wasn't considered. Since upload tokens are coupled to Active Record models, you need a model and attachment to tie an upload to. I don't think plain Active Model would work with currently either. Can you provide an example snippet or test case to show how this previously worked? I can add test coverage so these contracts are better enforced.

Previously direct upload made no assumptions about what its file was going to be attached to. It only uploaded the file to the configured service and returned to token that was used. 

Here's the most bare bones use case that used to work and no longer does. Instead of using a form object, it uses a plain `file_field_tag`. I've also intentionally removed the attribute name to ensure direct upload has absolutely no information about where the file is going to be attached.

View:
```erb
<%= form_with url: photos_path do |form| %>
  <%= file_field_tag nil, name: "photo[file]", direct_upload: true %>
  <%= form.submit "Save" %>
<% end %>
```

Controller:
```ruby
def create
  Photo.create!(photos_params)
  head :ok
end

private
  def photo_params
    params.require(:photo).permit(:file)
  end
```

Model:
```ruby
class Photo
  has_one_attached :file
end
```

**Comment by brenogazzola** [comment]
> We can make multi-service uploads opt-in depending on how much it is breaking apps. The feature seems to still need some work on the action view integration end. I'll review that once this patch is in. The unreleased changes to JS libraries may be causing your app some issues too if you aren't linking them to your app.

I haven't read through the entire implementation, but would it be possible to modify the `direct_upload` attribute to take a string with the model/attachment instead of a bool? That would solve most of the problems:

```
<%= file_field_tag nil, name: "photo[file]", direct_upload: "photo#file %>
```

**Comment by gmcgibbon** [comment]
> Here's the most bare bones use case that used to work and no longer does

Is the photo class an Active Model or an Active record? There's no superclass specified.

> but would it be possible to modify the direct_upload attribute to take a string with the model/attachment instead of a bool?

Yes, that's what I have in this PR to fix the contract of `file_field_tag`, but in a hash. `file_field` can still use `direct_upload: true` because the model and attachment can be inferred from the `options[:object]`.

**Comment by brenogazzola** [comment]
Sorry, Photo is a normal model. But in this case it does not make much difference. Since we are using a standard tag helper not a form builder one, direc upload does not have access to the forms object. 

I’ve pulled the JS file from the gem into my JS folder and included it in my bundle. The uploads are all working now, but are still flakky in the CI.

**Comment by brenogazzola** [comment]
Thinking a bit, couldn’t the direct uplod controller assume that if no attachment name is provided he can simply upload to the default service? And then only create the attachment name/token if the attachment in question defined a service other than the default?

This would mean no migration burden for projects already using active storage, while supporting projects that need per attachment service.

**Comment by brenogazzola** [comment]
Hey @gmcgibbon anything I can help with this? I’m not skilled enough with JS to help there, but I’m fine with the ruby part.

**Comment by gmcgibbon** [comment]
> Thinking a bit, couldn’t the direct uplod controller assume that if no attachment name is provided it can simply upload to the default service?

Yes, that's possible, but I'd rather it be consistent for all uploads to have tokens included. If this breaks apps, we could just make it opt-in behaviour while upgrading, but I'm not convinced that's necessary yet.

> The uploads are all working now, but are still flakky in the CI.

If you could debug why the tests are flaky on your end, that would be helpful. I wouldn't expect them to be. I should have time to work on this next week.

**Comment by brenogazzola** [comment]
> Yes, that's possible, but I'd rather it be consistent for all uploads to have tokens included. 

Alright. With your PR it’s not as much extra work as we had with the original one, so it sounds like a good compromise between correctness and ease. 

> If you could debug why the tests are flaky on your end,

I’ll see if I can figure it out. They were ocasionallu breaking in production too. File uploads worked most of the time but every once in a while I’d get an invalid token error.

**Comment by brenogazzola** [comment]
A user in issue #43895 has mentioned another use case that is no longer supported: Using direct upload without a session. Seems he has a react app and disable CSRF tokens and sessions.

**Comment by gmcgibbon** [comment]
Sounds like we're rewriting this feature, and the implementation will change significantly, so I'm going to close this.
