### ISSUE TITLE
ActiveSupport::Duration got a breaking change in 5.2.5/6

### ISSUE THREAD

**Issue by lirossarvet** [rails/rails#42155]
### Steps to reproduce

Between version 5.2.4.5 and version 5.2.6, ActiveSupport inherited a breaking change to what `ActiveSupport::Duration.build` accepts. Namely, Strings will now raise an error. This is fundamentally a result of this [commit](https://github.com/rails/rails/commit/39a8266a4c061d447b679f755dd1ed8485a9397f) being included into a 5.2.6 release when it was not part of [5.2.4.5](https://github.com/rails/rails/compare/v5.2.4.5...v5.2.6). I would've hoped something like this would be part of Release Notes as given at least. I'm also not sure of any other features that may cause breaking or unexpected behavior that are part of this.

### Expected behavior

In ActiveSupport 5.2.4.5, `ActiveSupport::Duration` accepted a String value:

```
> d = ActiveSupport::Duration.build('%.4f' % 1.00)
=> 1.0 second
```

### Actual behavior

ActiveSupport 5.2.6 does the following:

```
>  = ActiveSupport::Duration.build('%.4f' % 1.00)
NoMethodError: undefined method `round' for "1.0000":String
```

### System configuration
**Rails version**: 5.2.6

**Ruby version**: 2.6.6

**Comment by lirossarvet** [comment]
Looks like 5.2.5 also got this fun change: https://github.com/rails/rails/compare/v5.2.4.5...v5.2.5

Unfortunately 5.2.5 only really calls out the marcel change because of the MimeMagick stuff

**Comment by rafaelfranca** [comment]
@kamipo do you remember why that change was backported to 5-2-stable?

**Comment by kamipo** [comment]
It was a year and a half ago (Dec 5, 2019), so I'm not 100% confident, but according to the description of #37882, it was a fix the behavior caused by #31310. Since latest stable version was 6.0.1 (November 05, 2019) at that time, I suppose I backported #37882 as the fix for the regression #31310 for 5.2 users.

I'm not sure `Duration.build` was intended to work with a string, if do that it will cause weird behavior on Duration comparison #37012, and now it is disallowed by #37013.

**Comment by lirossarvet** [comment]
For sure! I don't think it was either, but some people were (us 😬) and it caught us by surprise. It's pretty easy for us to swap to passing a float in.

I think it would be kind to add something on the changleog at least for ActiveSupport in the 5-2-stable branch? I can open a PR for that if you'd like. I know we can't probably do release note updates on the site, but that might at least help catch someone a little less by surprise. It also might not matter that much since Rails 6 just outright raises a TypeError, very explicitly not accepting it.

**Comment by ghiculescu** [comment]
I'm going to close this as it only impacts 5.2. Adding something to the 5-2-stable changelog isn't a bad idea, if you want to make a PR please go ahead. Hopefully this issue existing will also help people find it if they have issues - thank you for raising it.
