### ISSUE TITLE
assert_changes stopped working after rails 6.1 on including ActiveSupport::Testing::Assertions

### ISSUE THREAD

**Issue by pedrosnk** [rails/rails#42869]
### Steps to reproduce

Hi, dear rails team. I came with this small issue that I found while maintaining an internal library for the company I work for.

Before on rails 6.0.4 It was possible to include the `ActiveSupport::Testing::Assertions` on my classes that comes from `Minitest::Unit` and all the assertions there just worked. After updating to rails `6.1`. The problem doesn't happen if my test class extends `ActiveSupport::TestCase` but that is not a possibility if we are using `Minitest::Spec`.

Even with possible workarounds I still think the module should be able to work without the need of extending the `ActiveSupport::TestCase` class.

I think this could be fixed in two ways

1. change [this line](https://github.com/rails/rails/blob/1488cb84400cdee781d39707dc65e44d348eeaa8/activesupport/lib/active_support/testing/assertions.rb#L192) to use refute_equals as it is [defined here](https://github.com/rails/rails/blob/675d9ffb6eb544b527a19bd5d128fbd96cb5acda/activesupport/lib/active_support/test_case.rb#L140)

2. Move the alias from ActiveSupport::TestCase to ActiveSupport::Testing::Assertions as this late class is [included on TestCase](https://github.com/rails/rails/blob/675d9ffb6eb544b527a19bd5d128fbd96cb5acda/activesupport/lib/active_support/test_case.rb#L131)

```rb
# frozen_string_literal: true
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '6.1.4 ' # started breaking on 6.1.0 works on 6.0.4
end

require "minitest/autorun"
require "active_support/testing/assertions"

describe :assert_changes do
  include ActiveSupport::Testing::Assertions

  it "counts" do
    counter = 1
    assert_changes( -> { counter } ) do
      counter = 2
    end
  end
end
```

### Expected behavior

this used to work before 6.0.4 and now is not working after 6.1

### Actual behavior

breaks with the message
```
Error:
assert_changes#test_0001_counts:
NoMethodError: undefined method `assert_not_equal' for #<#<Class:0x00007fbbe4b2a488>:0x00007fbc23a3e828 @NAME="test_0001_counts", @failures=[#<Minitest::UnexpectedError: Unexpected exception>], @assertions=0, @time=5.49999822396785e-05>
Did you mean?  assert_equal
    /Users/user/.gem/ruby/3.0.2/gems/activesupport-6.1.4/lib/active_support/testing/assertions.rb:192:in `assert_changes'
    script.rb:20:in `block (2 levels) in <class:FooTest>'
```

### System configuration
**Rails version**: 6.1 +

**Ruby version**: 3.0.2 tested on 2.7.4 as well
