### ISSUE TITLE
active_support/core_ext/marshal breaking jRuby Marshal

### ISSUE THREAD

**Issue by erikogan** [rails/rails#28342]
### Steps to reproduce

I am trying to upgrade a jRuby Rails app from 5.0.0 to 5.0.2. The following test fails on JRuby 9k (I tested 9.1.8.0 & 9.1.6.0) and passes on MRI 2.4.0:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # gem 'activesupport', '5.0.2' # 5.0.1 works
  gem 'rails', github: 'rails/rails'
end

require 'active_support'
require 'active_support/core_ext/marshal'
require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_marshal
    # refute_raises(NoMethodError) { Marshal.load(Marshal.dump({})) }
    begin
      Marshal.load(Marshal.dump({}))
      @pass = true
    rescue NoMethodError => nme
      raise nme unless nme.message =~ /undefined method \Wcall\W/
      @pass = false
    end

    assert_equal true, @pass
  end
end
```

It’s not clear to me why this is failing, and looks to me like you might be tickling a jRuby bug, but if that is true, I thought you might want to work around it. (I will file an issue in the jRuby repo referencing this issue.)

### Expected behavior
`Marshal.load` should work as expected

### Actual behavior
```
NoMethodError: undefined method `call' for nil:NilClass
Did you mean?  caller
    load at org/jruby/RubyMarshal.java:145
    load at /Users/erik/.rbenv/versions/jruby-9.1.8.0/lib/ruby/gems/shared/gems/activesupport-5.0.2/lib/active_support/core_ext/marshal.rb:4
  <main> at activesupport_bug.rb:15
```

### System configuration
5.0.2, also master. 5.0.1 works.

jRuby 9.1.8.0 (also .6.)

**Comment by rafaelfranca** [comment]
May it be related with https://github.com/rails/rails/commit/a72498f776b2e67b7e3a074423181defcd06fc56? We are passing `nil` as the second argument by default and I think JRuby expect that to always be a proc.

**Comment by rafaelfranca** [comment]
Yeah, [MRI accept the proc argument as `nil`](https://github.com/ruby/ruby/blob/trunk/marshal.c#L2085) but maybe JRuby doesn't, but it should. I'll consider it a JRuby bug and close the issue here since officially Rails doesn't support JRuby yet.

**Comment by rafaelfranca** [comment]
But, since it worked in 5.0.1, what we can do is revert the change in 5.0.3 but keep in 5.1.0.

**Comment by erikogan** [comment]
@rafaelfranca That’s probably it. I can confirm it later today. If it’s true, I’ll update the jRuby issue to reflect that difference.

**Comment by erikogan** [comment]
@rafaelfranca Confirmed: 

```ruby
puts Marshal.load(Marshal.dump(without: :proc)).inspect
puts Marshal.load(Marshal.dump(with: :proc) {|o| puts o.inspect}).inspect
puts Marshal.load(Marshal.dump(with: :nil_proc), nil).inspect
```

Exhibits the same behavior, and works fine in MRI.

**Comment by maclover7** [comment]
Looks like this issue has been fixed upstream in JRuby, via https://github.com/jruby/jruby/commit/64c7ea04829a77cf5eac2f368bb3e0131ac37646.
