### ISSUE TITLE
mail_ext from_address not working

### ISSUE THREAD

**Issue by romarioliveira25** [rails/rails#46810]
After upgrade rails from 6.0.3 to 6.1.7 `from_address` not working at Mail object instance, occurring the error below:

```
[37] pry(main)> mail.from_address
NoMethodError: undefined method `address_list' for #<Mail::FromField:0x00007f0d341bfda8>
Did you mean?  address
from /usr/local/bundle/ruby/2.7.0/gems/mail-2.8.0/lib/mail/field.rb:233:in `method_missing'
```

To workarround it, a need change to use `mail.header[:from].element.addresses.first`

Environment:
Rails 6.1.7
Ruby 2.7.7
Mail 2.8.0

Any know issue about breaking changes at that method?

https://github.com/rails/rails/blob/6d581c43a77b8945df3d427273d357b67c303077/actionmailbox/lib/action_mailbox/mail_ext/addresses.rb#L5-L7

**Comment by skipkayhil** [comment]
Hey @romarioliveira25, thanks for opening an issue!

The error is due to a change in mail `2.8.0`. A fix was made to `main` in #46643, and was backported to `7-0-stable` in 05133ee198213ba1fc3b8ac8323646ffee60fd62 and `6-1-stable` in f5463f314886016fb40199d1265cacddf64ea357.

6.1 will only get new releases for Security Issues per the [maintenance policy](https://edgeguides.rubyonrails.org/maintenance_policy.html).

So you can either:
- point your Gemfile at `6-1-stable`: `gem "rails", github: "rails/rails", branch: "6-1-stable"`
- upgrade Rails to 7 and point it at `7-0-stable` until a new 7.0 version is released (at which point you can use that)
- downgrade `mail` to `2.7`

I'm going to close this because the issue has been addressed in stable branches, but feel free to reply if you have any questions!
