### ISSUE TITLE
Rails v6.0.1 error when using engine routes in System Tests

### ISSUE THREAD

**Issue by chalofa** [rails/rails#37754]
### Steps to reproduce
When you use a Rails mountable engine, and in your System Tests you try to use the route helpers (aka, `engine_name.root_url`), in Rails v6.0.1 you get an undefined error.

This only affect tests that inherit from `ActionDispatch::SystemTestCase` (System Tests)...
Tests using `ActionDispatch::IntegrationTest` work just as expected...

After bisecting, this is the first bad commit:
https://github.com/rails/rails/commit/7982363

And, per the changelog, this seems to be the code what is breaking this:

```
# actionpack/CHANGELOG.md
*   `ActionDispatch::SystemTestCase` now inherits from `ActiveSupport::TestCase`
    rather than `ActionDispatch::IntegrationTest`. This permits running jobs in
    system tests.
    *George Claghorn*, *Edouard Chin*
```

I guess the `actionpack` commit is:
https://github.com/rails/rails/commit/ea77dbff

- [ ] create test to reproduce error
- [x] find root cause in Rails v6.0.1 associated gems

### Expected behavior
Same as Rails v6.0.0:
System Tests should be able to use Rails engine route helpers.

### Actual behavior
In Rails 6.0.1:
Rails engine route helpers (`engine_name.root_url`) cannot be used because `engine_name` is undefined:

```
NameError: undefined local variable or method `engine_name' for #<SystemTest:0x00007f93eb38d278>
```

### System configuration
**Rails version**:
Rails v6.0.1

**Ruby version**:
reproduced with Ruby 2.6.5
