### ISSUE TITLE
5.0.0.1 / actionpack - undefined method `ref' for nil:NilClass*

### ISSUE THREAD

**Issue by badlamer** [rails/rails#26912]
### Steps to reproduce

Reproduced with **webmock** gem

``` ruby
      stub_request(:any, 'http://app')
        .to_rack(Rails.application)
```
#### Error

```
     Failure/Error: Net::HTTP.get('app', '/')

     NoMethodError:
       undefined method `ref' for nil:NilClass
```
#### Location

```
~/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:280:in `_wrapper_enabled?'
```
### Expected behavior

in https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/params_wrapper.rb#L278 request.has_content_type? should be return false for nil CONTENT_TYPE header
### Actual behavior

 request.has_content_type? return true for nil CONTENT_TYPE header
### System configuration

**Rails version**: 2.3.1

**Ruby version**: 5.0.0.1

**Comment by badlamer** [comment]
Broken in https://github.com/rails/rails/commit/a9f28600e901b11a9222e34bfae8642bfb753186

**Comment by maclover7** [comment]
Investigating.

**Comment by maclover7** [comment]
Opened #27007.
