### ISSUE TITLE
ActiveRecord 5.0.0.1 -> 5.0.6 nested join query syntax change

### ISSUE THREAD

**Issue by shterrett** [rails/rails#30675]
I had a query that was previously working in ActiveRecord 5.0.0.1:

```ruby
  Booking.joins(trip_price: { trip: :transitions })
            .where(traveler: traveler, trip_price: { trip: { trip_transitions: { most_recent: true, to_state: Trip::CANCELLED } } }
```

But after upgrading to ActiveRecord 5.0.6, I got the following error:

```
NoMethodError:
       undefined method `singularize' for :trip_transitions:Symbol
```

I was able to change the query to the following:

```ruby
 Booking.joins(trip_price: { trip: :transitions })
   .where(traveler: traveler, trip_price: { "trips" => { "trip_transitions" => { most_recent: true, to_state: Trip::CANCELLED } } }
```

The two changes are that the inner keys needed to be strings, and the `trips` key needed to be pluralized. Then the query ran again.

### Steps to reproduce

Craft a query with a nested join and nested where clause operating on the join using the hash query syntax and symbol keys

### Expected behavior

The query should run as it did in ActiverRecord 5.0.0.1

### Actual behavior

A `NoMethodError` is thrown for the first **inner** key in the where clause that the `singularize` method is not present.

### System configuration
**Rails version**: 5.0.6

**Ruby version**: 2.3.4

**Comment by sgrif** [comment]
Please provide a script we can use to reproduce the issue using [our standard bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb) or at least a stack trace

**Comment by kamipo** [comment]
Backported in 589edb84f86b2a100490319b31c0fe00fe4d24e4.
