### ISSUE TITLE
alias_attribute broken in Rails 7.1.4

### ISSUE THREAD

**Issue by benlangfeld** [rails/rails#52820]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activemodel", "= 7.1.4"
end

require "minitest/autorun"
require "active_model"

# Reproduce example from documentation
# https://guides.rubyonrails.org/active_model_basics.html#method-alias-attribute
class Person
  include ActiveModel::AttributeMethods

  define_attribute_methods :name
  attr_accessor :name

  alias_attribute :full_name, :name
end

class BugTest < Minitest::Test
  def test_aliased_attribute
    person = Person.new
    person.name = "Joe Doe"

    assert_equal "Joe Doe", person.name
    assert_equal "Joe Doe", person.full_name
  end
end
```

### Expected behavior
Tests pass

### Actual behavior
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Run options: --seed 61935

# Running:

E

Finished in 0.000626s, 1597.4438 runs/s, 1597.4438 assertions/s.

  1) Error:
BugTest#test_aliased_attribute:
NoMethodError: undefined method `attribute' for an instance of Person
    /Users/blangfeld/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/attribute_methods.rb:507:in `method_missing'
    /Users/blangfeld/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/attribute_methods.rb:268:in `name'
    alias.rb:31:in `test_aliased_attribute'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: 7.1.4 (works in 7.1.3.4)

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]

**Comment by benlangfeld** [comment]
It appears likely that https://github.com/rails/rails/pull/52145 broke this.

**Comment by Earlopain** [comment]
Almost, I've bisected this to https://github.com/rails/rails/pull/52118. This also happens in 7.2 and main.

cc @casperisfine

**Comment by benlangfeld** [comment]
It's surprising that there's no test coverage of this basic usage in activemodel. There are only unit tests of tangential behaviour.

**Comment by byroot** [comment]
Thanks for the repro, I'll see what I can do.

**Comment by byroot** [comment]
Got a tentative fix here: https://github.com/rails/rails/pull/52822, it fix your repro script but there are a few edge cases left, and also I need to add some tests. So I kinda want to sleep on it.

**Comment by byroot** [comment]
I merged the wrong version of the fix by accident. Redoing it.

**Comment by benlangfeld** [comment]
Thanks @byroot !

**Comment by byroot** [comment]
It will be yes. Milestone are only for things that need more work, this was backported to 7-1-stable. You can point your Gemfile to the 7-1-stable branch if you need the fix urgently.

**Comment by joe-sharp** [comment]
Much appreciated! Its a little trickier for us because a dependency of ours needs the fix, but I think we can make something work for us for now. Thanks for the quick response!
