### ISSUE TITLE
Wrong backtrace (ActionView::MissingTemplate) when exception in partial with variant

### ISSUE THREAD

**Issue by joallard** [rails/rails#28741]
I'm having a hard time find the cause of this especially because the backtrace seems to come from the wrong place, but here's what I have.

```gherkin
Given a view `foos/show.haml` with """
  render partial: 'foos/foo', collection: @foos, variants: :grid
"""
And a partial `foos/_foo+grid.haml` with "- raise"
When I load `show.haml`
Then I should see the exception in the partial template

# Actual: I get an `ActionView::MissingTemplate` error from the `show.haml`
```

* Rails 5.1.3, Ruby 2.4.0
* Rails 5.0.2, Ruby 2.2.6

Does this sound like something? ~~I'll try to get a repro case going~~
(Edit) See reproduction in comment#3

Notes:
* Removing the `variants` parameter makes the trace bubble correctly

**Comment by joallard** [comment]
I'm trying to work out how to make an ActionView test case with some lookup paths. Here's where I am now:

```rb
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "5.0.2"

  gem "pry-rails"
  gem "pry-rescue"
  gem "pry-stack_explorer"
end

require "rack/test"
require "action_controller/railtie"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token    = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/foo" => "foos#show"
  end
end

class FoosController < ActionController::Base
  def show
    @foos = [1,2,3]

    Pry.rescue do
      if params[:variant]
        render partial: "foos/foo", collection: @foos, variants: :grid
      else
        render partial: "foos/foo", collection: @foos
      end
    end
  end
end

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_stuff
    get "/foo", variant: :grid
    assert "zomg".present?
    refute "".present?
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by rafaelfranca** [comment]
One new rails application also helps to reproduce the bug.

**Comment by joallard** [comment]
Can't believe I forgot about that. 

https://github.com/joallard/rails-28741

The diff from Rails new (https://github.com/joallard/rails-28741/commit/2f5a8932d198365a303864b7e50d7bc14dc55b1d):

```diff
diff --git a/app/controllers/foos_controller.rb b/app/controllers/foos_controller.rb
new file mode 100644
index 0000000..4f86b54
--- /dev/null
+++ b/app/controllers/foos_controller.rb
@@ -0,0 +1,6 @@
+class FoosController < ApplicationController
+  def show
+    @foos = [1,2,3]
+    render partial: "foos/hasvariant", collection: @foos, variants: :grid
+  end
+end
diff --git a/app/views/foos/_hasvariant+grid.erb b/app/views/foos/_hasvariant+grid.erb
new file mode 100644
index 0000000..554c3b6
--- /dev/null
+++ b/app/views/foos/_hasvariant+grid.erb
@@ -0,0 +1,2 @@
+<h2>This is a variant partial for an element of the @foo array</h2>
+<% method_that_doesnt_exist unless params[:noraise] %>
diff --git a/config/routes.rb b/config/routes.rb
index 787824f..2636c83 100644
--- a/config/routes.rb
+++ b/config/routes.rb
@@ -1,3 +1,3 @@
 Rails.application.routes.draw do
-  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
+  get "/foo", to: "foos#show"
 end
```


So, given a running server, go to `/foo`. 

Notes:
 
* if the exception is not present, the template renders correctly. (`/foo?noraise=1`)
* If you try it with a partial that is not a variant, the exception will bubble correctly.

**Comment by joallard** [comment]
I would posit that for users who use both partials and variants, this is a rather major bug. The view system is particularly obscure for me with its compilation step, can someone give some hints towards a fix for this? Maybe some documentation about how it works/guidance on where to look would be helpful.

**Comment by joallard** [comment]
Reproduced in `5-1-stable@237f00c` (5.1.4.rc1+ - as of today)

**Comment by joallard** [comment]
Reproduced in `5-1-stable@e9b77953` (5.1.4)

**Comment by joallard** [comment]
@Schwad Absolutely, thanks for the ping! Some expertise would help a lot!

**Comment by khasinski** [comment]
Looks like this was fixed at some point and works in 7.0.1, I've tested it and got:

```undefined local variable or method `method_that_doesnt_exist' for #<ActionView::Base:0x0000000000ac58>
Did you mean?  method_not_get_method?```

Instead of the missing template error.

**Comment by joallard** [comment]
Thanks for testing this @khasinski , I'll take your word for it and take one issue out from the backlog for now. It's been a long time since I've left the project that needed this; we'll re-open if there's ever the need.
