### PR TITLE
Require missing module

### LINKED ISSUE #37391: Rails 6.1 development.rb undefined method `year' for 1:Integer
### Steps to reproduce

```
git clone https://github.com/schneems/rails_61_boot_bug
cd rails_61_boot_bug
bundle install
rails c
```

There is a `1.year` in the `development.rb` file, for some reason the activesupport core extensions aren't yet applied when this file (and other config files) are attempted to be loaded. You can see the commit that introduces the bug here https://github.com/schneems/rails_61_boot_bug/commit/a3d207c53e8c944e629b158f62c4d571815d6b81

The only other modification I made was 

### Expected behavior

The app to boot into a console

### Actual behavior

An error occurs:

```
	15: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/railties/lib/rails/engine.rb:612:in `block in <class:Engine>'
	14: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/railties/lib/rails/engine.rb:612:in `each'
	13: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/railties/lib/rails/engine.rb:613:in `block (2 levels) in <class:Engine>'
	12: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/activesupport/lib/active_support/dependencies.rb:324:in `require'
	11: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/activesupport/lib/active_support/dependencies.rb:291:in `load_dependency'
	10: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/activesupport/lib/active_support/dependencies.rb:324:in `block in require'
	 9: from /Users/rschneeman/.gem/ruby/2.6.5/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
	 8: from /Users/rschneeman/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 7: from /Users/rschneeman/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 6: from /Users/rschneeman/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 5: from /Users/rschneeman/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 4: from /Users/rschneeman/.gem/ruby/2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 3: from /Users/rschneeman/Documents/projects/tmp/boot_bug/config/environments/development.rb:1:in `<main>'
	 2: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/railties/lib/rails/railtie.rb:216:in `configure'
	 1: from /Users/rschneeman/.gem/ruby/2.6.5/bundler/gems/rails-921b55d300fe/railties/lib/rails/railtie.rb:216:in `instance_eval'
/Users/rschneeman/Documents/projects/tmp/boot_bug/config/environments/development.rb:63:in `block in <main>': undefined method `year' for 1:Integer (NoMethodError)
```

### System configuration

**Rails version**: Master (SHA 921b55d300fe)

**Ruby version**: 2.6.5

### PR DESCRIPTION
**Pull request by santib**
Resolves https://github.com/rails/rails/issues/37391

I found out `12959dee0f19a8e050dd1236b031c2c690729905` to be the offending commit by using `git bisect` and making sure to `spring stop` before running `bundle exec rails c` on each commit.

I think that the commit makes sense, but it just had a side effect because the `time` file wasn't correctly required in some other place. For that reason I went with the approach of requiring the `time` file in the `dependencies` file. I'm not familiar with this code so it's possible that there is a better place where to do it.

### CODE REVIEW

**Comment by Edouard-chin** [comment]
I think that this is not a bug but it's by design. The problem will be the same if someone tries to use almost any of the Activesupport core ext methods (i.e. `String#indent`).
The only way to really fix this issue is to `require "active_support/all"` at the very beginning of the boot process. But if we do that it will make the boot process slower for application who have set the `config.active_support.bare` [flag](https://guides.rubyonrails.org/configuring.html#configuring-active-support)

If someone needs some of the active_support method before this initializer kicks in https://github.com/rails/rails/blob/0e8d85ddb54a7f08b027b2757c6678ebf74732d9/railties/lib/rails/application/bootstrap.rb#L16-L18 then he'd have to manually require it

**Comment by kaspth** [comment]
@Edouard-chin exactly! Thanks, I’ll close this

**Comment by santib** [comment]
Ok.. It sounds a bit contrary to what was discussed here https://github.com/rails/rails/issues/36844 and also against to the Rails philosophy that is making devs lives easier by requiring everything automatically. I don't think making devs require an active_support file manually makes sense but.. 🤷‍♂

**Comment by kaspth** [comment]
Adding a require for Active Support’s time in the legacy auto loader has nothing to do with either of those things and us not merging is not a violation of them either. Sorry, we’ll need a different fix for that issue.
