### ISSUE TITLE
Cannot add ActiveModel::Attribute::FromDatabase to permitted YAML safe load classes

### ISSUE THREAD

**Issue by stanhu** [rails/rails#45609]
### Steps to reproduce

We have some database entries serialized to YAML. For example:

```
---
:custom_message: Repository Download Started
:author_name: !ruby/object:DeployToken
  concise_attributes:
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: deploy_token_type
    value_before_type_cast: 1
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: id
    value_before_type_cast: 2
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: revoked
    value_before_type_cast: false
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: read_repository
    value_before_type_cast: true
```

However, since the security release announced inhttps://rubyonrails.org/2022/7/12/Rails-Versions-7-0-3-1-6-1-6-1-6-0-5-1-and-5-2-8-1-have-been-released to address CVE-2022-32224, we cannot simply add `ActiveModel::Attribute::FromDatabase` to the permitted class list:

```ruby
(byebug) YAML.safe_load(payload, permitted_classes: [ActiveModel::Attribute::FromDatabase, Symbol, DeployToken], aliases: true)
*** NameError Exception: private constant ActiveModel::Attribute::FromDatabase referenced
```

```ruby
# Your reproduction script goes here
```

### Expected behavior

YAML loading should work. Should this constant no longer be private since it's been serialized to YAML?

### Actual behavior

YAML loading fails with:

```
*** NameError Exception: private constant ActiveModel::Attribute::FromDatabase referenced
```

### System configuration

**Rails version**:
v6.1.6.1

**Ruby version**:
v2.7.5

**Comment by stanhu** [comment]
Workaround is to do this:

```ruby
ActiveModel::Attribute::const_get(:FromDatabase)
```

**Comment by julienchabanon** [comment]
Indeed, using `:serialize` in a model with an ActiveRecord type does not work anymore:

`serialize :current_user, User`

and adding **User** to `config.active_record.yaml_column_permitted_classes` in `config/application.rb` does not work. Adding `ActiveModel::Attribute::FromDatabase` or `ActiveModel::Attribute.const_get(:User)` does not work either.

Error:
`uninitialized constant ActiveModel::Attribute::User (NameError)`

**Comment by stanhu** [comment]
I had to move the setting of `yaml_column_permitted_classes` into an `after_initialize` block inside `config/application.rb`.

**Comment by julienchabanon** [comment]
@stanhu thank you!!! It fixes the issue.

Here is the working config for me in `config/application.rb`:
```
    config.after_initialize do
      # Psych Allow YAML Classes
      config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, ActiveSupport::HashWithIndifferentAccess, ActiveModel::Attribute.const_get(:FromDatabase), User, Time]
    end

**Comment by jywarren** [comment]
Thanks! This seemed to be an unexpected breaking change in Rails 5.2.8.1, I understand it's intentional, but I think there could be more notification of the breaking changes in the release notes or elsewhere. I tracked this for a while before finding this here. 

When I try to [address this with permitted classes](https://github.com/publiclab/plots2/pull/11274), the list gets longer and longer as I re-run tests and find new ones each time. 

```ruby
config.active_record.yaml_column_permitted_classes = [OAuth::AccessToken, OAuth::Consumer, Symbol, Net::HTTP, OpenSSL::SSL::SSLContext, OpenSSL::SSL::Session, URI::HTTPS, URI::RFC3986_Parser]
```

Is this really the best way to do it? Honest question, i imagine it balances the risk of allowing some but not all? The vulnerability is great enough to avoid the old default in any production apps?

Thank you very much!!

**Comment by masterkain** [comment]
I'm migrating a big table with yaml serialized columns to jsonb, the serialized columns have seen multiple rails versions so the classes inside there are quite a bit.

```
::YAML.load_tags['!ruby/object:ActiveRecord::Attribute::FromDatabase'] = ActiveModel::Attribute.const_get(:FromDatabase)
```

this resolves the issue for which `YAML.unsafe_load(record.my_serialized_column)` raises but I get anothe error:

```
/usr/local/lib/ruby/3.0.0/psych/class_loader.rb:26:in `load': undefined method `empty?' for ActiveModel::Attribute::FromDatabase:Class (NoMethodError)
```

this running on a Rails 6 codebase.

anyone knows how to solve this? I tried adding the `empty?` method to the class but I get core dumps.

**Comment by gnumarcelo** [comment]
> @stanhu thank you!!! It fixes the issue.
> 
> Here is the working config for me in `config/application.rb`:
> 
> ```
>     config.after_initialize do
>       # Psych Allow YAML Classes
>       config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, ActiveSupport::HashWithIndifferentAccess, ActiveModel::Attribute.const_get(:FromDatabase), User, Time]
>     end
> ```

After upgrading from 6.0.5.1 to 6.0.6 the fix above stopped working, removing it from `config.after_initialize` fixes it.

**Comment by stanhu** [comment]
Does 6.0.6 even have a security update? https://rubyonrails.org/2022/7/12/Rails-Versions-7-0-3-1-6-1-6-1-6-0-5-1-and-5-2-8-1-have-been-released suggests you need to go to v6.1.6.1.

**Comment by etiennebarrie** [comment]
To go back to the original question, I don't think `ActiveModel::Attribute::FromDatabase` should be made public for this, especially since `ActiveModel::Attribute` is a private API. `ActiveModel::Attribute.const_get(:FromDatabase)` is fine to work around the issue of your database having those already serialized, but you should try to clean that up.

If you have autoloadable classes to be deserialized, you can put that in the `after_initialize`, but since the configs are already copied by that point, you'll need to set it directly to `ActiveRecord` (`ActiveRecord::Base` for Rails < 7.0):
```ruby
    config.after_initialize do
      ActiveRecord.yaml_column_permitted_classes = [Symbol, Hash, Array, ActiveModel::Attribute.const_get(:FromDatabase), ActiveSupport::TimeWithZone, Time, ActiveSupport::TimeZone, User]
    end
```

I put together a sample repo at https://github.com/etiennebarrie/rails-app/tree/45609, here's the commit for Rails 7.0: https://github.com/etiennebarrie/rails-app/commit/7a0de750b3eb78c51da0d968b0f3764b2c4f51a4
