### PR TITLE
Fix NameError: undefined local variable or method `cols`

### PR DESCRIPTION
**Pull request by kamipo**
Caused by 007e50d8e5a900547471b6c4ec79d9d217682c5d.

### CODE REVIEW

**Comment by kamipo** [comment]
CI failure is depend on broken master branch.
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb#L10
https://travis-ci.org/rails/rails/jobs/171437317#L813

Fixed by this PR is merged.

**Comment by rafaelfranca** [comment]
Master is not broken anymore. @matthewd did you fix it?

**Comment by guilleiguaran** [comment]
fixed in https://github.com/rails/rails/commit/dcb364ec8ec89c4c70c8de1965a3d3d6b45de072

**Comment by kamipo** [comment]
dcb364ec8ec89c4c70c8de1965a3d3d6b45de072 is only fixed sqlite3 adapter.
Still broken mysql2 adapter with `prepared_statements: true` (`exec_stmt_and_free`).
