### PR TITLE
Update `cookies` helper on all HTTP requests

### PR DESCRIPTION
**Pull request by maclover7**
### Summary

Regression introduced by ae29142142324545a328948e059e8b8118fd7a33 / 8363b879fe759f0645179f4521cc64795efbee6e.

Previously, cookies were only updated on `GET` requests. Now we will
update the helper for all requests, as part of `process`. Added
regression tests for all available HTTP method helpers in
`ActionController::TestCase`.

### Other Information

- ref #27584 
- very similar to #27145, #27146

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Backported in cf51e7415a

**Comment by rafaelfranca** [comment]
This caused a regression https://gist.github.com/davidcornu/91f248ad66dd8df2dc41b22728f9a3fd.

@davidcornu was taking a look but I'll revert it for now.

**Comment by mrageh** [comment]
@rafaelfranca I ran the regression script above on the latest master and it still fails, so I'm not sure if this patch by @maclover7 caused the regression.

**Comment by devohh** [comment]
@rafaelfranca @maclover7 @mrageh Any news ? I still can't access to a signed cookie from my tests.

**Comment by devohh** [comment]
@rafaelfranca Hello Rafael, I just realized how useless my precedent message was. It's my first participation on Github. Sorry for my inexperience. I just updated to 5.0.2.rc1.
When I run my IntegrationTest, I get this error :
```
Error:
CartsControllerTest#test_should_get_cart:
NoMethodError: undefined method `signed' for #<Rack::Test::CookieJar:0x00555a9c6ad320>
    test/controllers/carts_controller_test.rb:18:in `block in <class:CartsControllerTest>'
```
 test/controllers/carts_controller_test.rb:18 
```
assert_not_nil cookies.signed['cart_ids']
```
At first I thought it was not the appropriate way to test the presence of a signed cookie. And then, I read [this message](https://github.com/rails/rails/issues/27145). 

**Note** : I have successfully tested the presence and/or the value of a simple cookie.
**My configuration** : ruby 2.4.0p0 && Rails 5.0.2.rc1

Hope it helps. Otherwise, could you show me the way.
