### PR TITLE
Fix test failing in Active Storage's GCS service

### PR DESCRIPTION
**Pull request by maleblond**
### Summary

Ref. https://github.com/rails/rails/pull/42509#issuecomment-864053693

This PR should fix two tests in `main` that are failing since https://github.com/rails/rails/pull/42509: https://buildkite.com/rails/rails/builds/78375#6fb6fd5c-1d74-4491-b9c8-97ee7ad52c67

```
Error:
--
ActiveStorage::Service::GCSServiceTest#test_upload_with_cache_control:
NoMethodError: undefined method `delete' for nil:NilClass
/rails/activestorage/test/service/gcs_service_test.rb:132:in `ensure in block in &lt;class:GCSServiceTest&gt;'
/rails/activestorage/test/service/gcs_service_test.rb:132:in `block in &lt;class:GCSServiceTest&gt;'
```

We were trying to use a variable that doesn't exist (`service_config` instead of `SERVICE_CONFIGURATIONS`). Those tests only run in the `main` branch, which is why this failure wasn't caught before the PR was merged

### CODE REVIEW

**Comment by pixeltrix** [comment]
@maleblond thanks for following this up 👍🏻

**Comment by pixeltrix** [comment]
Ugh, I missed the second commit - for future reference, please squash those out, thanks.
