### PR TITLE
Make `deprecate` work for non-exists methods

### LINKED ISSUE #34646: Deprecating column accessor fails in 5.2.2
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "5.2.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :content
  end
end

class Post < ActiveRecord::Base
  deprecate :content
end

class BugTest < Minitest::Test
  def test_stuff
    Post.create!
  end
end
```

### Expected behavior
Exit without error, as 5.2.1

### Actual behavior
```
Traceback (most recent call last):
	7: from ./test.rb:31:in `<main>'
	6: from ./test.rb:34:in `<class:Post>'
	5: from /Users/yskkin/projects/rails/activesupport/lib/active_support/core_ext/module/deprecation.rb:23:in `deprecate'
	4: from /Users/yskkin/projects/rails/activesupport/lib/active_support/deprecation/instance_delegator.rb:22:in `deprecate_methods'
	3: from /Users/yskkin/projects/rails/activesupport/lib/active_support/deprecation/method_wrappers.rb:57:in `deprecate_methods'
	2: from /Users/yskkin/projects/rails/activesupport/lib/active_support/deprecation/method_wrappers.rb:57:in `each'
	1: from /Users/yskkin/projects/rails/activesupport/lib/active_support/deprecation/method_wrappers.rb:67:in `block in deprecate_methods'
/Users/yskkin/projects/rails/activesupport/lib/active_support/deprecation/method_wrappers.rb:67:in `alias_method': undefined method `content' for class `Post(id: integer, content: string)' (NameError)
```

### System configuration
**Rails version**: 5.2.2

**Ruby version**: 2.5.0p0

Bisected to 015477ae9109d4105d5a5057d82338f198febb74

### PR DESCRIPTION
**Pull request by y-yagi**
Before #33325, `deprecate` works for non-exist methods.
This is necessary, for example, if want to deprecate dynamically defined
methods like attributes methods.

Fixes #34646

### CODE REVIEW

**Review by gmcgibbon — APPROVED** [review]

**Comment by rmacklin** [comment]
Hi, we just ran into the issue in https://github.com/rails/rails/issues/34646 after upgrading an app to 5.2.2

I'm glad to see that it's fixed in the upcoming 6.0 release, but just wanted to ask if 5.2.x is closed for changes, or if there will be another patch release in the 5.2.x series. If there will be another 5.2.x patch release, could it include a backport of this PR?
