### ISSUE TITLE
Caching with jbuilder errors with undefined local variable or method `view_cache_dependencies` from 7.2.2

### ISSUE THREAD

**Issue by dwightwatson** [rails/rails#53559]
### Steps to reproduce

I first noticed this issue when upgrading from Rails 7.2.1.2 to 7.2.2. 

When using jbuilder cache the following error is thrown:

```
undefined local variable or method `view_cache_dependencies' for an instance of #<Class:0x00007f5ca71da640> (ActionView::Template::Error)
```

I was able to replicate this on a fresh 7.2.2 project: https://github.com/dwightwatson/jbuilder-cache

I suspect this is the relevant PR #52825 and specific line: https://github.com/rails/rails/compare/v7.2.1.2...v7.2.2#diff-82bb7084e6af04d737b9f7bcc26d977ca94770aab78e8d29843c419331fc54aeR126

I wonder if it's an ordering issue and perhaps the helper method isn't registered because `helper_method` isn't available yet here: https://github.com/rails/rails/blob/main/actionpack/lib/abstract_controller/caching.rb#L45

```ruby
git clone https://github.com/dwightwatson/jbuilder-cache
cd jbuilder-cache
bundle
bin/rails dev:cache
bin/rails c 
Post.create(title: "title", content: "content")
bin/rails server
curl localhost:3000/posts
```

### Expected behavior

The JSON partial would be cached and/or returned, as it did in 7.2.1.2.

### Actual behavior

An error is raised from ActionView.

### System configuration
**Rails version**: 7.2.2

**Ruby version**: 3.3.4

**Comment by Earlopain** [comment]
There is a PR for `jbuilder` which is supposed to fix this https://github.com/rails/jbuilder/pull/575. That PR seems to agree with your root cause analysis.

**Comment by dwightwatson** [comment]
Oh thank you, I did look at the jbuilder issues but clearly missed that.
