### ISSUE TITLE
ActionView output_buffer issue on newly registered partial filetypes

### ISSUE THREAD

**Issue by rikkipitt** [rails/rails#45844]
### Steps to reproduce

Using the latest Rails version (HEAD), I'm getting some issues with views that have extensions that have been registered. For example, I have a markdown handler that works in Rails 6.1.6.1 but seemingly not in 7 (specifically, 7.1).

When the view/templates are rendered, what's returned is an `@output_buffer.safe_append="..."` leading to things like:

`undefined method 'gsub' for #<ActionView::OutputBuffer:0x000000011f067aa0 @raw_buffer="..."`

It also happens with mailer views rendered by https://github.com/foundation/inky-rb via files like `mailer.html.inky`

### Expected behavior

I expect HTML to be returned, I think.

### Actual behavior

An Actionview output buffer is returned, leading to errors from missing methods that probably expect a string.

### System configuration
**Rails version**: Rails 7.1.0.alpha

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

Apologies for the tricky one. Let me know if I can do anything to explain it a bit better. Perhaps I'll see if I can create a proof of concept demo repo?

Cheers

**Comment by byroot** [comment]
Hi @rikkipitt, so this is very likely due to a refactoring I did recently (https://github.com/rails/rails/pull/45614).

`@output_buffer` used to be a `String` subclass, so you could do all sort of stuff on it, it's now a much more restricted API. This may have broken some handlers, I'd be happy to work with the maintainers to get that fixed properly.

Could you share for both cases:
  - the full backtrace so that I can locate the faulty code.
  - the gem used, or github repo.

If I understand correctly your Markdown handler is private code is that right? If it's not trade secret feel free to share it in a gist and I can help you get it updated.

**Comment by rikkipitt** [comment]
Hey @byroot. Sorry for the poor issue write-up. I was on the go and didn't have full access to my laptop/code.

That said, thanks for spotting this and figuring out what might be the issue. I'll send you over a gist ASAP.

Cheers!

**Comment by byroot** [comment]
Closing since this isn't a Rails bug, still feel free to share your handler when you got the time.
