### ISSUE TITLE
ActiveRecord causes errors for rdoc 6.0

### ISSUE THREAD

**Issue by agrimm** [rails/rails#31371]
### Steps to reproduce

Approach 1: Use Ruby 2.4.2 and rdoc 6.0

1.1 Use rbenv to install Ruby 2.4.2 with `rbenv install 2.4.2`
1.2 Install rdoc 6.0 with `gem install rdoc`
1.3 Install ActiveRecord with `gem install activerecord`

Approach 2: Use Ruby 2.5.0-dev

2.1 Use rbenv to install Ruby 2.5.0-dev with `rbenv install 2.5.0-dev`
2.2 Install activerecord with `gem install activerecord`

### Expected behavior

No errors get generated.

### Actual behavior

Errors get generated.

    $ rbenv shell 2.5.0-dev 

    $ gem install rails

    [Snip irrelevant output]

    Parsing documentation for arel-8.0.0
    Installing ri documentation for arel-8.0.0
    Parsing documentation for activerecord-5.1.4

    RDoc::Parser::Ruby failure around line 1 of
    lib/rails/generators/active_record/migration/templates/create_table_migration.rb

    Before reporting this, could you check that the file you're documenting
    has proper syntax:

      /Users/agrimm/.rbenv/versions/2.5.0-dev/bin/ruby -c lib/rails/generators/active_record/migration/templates/create_table_migration.rb

    RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

    The internal error was:

        (NoMethodError) undefined method `[]' for nil:NilClass

    ERROR:  While executing gem ... (NoMethodError)
        undefined method `[]' for nil:NilClass
    $ gem install rails
    Successfully installed rails-5.1.4
    Parsing documentation for rails-5.1.4
    Installing ri documentation for rails-5.1.4
    Done installing documentation for rails after 0 seconds
    1 gem installed
    $ /Users/agrimm/.rbenv/versions/2.5.0-dev/bin/ruby -c lib/rails/generators/active_record/migration/templates/create_table_migration.rb
    Traceback (most recent call last):
    /Users/agrimm/.rbenv/versions/2.5.0-dev/bin/ruby: No such file or directory -- lib/rails/generators/active_record/migration/templates/create_table_migration.rb (LoadError)
    $ gem install activerecord --version 5.1.3
    Fetching: activesupport-5.1.3.gem (100%)
    Successfully installed activesupport-5.1.3
    Fetching: activemodel-5.1.3.gem (100%)
    Successfully installed activemodel-5.1.3
    Fetching: activerecord-5.1.3.gem (100%)
    Successfully installed activerecord-5.1.3
    Parsing documentation for activesupport-5.1.3
    Installing ri documentation for activesupport-5.1.3
    Parsing documentation for activemodel-5.1.3
    Installing ri documentation for activemodel-5.1.3
    Parsing documentation for activerecord-5.1.3

    RDoc::Parser::Ruby failure around line 1 of
    lib/rails/generators/active_record/migration/templates/create_table_migration.rb

    Before reporting this, could you check that the file you're documenting
    has proper syntax:

      /Users/agrimm/.rbenv/versions/2.5.0-dev/bin/ruby -c lib/rails/generators/active_record/migration/templates/create_table_migration.rb

    RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

    The internal error was:

        (NoMethodError) undefined method `[]' for nil:NilClass

    ERROR:  While executing gem ... (NoMethodError)
        undefined method `[]' for nil:NilClass
    $ 

    $ /Users/agrimm/.rbenv/versions/2.5.0-dev/bin/ruby -c activerecord-5.1.4/lib/rails/generators/active_record/migration/templates/create_table_migration.rb
    activerecord-5.1.4/lib/rails/generators/active_record/migration/templates/create_table_migration.rb:1: syntax error, unexpected '<'
    class <%= migration_class_name %> < ...
          ^
    activerecord-5.1.4/lib/rails/generators/active_record/migration/templates/create_table_migration.rb:1: syntax error, unexpected tCONSTANT, expecting end-of-input
    ...ord::Migration[<%= ActiveRecord::Migration.current_version %...
    ...                   ^~~~~~~~~~~~

Trying with Ruby 2.4.2 works fine with rdoc 5.0, but not rdoc 6.0

    $ rbenv shell 2.4.2
    $ gem install activerecord
    Fetching: concurrent-ruby-1.0.5.gem (100%)
    Successfully installed concurrent-ruby-1.0.5
    Fetching: i18n-0.9.1.gem (100%)
    Successfully installed i18n-0.9.1
    Fetching: thread_safe-0.3.6.gem (100%)
    Successfully installed thread_safe-0.3.6
    Fetching: tzinfo-1.2.4.gem (100%)
    Successfully installed tzinfo-1.2.4
    Fetching: activesupport-5.1.4.gem (100%)
    Successfully installed activesupport-5.1.4
    Fetching: activemodel-5.1.4.gem (100%)
    Successfully installed activemodel-5.1.4
    Fetching: arel-8.0.0.gem (100%)
    Successfully installed arel-8.0.0
    Fetching: activerecord-5.1.4.gem (100%)
    Successfully installed activerecord-5.1.4
    Parsing documentation for concurrent-ruby-1.0.5
    Installing ri documentation for concurrent-ruby-1.0.5
    Parsing documentation for i18n-0.9.1
    Installing ri documentation for i18n-0.9.1
    Parsing documentation for thread_safe-0.3.6
    Installing ri documentation for thread_safe-0.3.6
    Parsing documentation for tzinfo-1.2.4
    Installing ri documentation for tzinfo-1.2.4
    Parsing documentation for activesupport-5.1.4
    Installing ri documentation for activesupport-5.1.4
    Parsing documentation for activemodel-5.1.4
    Installing ri documentation for activemodel-5.1.4
    Parsing documentation for arel-8.0.0
    Installing ri documentation for arel-8.0.0
    Parsing documentation for activerecord-5.1.4
    Installing ri documentation for activerecord-5.1.4
    Done installing documentation for concurrent-ruby, i18n, thread_safe, tzinfo, activesupport, activemodel, arel, activerecord after 29 seconds
    8 gems installed
    $ gem install rdoc
    Fetching: rdoc-6.0.0.gem (100%)
    rdoc's executable "rdoc" conflicts with /Users/agrimm/.rbenv/versions/2.4.2/bin/rdoc
    Overwrite the executable? [yN]  y
    rdoc's executable "ri" conflicts with /Users/agrimm/.rbenv/versions/2.4.2/bin/ri
    Overwrite the executable? [yN]  y
    Successfully installed rdoc-6.0.0
    Parsing documentation for rdoc-6.0.0
    Installing ri documentation for rdoc-6.0.0
    Done installing documentation for rdoc after 11 seconds
    1 gem installed

    $ rbenv shell 2.4.2 
    $ gem install activerecord --version 5.1.3
    Fetching: activesupport-5.1.3.gem (100%)
    Successfully installed activesupport-5.1.3
    Fetching: activemodel-5.1.3.gem (100%)
    Successfully installed activemodel-5.1.3
    Fetching: activerecord-5.1.3.gem (100%)
    Successfully installed activerecord-5.1.3
    Parsing documentation for activesupport-5.1.3
    Installing ri documentation for activesupport-5.1.3
    Parsing documentation for activemodel-5.1.3
    Installing ri documentation for activemodel-5.1.3
    Parsing documentation for activerecord-5.1.3

    RDoc::Parser::Ruby failure around line 1 of
    lib/rails/generators/active_record/migration/templates/create_table_migration.rb

    Before reporting this, could you check that the file you're documenting
    has proper syntax:

      /Users/agrimm/.rbenv/versions/2.4.2/bin/ruby -c lib/rails/generators/active_record/migration/templates/create_table_migration.rb

    RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

    The internal error was:

        (NoMethodError) undefined method `[]' for nil:NilClass

    ERROR:  While executing gem ... (NoMethodError)
        undefined method `[]' for nil:NilClass
    $ gem list rdoc

    *** LOCAL GEMS ***

    rdoc (6.0.0, default: 5.0.0)
    $ 

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

**Comment by y-yagi** [comment]
It seems that it got an error trying to parse to template files.
Since it is a problem with rdoc 6.0, would you create an issue to [rdoc](https://github.com/ruby/rdoc)? 

FIY: Since we have changed the extension of templates files in 8dd76a7a6ff1bb7105beabb8f834ca54ab1e5fc2, this problem does not seem to happen in 5.2.0 beta.

**Comment by matthewd** [comment]
Yeah, this error doesn't seem surprising (it's right; that's not a valid ruby file)... but if it's new, that sounds like a matter for rdoc.

As @y-yagi noted, we've already made a change that'll prevent this in future versions. That feels a bit substantial to backport, though, so I think we'll have to rely on rdoc to address it for older versions. (Especially as this is presumably true for many years' worth of historical Rails releases.)

**Comment by y-yagi** [comment]
FYI: I created an issue to rdoc. https://github.com/ruby/rdoc/issues/571
