### ISSUE TITLE
NoMethodError with incomplete datetime data in model

### ISSUE THREAD

**Issue by Zapotek** [rails/rails#24195]
### Steps to reproduce

Unfortunately I haven't managed to reproduce it with the template, the code basically looks like:

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '5.0.0beta3'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tasks, force: true  do |t|
    t.datetime "start_at"
  end
end

class Task < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_datetime
    task = Task.new(
      "start_at(1i)" => "2016", 
      "start_at(2i)" => "", 
      "start_at(3i)" => "", 
      "start_at(4i)" => "", 
      "start_at(5i)" => ""
    )
    p task.start_at
  end
end
```
### Expected behavior

When calling `task.start_at` it should return `nil` and not raise a `NoMethodError` exception.
### Actual behavior

The above works when run by itself, but produces the following error when it's being executed as part of a Rails application:

```
NoMethodError - undefined method `in_time_zone' for 0:Fixnum:
  activerecord (5.0.0.beta3) lib/active_record/attribute_methods/time_zone_conversion.rb:42:in `set_time_zone_without_conversion'
  activerecord (5.0.0.beta3) lib/active_record/attribute_methods/time_zone_conversion.rb:15:in `cast'
  activerecord (5.0.0.beta3) lib/active_record/attribute.rb:150:in `type_cast'
  activerecord (5.0.0.beta3) lib/active_record/attribute.rb:38:in `value'
  activerecord (5.0.0.beta3) lib/active_record/attribute_set.rb:42:in `fetch_value'
  activerecord (5.0.0.beta3) lib/active_record/attribute_methods/read.rb:66:in `_read_attribute'
  activerecord (5.0.0.beta3) lib/active_record/attribute_methods/read.rb:36:in `__temp__3747162747f51647'
```

This only happens when the date parameters are incomplete, when all are provided it works as expected.
### System configuration

**Rails version**: 5.0.0beta3

**Ruby version**: `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]`

The real application is using PostgreSQL 9.4.6, maybe Rails stores a `nil` which PG converts to `0` thus resulting in the error when the attribute is being retrieved?

**Comment by Zapotek** [comment]
I should also mention that it worked fine with Rails 4.2.3.

**Comment by michaelem** [comment]
Having the same issue on.

### System Configuration ###

**Rails version**: 5.0.1

**Ruby version**: 2.3.1p112

Running on PostgreSQL 9.5.3

**Comment by khanhpham1990** [comment]
I had a problem same as you. Hope rails core team fix it as soon as possible.

**Comment by arthurnn** [comment]
should be fixed by https://github.com/rails/rails/pull/24202
