### ISSUE TITLE
ActionView::Template::Error: undefined method after recent ActiveView changes

### ISSUE THREAD

**Issue by charlesobrien** [rails/rails#47449]
### Steps to reproduce
1. web-console included in gem file
2. Start application in dev environment and trigger something that generates the Rails error page (e.g., navigating to a route that doesn't exist)
3. Hit refresh on the error page

### Expected behavior
The error page should refresh successfully (and assuming no code was changed, show the same error that was given initially.)

### Actual behavior
Upon refresh the detailed error page does not show and instead shows the "We're sorry something went wrong" error page.

It appears that this issue begin on 16 February 2022, resulting from one of the commits related to the ActionView refactor. I've retested and the expected behavior works fine w/ commit https://github.com/rails/rails/commit/a44559679aa26a54ea9867a68a78c5a4a55a3b9f and no longer works in https://github.com/rails/rails/commit/72abd6357d7909c15a460c716840159e5bb97ac7 forward.

The log shows:

`1:23:38 web.1  |   
21:23:38 web.1  | 
21:23:38 web.1  | ActionView::Template::Error: undefined method `__usr_local_rvm_gems_default_gems_web_console_______lib_web_console_templates_index_html_erb__4222570476681288892_26260' for #<ActionView::Base:0x0000000000cfd0>
21:23:38 web.1  |       from /usr/local/rvm/gems/default/bundler/gems/rails-72abd6357d79/actionview/lib/action_view/base.rb:264:in `public_send'
21:23:38 web.1  |       from /usr/local/rvm/gems/default/bundler/gems/rails-72abd6357d79/actionview/lib/action_view/base.rb:264:in `_run'`

### System configuration
**Rails version**: 7.1.0alpha (main)

**Ruby version**: 3.2.0

**Comment by skipkayhil** [comment]
Mmm, it looks like `web_console` is using `with_empty_template_cache` as well, similarly to what we changed in #47445: 

https://github.com/rails/web-console/blob/891c363b60eee7c27ea4755e43ca2b54a4fbec9f/lib/web_console/template.rb#L20

**Comment by jhawthorn** [comment]
Thanks for spotting and reporting!

I think there's two issues: one is that `with_empty_template_cache` is a private API and a pretty heavy operation: it makes a new class which acts as a new view method container, so it needs a new copy of every view. We probably should not be calling it in the way we've seen guides and webconsole do so.

That said, the new (I'd argue necessary if we want to continue supporting the API) cache for runtime `append_view_path/prepend_view_path` is clearly too aggressive (we shouldn't be sharing those view paths).

I'm going to have a think on what to do next. One possibility is scoping the new cache to each view method container (though that needs to be done in a way we don't hold permanent references), or possibly we need to investigate moving the method container to be more global.
