### ISSUE TITLE
Error in actionview cache_expiry

### ISSUE THREAD

**Issue by shanehofstetter** [rails/rails#36093]
### Steps to reproduce
1. start rails server in dev env
2. do multiple parallel requests

In my app the first request is an active-storage request, second one is not (not sure if that is relevant).

### Expected behavior
no errors to occur

### Actual behavior
```ruby
NoMethodError: undefined method `execute_if_updated' for nil:NilClass
```
**Traceback (top):**
```
/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:30:in `clear_cache_if_necessary'
```

It seems to me that `clear_cache_if_necessary` is called twice, where in the second call ```@watcher``` is not yet initialized. 

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.5.3

**Comment by composerinteralia** [comment]
Confirmed, that this happens consistently if I start a server and run `curl http://localhost:3000 & curl http://localhost:3000`

That code was introduced in https://github.com/rails/rails/pull/35629

Some logging may make it more obvious what is going on here:

``` 
   def clear_cache_if_necessary
      id = SecureRandom.hex
      watched_dirs = dirs_to_watch
      p "#{id} - @watched_dirs = #{@watched_dirs.inspect}"
      p "#{id} - 'watched_dirs != @watched_dirs' = #{watched_dirs != @watched_dirs}"
      if watched_dirs != @watched_dirs
        p "#{id} - setting @watched_dirs"
        @watched_dirs = watched_dirs
        p "#{id} - setting @watcher"
        @watcher = @watcher_class.new([], watched_dirs) do
          clear_cache
        end
        p "#{id} - @watcher set to #{@watcher.inspect}"
        p "#{id} - execute watcher #{@watcher.inspect}"
        @watcher.execute
      else
        p "#{id} - execute_if_updated with watcher = #{@watcher.inspect}"
        @watcher.execute_if_updated
      end
    end
```

Produces something like:

```
"81d0f47fdacf21f2c00d4282a9fed248 - @watched_dirs = nil"                                                                                        
"81d0f47fdacf21f2c00d4282a9fed248 - 'watched_dirs != @watched_dirs' = true"                                                                 
"81d0f47fdacf21f2c00d4282a9fed248 - setting @watched_dirs"                                                                                      
"81d0f47fdacf21f2c00d4282a9fed248 - setting @watcher"                                                                                                                               
"5b804b92e0d1fabff1e2f5b2ef1f4995 - @watched_dirs = [\"/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actionmailbox-6.0.0.rc1/app/views\", \"/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.rc1/app/views\", \"/Users/daniel/Desktop/oss/rails/testing123/app/views\"]"                                         
"5b804b92e0d1fabff1e2f5b2ef1f4995 - 'watched_dirs != @watched_dirs' = false"                                                                
"5b804b92e0d1fabff1e2f5b2ef1f4995 - execute_if_updated with @watcher = nil"
"81d0f47fdacf21f2c00d4282a9fed248 - @watcher set to #<ActiveSupport::EventedFileUpdateChecker:0x00007fc1054bc828 @ph=#<ActiveSupport::EventedFileUpdateChecker::PathHelper:0x00007fc1054bc7b0>, @files=#<Set: {}>, @dirs={#<Pathname:/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actionmailbox-6.0.0.rc1/app/views>=>[], #<Pathname:/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.rc1/app/views>=>[], #<Pathname:/Users/daniel/Desktop/oss/rails/testing123/app/views>=>[]}, @block=#<Proc:0x00007fc1054bc7d8@/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:30>, @updated=#<Concurrent::AtomicBoolean:0x00007fc1054d3938 value:false>, @lcsp=#<Pathname:/Users/daniel>, @pid=24991, @boot_mutex=#<Thread::Mutex:0x00007fc1054f2108>, @dtw=[#<Pathname:/Users/daniel/Desktop/oss/rails/testing123/app/views>], @missing=[]>"
"81d0f47fdacf21f2c00d4282a9fed248 - execute with @watcher =  #<ActiveSupport::EventedFileUpdateChecker:0x00007fc1054bc828 @ph=#<ActiveSupport::EventedFileUpdateChecker::PathHelper:0x00007fc1054bc7b0>, @files=#<Set: {}>, @dirs={#<Pathname:/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actionmailbox-6.0.0.rc1/app/views>=>[], #<Pathname:/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actiontext-6.0.0.rc1/app/views>=>[], #<Pathname:/Users/daniel/Desktop/oss/rails/testing123/app/views>=>[]}, @block=#<Proc:0x00007fc1054bc7d8@/Users/daniel/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:30>, @updated=#<Concurrent::AtomicBoolean:0x00007fc1054d3938 value:false>, @lcsp=#<Pathname:/Users/daniel>, @pid=24991, @boot_mutex=#<Thread::Mutex:0x00007fc1054f2108>, @dtw=[#<Pathname:/Users/daniel/Desktop/oss/rails/testing123/app/views>], @missing=[]>"

So `watched_dirs != @watched_dirs` returns `true` in the second request because the first request alreayd set `@watched_dirs`, but the first request hasn't yet set `@watcher`.

**Comment by Medvezo** [comment]
Can confirm, I experience the same issue with Active Job & Sidekiq. The first job always fails, then gets retried and passes through; no more errors afterwards.

**Rails version**: 6.0.0.rc1
**Ruby version**: 2.6.3

**Comment by imechemi** [comment]
I am facing the same issue. I have a Rails API and a React app invoking multiple requests from a single page. 

```log
=> Booting Puma
=> Rails 6.0.0.rc1 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.1 (ruby 2.5.3-p105), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3001
Use Ctrl-C to stop
2019-05-19 23:04:42 +0530: Rack app error handling request { GET /teams }
#<NoMethodError: undefined method `execute_if_updated' for nil:NilClass>
/Users/tenzinchemi/.rvm/gems/ruby-2.5.3@snow_lion/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:30:in `clear_cache_if_necessary'
/Users/tenzinchemi/.rvm/gems/ruby-2.5.3@snow_lion/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:11:in `before'
```

**Rails version:** 6.0.0.rc1
**Ruby version:** 2.5.3

But one thing to note is that it started happening only after a few stages of development without any changes in Gemfile and Ruby version.

**Comment by Medvezo** [comment]
@rafaelfranca , has this problem been solved?

**Comment by sirdharma** [comment]
I am experiencing the same issue.

Rails 6.0.0.rc1
Ruby 2.6.3

**Comment by composerinteralia** [comment]
This was addressed in https://github.com/rails/rails/pull/36323. It should be fixed in the next release candidate.
