### PR TITLE
Add ActionView::OutputBuffer#concat back

### LINKED ISSUE #45777: ActionView::Template::Error: undefined method `concat' for ActionView::OutputBuffer
### Steps to reproduce
First of all, I really appreciate how easy you make it to submit test cases on issues, but I couldn't figure out how to make one for this particular situation. I can tell you, though, that after a bisect, this issue is introduced by 4e8e82829182cc2c1dc07997acc210bc0656eda4.

My test case is pretty simple. I have a HAML view that makes use of a helper like this:

```
def icons
  content_tag(:span, class: "my-icons") do
    concat image_tag('path/to/image.svg')
  end
end
```

### Expected behavior
This helper should render a span with an image contained within it. Before 4e8e82829182cc2c1dc07997acc210bc0656eda4, that's what happened.

### Actual behavior
An error is raised:

```
ActionView::Template::Error: undefined method `concat' for #<ActionView::OutputBuffer:0x000055751f13e310 @raw_buffer="">
    /home/app/foo/vendor/bundle/ruby/2.7.0/gems/haml-5.2.2/lib/haml/helpers/action_view_xss_mods.rb:41:in `concat_with_haml_xss'
    /home/app/foo/app/helpers/icons_helper.rb:80:in `block in icons'
    <snip>
```

### System configuration
**Rails version**: main
**Ruby version**: 2.7.4

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/45777

The method is being used by HAML, it's easy to add it back.

### CODE REVIEW

**Comment by kyrofa** [comment]
Thank you, @casperisfine!
