### ISSUE TITLE
Get NoMethodError (undefined method `split' for nil:NilClass) when validating with uniqueness: { case_sensitive: false }

### ISSUE THREAD

**Issue by kevinsapp** [rails/rails#29172]
### Steps to reproduce

I am trying to save an EndUser model in the create action of my EndUsers controller. However, when I attempt to save (or save!) the model, the save method throws a NoMethodError (undefined method `split' for nil:NilClass) exception and save fails.

I haven't had a problem with this until I upgraded to Rails 5.0.3 and Ruby 2.4.1.

### Expected behavior
The model should be saved without error.

### Actual behavior
My controller action is straight forward, i.e.

    def create
        @end_user = EndUser.new(end_user_params)
        if @end_user.save
        ...

My EndUser model has an email attribute, and I validate this attribute with `uniqueness: { case_sensitive: false }`

I tried changing the validation to the simpler `uniqueness: true`, and after doing this, everything works fine. I only discovered this issue with the validator through trial and error. I don't see any specific info in the log or stack trace which points at this particular validator being the problem (but my knowledge of Rails internals is 0).

So, the only thing I can think of at this point is that this is either a regression in 5.0.3, or some incompatibility between Rails 5.0.x and Ruby 2.4.1.

### System configuration
**Rails version**: 5.0.3

Also, I use the pg gem and Postgres. I'm using pg 0.20.0 (in case that's useful info).

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by kevinsapp** [comment]
I just reproduced this issue with Rails 5.0.2, by the way.

**Comment by matthewd** [comment]
> I haven't had a problem with this until I upgraded to Rails 5.0.3 and Ruby 2.4.1.

> I just reproduced this issue with Rails 5.0.2, by the way.

Which version(s) was it working on / did you upgrade from?

> I don't see any specific info in the log or stack trace which points at this particular validator being the problem (but my knowledge of Rails internals is 0).

Can we see the stack trace?

**Comment by kevinsapp** [comment]
> Which version(s) was it working on / did you upgrade from?

This was working on Rails 5.0.2 and Ruby 2.4.0p0. However, it fails with Rails 5.0.2 and 5.0.3 with Ruby 2.4.1.

> Can we see the stack trace?

Following is the output at the terminal:

Started POST "/end_users" for 127.0.0.1 at 2017-05-21 11:42:56 -0700
Processing by EndUsersController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"uuXJQToikhyha8gK1yO+Y1nXlEHP1SaVMcHlQqCtfOA7lApxz0ERXsAiqoG6rbriNNA77QJ/vjnbcfVq6fz5kg==", "end_user"=>{"email"=>"sapp.kevin@gmail.com", "first_name"=>"Kevin", "last_name"=>"Sapp"}, "button"=>""}
  Tenant Load (1.2ms)  SELECT  "tenants".* FROM "tenants" WHERE "tenants"."subdomain" = $1 LIMIT $2  [["subdomain", "test"], ["LIMIT", 1]]
  Admin Load (2.2ms)  SELECT  "admins".* FROM "admins" WHERE "admins"."id" = $1 ORDER BY "admins"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (1.4ms)  BEGIN
  EndUser Exists (2.6ms)  SELECT  1 AS one FROM "end_users" WHERE LOWER("end_users"."email") = LOWER($1) LIMIT $2  [["email", "sapp.kevin@gmail.com"], ["LIMIT", 1]]
   (20.8ms)  ROLLBACK
Completed 500 Internal Server Error in 115ms (ActiveRecord: 49.3ms)


  
NoMethodError (undefined method `split' for nil:NilClass):
  
app/controllers/end_users_controller.rb:41:in `create'
app/models/tenant.rb:21:in `scope_schema'
app/controllers/concerns/tenant_scoping.rb:15:in `scope_current_tenant'
  Rendering /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (7.8ms)
  Rendering /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (5.1ms)
  Rendering /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /Users/ksapp/.rvm/gems/ruby-2.4.1@newedge_admin/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (99.9ms)

Following is the "full stack trace" as shown in the browser when running in development mode:

Application Trace | Framework Trace | Full Trace
rack-mini-profiler (0.10.4) lib/patches/db/pg.rb:111:in `get_binds'
rack-mini-profiler (0.10.4) lib/patches/db/pg.rb:95:in `async_exec'
activerecord (5.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
activesupport (5.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
activerecord (5.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
activerecord (5.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:587:in `execute_and_clear'
activerecord (5.0.3) lib/active_record/connection_adapters/postgresql/database_statements.rb:13:in `select_value'
activerecord (5.0.3) lib/active_record/relation/finder_methods.rb:335:in `exists?'
activerecord (5.0.3) lib/active_record/validations/uniqueness.rb:29:in `validate_each'
activemodel (5.0.3) lib/active_model/validator.rb:151:in `block in validate'
activemodel (5.0.3) lib/active_model/validator.rb:148:in `each'
activemodel (5.0.3) lib/active_model/validator.rb:148:in `validate'
activesupport (5.0.3) lib/active_support/callbacks.rb:405:in `public_send'
activesupport (5.0.3) lib/active_support/callbacks.rb:405:in `block in make_lambda'
activesupport (5.0.3) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
activesupport (5.0.3) lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
activesupport (5.0.3) lib/active_support/callbacks.rb:546:in `catch'
activesupport (5.0.3) lib/active_support/callbacks.rb:546:in `block in default_terminator'
activesupport (5.0.3) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.3) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.3) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
activemodel (5.0.3) lib/active_model/validations.rb:408:in `run_validations!'
activemodel (5.0.3) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
activesupport (5.0.3) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.3) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
activemodel (5.0.3) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
activemodel (5.0.3) lib/active_model/validations.rb:338:in `valid?'
activerecord (5.0.3) lib/active_record/validations.rb:65:in `valid?'
activerecord (5.0.3) lib/active_record/validations.rb:82:in `perform_validations'
activerecord (5.0.3) lib/active_record/validations.rb:44:in `save'
activerecord (5.0.3) lib/active_record/attribute_methods/dirty.rb:22:in `save'
activerecord (5.0.3) lib/active_record/transactions.rb:319:in `block (2 levels) in save'
activerecord (5.0.3) lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
activerecord (5.0.3) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.3) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.3) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
activerecord (5.0.3) lib/active_record/transactions.rb:319:in `block in save'
activerecord (5.0.3) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
activerecord (5.0.3) lib/active_record/transactions.rb:318:in `save'
activerecord (5.0.3) lib/active_record/suppressor.rb:41:in `save'
bullet (5.5.1) lib/bullet/active_record5.rb:5:in `save'
app/controllers/end_users_controller.rb:41:in `create'
actionpack (5.0.3) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.3) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.3) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.3) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.3) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
app/models/tenant.rb:21:in `scope_schema'
app/controllers/concerns/tenant_scoping.rb:15:in `scope_current_tenant'
activesupport (5.0.3) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.3) lib/active_support/callbacks.rb:285:in `block in halting'
activesupport (5.0.3) lib/active_support/callbacks.rb:447:in `block in around'
activesupport (5.0.3) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.3) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.3) lib/action_view/rendering.rb:30:in `process'
rack-mini-profiler (0.10.4) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
actionpack (5.0.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.3) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:725:in `call'
bullet (5.5.1) lib/bullet/rack.rb:12:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.3) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-mini-profiler (0.10.4) lib/mini_profiler/profiler.rb:282:in `call'
railties (5.0.3) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"uuXJQToikhyha8gK1yO+Y1nXlEHP1SaVMcHlQqCtfOA7lApxz0ERXsAiqoG6rbriNNA77QJ/vjnbcfVq6fz5kg==",
 "end_user"=>{"email"=>"sapp.kevin@gmail.com", "first_name"=>"Kevin", "last_name"=>"Sapp"},
 "button"=>""}
Toggle session dump
Toggle env dump
Response

Headers:

None
x
>>

**Comment by divyashravanthi** [comment]
+1

**Comment by rono23** [comment]
This is not Rails problem, the error is caused by [rack-mini-profiler](https://github.com/MiniProfiler/rack-mini-profiler/pull/294#issuecomment-303099125). You can upgrade it, then it will work.

**Comment by kevinsapp** [comment]
Thanks, @rono23. That seems to have been the problem. I upgraded rack-mini-profiler from 0.10.4 to 0.10.5 (latest as of now), and the problem went away.
