### PR TITLE
Fix time travel helpers to work when nested using with separate classes

### LINKED ISSUE #49706: `travel_to` overwrites existing stubs if called from different classes
With Rails 7.1 we started getting some rather strange errors when running all tests in CI. Seemingly randomly, tests would suddenly all fail with `NoMethodError: undefined method 'original_method' for nil:NilClass` stemming from various different spots, often not even from our code (for example, the backtrace sometimes indicated a fixture YML when not passing `--backtrace` to `rails test`).

It turns out we have some tests in our codebase that have additional classes that include `ActiveSupport::Testing::TimeHelpers` and call `travel_to` and since the list of currently stubbed methods is stored as an instance variable, we were accidentally causing stubs to be overwritten in certain situations. Once that happened, everything stopped working. I think this wasn't an issue before Rails 7.1 since `Time.new` wasn't stubbed (that was introduced by #47315) so the problem wasn't as obvious. Now that it's being stubbed, if the stub gets overwritten, it ends up trying to call the original `Time.new` that no longer exists after unstubbing, and we get either the error above or one of the two other errors that can be reproduced with the example below.

The way we're using `TimeHelpers` and `travel_to` may not be recommended/supported, so I'm not sure this should be considered a bug. Some of our tests relied on the previous behaviour and I'm not sure we'd be able to refactor all of them to use these "properly" so hopefully we can find a solution. If it isn't a bug though, it'd be nice to have some more obvious error/message show up. For example, raise or warn if a method with the same name as the original method that's about to be stubbed (the one prefixed with `__simple_stubs__`) exists already.

I'm happy to discuss and provide further information if necessary!

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/testing/time_helpers"
require "minitest/autorun"

class MyOtherClass
  include ActiveSupport::Testing::TimeHelpers

  def travel_no_block
    travel_to(Time.parse("2023-10-19 05:00:00"))
    # do something
  end

  def travel_in_block
    travel_to(Time.parse("2023-10-19 05:00:00")) do
      # do something
    end
  end
end

class BugTest < Minitest::Test
  include ActiveSupport::Testing::TimeHelpers

  def setup
    @my_other_class = MyOtherClass.new
  end

  # NoMethodError: undefined method `original_method' for nil:NilClass
  def test_no_block_in_other_class
    travel_to(Time.parse("2023-10-19 00:00:00")) do
      @my_other_class.travel_no_block
    end
    assert_equal Time.parse("2023-10-19"), Time.new(2023, 10, 19)
  end

  # SystemStackError: stack level too deep
  def test_no_block_in_other_class_with_time_new_in_block
    travel_to(Time.parse("2023-10-19 00:00:00")) do
      @my_other_class.travel_no_block
      assert_equal Time.parse("2023-10-19"), Time.new(2023, 10, 19)
    end
  end

  # NameError: undefined method `__simple_stub__now' for class `#<Class:Time>'
  def test_block_in_other_class
    travel_to(Time.parse("2023-10-19 00:00:00")) do
      @my_other_class.travel_in_block
    end
    assert_equal Time.parse("2023-10-19"), Time.new(2023, 10, 19)
  end
end

```

### Expected behavior
No errors as in Rails pre 7.1.

### Actual behavior
Various errors (see comment above each test case).

### System configuration
**Rails version**: 7.1.1 & latest `main` as of writing (9f6b721b1d482ab16d7bdce758fea448bd7ffdbb)

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #49706.

When using nested `travel_to` with separate classes (see the issue description for the details), we stub original methods with new ones https://github.com/rails/rails/blob/df507240dfc83f120a60b8e2e967d5d96663f67b/activesupport/lib/active_support/testing/time_helpers.rb#L28-L33 and restore in https://github.com/rails/rails/blob/df507240dfc83f120a60b8e2e967d5d96663f67b/activesupport/lib/active_support/testing/time_helpers.rb#L59-L64

For a call as
```ruby
travel_to(...) do # outer
  travel_to(...) do # inner
    # ...
  end
end
```

when "inner" restores original methods, it removes the stub method (`"__simple_stub__#{method_name}"` in this case) and defines original name with the original implementation. Then when "outer" tries to restore the stub method, it is not defined in the object because of the previously mentioned case. So we need somehow differentiate these stub methods. I added `object_id` to them to make them unique.

### CODE REVIEW

**Comment by nicoco007** [comment]
Thanks for the quick fix!
