### PR TITLE
activerecord: fix sql log with unnamed binds

### LINKED ISSUE #44968: SQL logging breaks with unnamed query binds
The active record log subscriber raises, when dealing with a query with unnamed binds. The issue was introduced with https://github.com/rails/rails/commit/17c7607167a9294edc64cec43ef32778eb2bd677 A solution could be to disable parameter filtering for unnamed binds.

### Steps to reproduce

```ruby
::ActiveRecord.connection.exec_query("select * from users where username = $1", "SQL", ["user1"])
```

### Expected behavior

Expected is a log like

```
DEBUG -- :   SQL (0.1ms)  select * from users where username = $1  ["user1"]
```

### Actual behavior

It actually produces the following log

```
ERROR -- : Could not log "sql.active_record" event. NoMethodError: undefined method `name' for "u":String ["/var/lib/gems/2.7.0/gems/activerecord-7.0.2.4/lib/active_record/log_subscriber.rb:54:in `block in sql'"
```

### System configuration
**Rails version**: 7.0.2.4

**Ruby version**: 2.7.1

### PR DESCRIPTION
**Pull request by ushi-as**
### Summary

Fixes https://github.com/rails/rails/issues/44968

### CODE REVIEW

**Comment by DmitryBochkarev** [comment]
@tenderlove Aaron, can this fix be released as a patch for stable branch 7?

**Comment by ushi-as** [comment]
> @tenderlove Aaron, can this fix be released as a patch for stable branch 7?

Done already. See https://github.com/rails/rails/pull/44995

**Comment by DmitryBochkarev** [comment]
Thank you, Martin!
