### PR TITLE
Fix `OID::Bit#cast_value`

### LINKED ISSUE #26137: PostgreSQL OID Bit column type issue on Rails 5
On upgrade to Rails 5, I have issue with Postgres `bit` column type and overwriting reader method
You can see the issue: https://gist.github.com/morgoth/1d3725b3e73b91e164d5e20a81221e8f

It was working fine on Rails 4.2, now it raises:
```
NoMethodError: undefined method `[]' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Bit::Data:0x00557ede32d2c0>
```
### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.3.1

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #26137.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Backported in dfcfa8a
