### ISSUE TITLE
Layout can no longer access local variables

### ISSUE THREAD

**Issue by terencedignon** [rails/rails#31680]
### Steps to reproduce
After upgrading from Rails 5.0.6 to Rails 5.1.4 I am no longer able to render locals to a layout.  Rendering to a template still works.

*controllers/users_controller.rb*
```
class UsersController < ApplicationController
  layout 'application'

  def index
    render locals: { user_name: 'John' }
  end
end
```

*views/layouts/application.html.erb*
```
...
<%= user_name %>
...
```

*views/users/index.html.erb*
```
...
<%= user_name %>
...
```

### Expected behavior
Expected behavior is user_name appears in both the layout and the index template.

### Actual behavior
```
ActionView::Template::Error: undefined local variable or method 'user_name'
```
is raised by layout.

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.4.2

**Comment by composerinteralia** [comment]
@terencedignon I can confirm that this doesn't work in 5.1.4, but I got the same error when I tried it in 5.0.6.

**Comment by terencedignon** [comment]
@composerinteralia Thanks for the clarifying question.

You have to set the layout when passing locals to _application.html.erb_.  I'll edit above and add a comment.

```
class UsersController < ApplicationController
  layout 'application'

  def index
    render locals: { user_name: 'John' }
  end
end
```

A practical example would be _layout 'users'`_ referencing a file _views/layouts/users.html.erb_

**Comment by composerinteralia** [comment]
Best if you can reproduce using this template: https://github.com/rails/rails/blob/master/guides/bug_report_templates/action_controller_gem.rb

**Comment by obromios** [comment]
I am having the same problem, see my stackoverflow [question](https://stackoverflow.com/questions/48619205/locals-not-working-for-controller-rendering-in-rails-5-1).  It worked in rails 5.0.6 but not rails 5.1.4.

**Comment by obromios** [comment]
I have experienced the same problem, see this SO question

**Comment by composerinteralia** [comment]
I was able to recreate this as well. I can look into it. In the meantime I think you can use `local_assigns[:user_name]` as a workaround.

**Comment by composerinteralia** [comment]
Looks like that was introduced in https://github.com/rails/rails/commit/d6bac046922fcee05366d26d75349dde70d25f6b.

**Comment by obromios** [comment]
Your workaround works, thank you.

**Comment by terencedignon** [comment]
Thanks @composerinteralia, local_assigns works great.  Appreciate you finding the relevant merge as well.

**Comment by tomstuart** [comment]
So that I can understand what to do in my application: is this legitimately an unintentional bug that is likely to be fixed in future, or is this the new official behaviour of rendering layouts?

**Comment by efremroberson** [comment]
+1 for a permanent fix for this. I can also confirm this is an issue in 5.1.4 + 5.1.6

To add...

With a partial:
`_example.html.erb`
```
...
<%= link_to('This is a link', link) unless link.empty? %>
...
```

This doesn't work:
`show.html.erb`
```
...
<%= render partial: 'example', locals: { example: example, link: example['link'].to_s } %>
...
```

But this works:
```
...
<%= render partial: 'example', example: example, link: example['link'].to_s %>
...
```

Using `local_assigns` works as well, but it feels like a step backwards if that's the new norm.

**Comment by composerinteralia** [comment]
Based on d6bac04 I believe this is the intended behavior. It is probably worth adding to the documentation.

**Comment by tomstuart** [comment]
@composerinteralia I don’t follow — d6bac046922fcee05366d26d75349dde70d25f6b looks like a performance optimisation for looking up the layout, with no suggestion that it should affect the behaviour. Perhaps @tenderlove can confirm or deny that the behaviour change is intentional?

**Comment by weedySeaDragon** [comment]
Getting this in 5.2.1
What's the status?

**Comment by krim** [comment]
Any news? It still doesn't work on Rails 5.1.6.1

**Comment by kyleboe** [comment]
Bump. Confirmed not working on Rails 5.1.6.1 as well.

**Comment by MSCAU** [comment]
I have just come across this in Rails 5.2.1:

This works:

`render :save_error, status: :bad_request, locals: {message: "ERROR SAVING"}`

This doesn't:

`render :save_error, status: :bad_request, message: "ERROR SAVING"`

It gives me a NameError:

> undefined local variable or method `message'

I assume it may be related?

**Comment by cmcguff** [comment]
Confirm this is issue in Rails 5.2.2 as well, specifically when attempting to render outside of a controller, for example generating PDF reports from a background job.

```
ApplicationController.render(template: '/formats/report_template.html.erb', 
  layout: '/layouts/report.html.erb',
  locals: { report_name: 'test'}
)

```
Where report_name local is used in the layout, will fail with ActionView::Template::Error: undefined local variable or method `report_name'

**Comment by jpwynn** [comment]
Just to highlights something important @cmcguff said, which I missed the first time around until I finally saw it in my own rspec specs, if a local named :foo is used in the __layout file__ the ActionView::Template::Error occurs; but if you use __local_assigns[:foo]__ in the layout, that works. 

So local_assigns is _not_ required in the template file, but is required for variables used in the layout file.

**Comment by webzorg** [comment]
> Just to highlight something very important @cmcguff said, which I missed the first time around until I finally saw it in my own rspec specs, if a local named :foo is used in the **layout file** the ActionView::Template::Error occurs; but if you use **local_assigns[:foo]** in the layout, that works.
> 
> So local_assigns is _not_ required in the template file, but is required for variables used in the layout file.

legend

**Comment by varchar** [comment]
Just commenting that this is still an issue on rails 7.0

**Comment by stuffa** [comment]
Also in Rails 7.1
I just ran in to the layout variable issue yesterday
traditionally I have been using @instance_variables (they work Ok)
but I have been moving to use the <%# locals () %> to define variables in all my templates and as a result i am moving away from @instance_variables.  And WHAM ....  local variables not defined in layouts

**Comment by stuffa** [comment]
Also in rails 7.2
just updating rails 7.1 to 7.2
locals still not passed through to the layout - forced to still use instance variables for layouts

I am now using locals on all views and partial along with the <%# locals: () %> magic - helped clean up a lot of unused instance variables

**Comment by flavorjones** [comment]
I've proposed a fix at https://github.com/rails/rails/pull/54020
