### ISSUE TITLE
ActiveRecord 4.2 serialize does not create initial coder instance

### ISSUE THREAD

**Issue by jarmo** [rails/rails#18926]
In Rails 4.1, this code works as expected:
```ruby
class Foo < ActiveRecord::Base
  serialize :bar, Hash

  after_initialize -> { self.bar.merge(baz: "something") }
end

Foo.new
```

In Rails 4.2 this code fails, because `self.bar` is `nil`.

In other words - Rails 4.2 does not set initial value for serialized columns anymore. This change is not documented anywhere.

Change related with this issue seems to be this one from the changelog:
```
Remove deprecated serialized_attributes.

Rafael Mendonça França
```

**Comment by rafaelfranca** [comment]
You are looking the CHANGELOG of the master branch.

I'm sure this is by design. The default value of the column is nil, if you want it to be an empty hash I think you have to define it as the default value.

cc @sgrif

**Comment by jarmo** [comment]
No, this is not expected behavior, because it did work differently before. Also the [documentation](http://api.rubyonrails.org/classes/ActiveRecord/Base.html) in paragraph `Saving arrays, hashes, and other non-mappable objects in text columns` says the following:
`When you specify a class option, the default value for that attribute will be a new instance of that class.`

Also, the examples there reflect that statement.

**Comment by rafaelfranca** [comment]
Right, there is a test asserting this https://github.com/rails/rails/blob/cc08de856acab3f480eb76b3e80cf2ea7705c9b6/activerecord/test/cases/serialized_attribute_test.rb#L160-164.

So we will need a reproduction script with this template https://github.com/rails/rails/blob/4-2-stable/guides/bug_report_templates/active_record_gem.rb?

**Comment by sgrif** [comment]
Please check this on 4-2-stable as well

**Comment by prathamesh-sonpatki** [comment]
I tried to reproduce this but the test passes for me. Please check https://gist.github.com/prathamesh-sonpatki/33219a4f5af62c906b16

**Comment by jarmo** [comment]
I managed to reproduce it https://gist.github.com/jarmo/0c5ff28b32a9bfd8a9af

The problem is in line 22, where i'm using `attr_accessor`. I'm not sure why it's added there in the firts place, but it does not cause any problems in rails < 4.2.

As soon as i remove that line, then everything starts working again. So it seems that there is some conflict between `attr_accessor` and `serialize`, which did not exist before.

**Comment by jarmo** [comment]
I found out that i'm actually using `protected_attributes` gem and `attr_accessible` not `attr_accessor` so that initial finding is not the cause. Also, when using `rails console` then this problem does not exist, which means that probably some gem in test is to be blame, since there that problem exists. I'm trying to poinpoint the gem.

**Comment by jarmo** [comment]
I've finally managed to reproduce that problem accidentally.

The problem is related with constant auto-loading. The code below fails with `ActiveRecord 4.2.1`, but works with `4.1.x`. By debugging `#serialize` method, i can see that a lot has changed in between.

Here's how to reproduce this problem.
```
$ rails -v
Rails 4.2.1

$ rails new -TJ serialize-test
      create  
      create  README.rdoc
      create  Rakefile
      ...
```

```ruby
# app/models/foo.rb

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos do |t|
    t.string :values
  end

  create_table :bars do |t|
  end
end

class Foo < ActiveRecord::Base
  require "bar"

  serialize :values, Hash

  after_initialize -> { self.values.merge(a: 1) }
end
```

```ruby
# app/models/bar.rb

class Bar < Foo
end
```

```ruby
$ rails console
Foo.new
=> #<Foo id: nil, values: {}>
Bar.new
=> NoMethodError: undefined method `merge' for nil:NilClass
```

The problem is in line `require "bar"`, which loads `Bar` before `Foo` has been loaded. With `ActiveRecord 4.1.x` this didn't cause any problems.

I've solved this problem by loading dynamic constants after `Foo` has been loaded. Since it all seems to be really an edge-case then maybe this bug can be closed altogether?

Although, it seems strange that things do not work as expected and `#serialize` depends on loading order.

**Comment by rafaelfranca** [comment]
Closing since it is related on how the constants are loaded. It is not only about `serializer` but you will have problem with associations too as you can see in the linked issue.
