### ISSUE TITLE
Can't access fixture for models named Options (redux)

### ISSUE THREAD

**Issue by silent-e** [rails/rails#52739]
Accessing a fixture on an `Option` model breaks with the errors down below.  Using the steps to reproduce you start with

```
class OptionsControllerTest < ActionDispatch::IntegrationTest
  setup do
    @option = options(:one)
  end
  …
```

You have to do the following to get it to work.

`@option = Option.find(ActiveRecord::FixtureSet.identify(:one))`

This is almost identical to Issue https://github.com/rails/rails/issues/10638 but with a new culprit.  Works in Rails 7.0 but 7.1 is broken.  Working on upgrading one of my apps.

It appears that [this change](https://github.com/rails/rails/commit/5726b1d1d7665c33830ad114f45258ecf772b7b6#diff-7c57a19207aafe25adcf81324c922c9bda0205db771c91f5365de6eb10197b53L235) introduced this error.  It changed the `path` parameter which is the symbol here from a passive item into the active item having methods called on it.

### Steps to reproduce

```ruby
rails _7.1.4_ new options
cd options
rails generate scaffold Option
rails db:migrate
rails test
```

### Expected behavior
The tests should not throw errors

### Actual behavior
The tests throw the following errors.  This is just a sample

```
❯ rails test
Running 7 tests in a single process (parallelization threshold is 50)
Run options: --seed 13738

# Running:

E

Error:
OptionsControllerTest#test_should_show_option:
NoMethodError: undefined method `include?' for an instance of Symbol
    test/controllers/options_controller_test.rb:5:in `block in <class:OptionsControllerTest>'


bin/rails test test/controllers/options_controller_test.rb:26

======= excluding five identical test results for other scaffold tests =======

E

Error:
OptionsControllerTest#test_should_get_new:
NoMethodError: undefined method `include?' for an instance of Symbol
    test/controllers/options_controller_test.rb:5:in `block in <class:OptionsControllerTest>'

bin/rails test test/controllers/options_controller_test.rb:13

Finished in 0.075560s, 92.6416 runs/s, 0.0000 assertions/s.
7 runs, 0 assertions, 0 failures, 7 errors, 0 skips
```

### System configuration
**Rails version**:
7.1.4

**Ruby version**:
3.2.5 and 3.3.4

**Comment by fatkodima** [comment]
Behaviour change was introduced in https://github.com/rails/rails/pull/44528 (cc @byroot).

Imo, using fixtures named `options` is bad by itself, because it makes impossible to use `options` http method in tests. And name `options` is too generic and it can clash with some rails internals (or other gems internals etc) in the future.

**Comment by byroot** [comment]
Yes, what @fatkodima said is correct, it's a precedence issue. Previously the generated accessors would override the existing `options` method, now it doesn't.

You can very easily restore the old behavior with an helper like:

```
def options(*args)
  access_fixture(:options, *args)
end
```

It's unfortunate that it break in some corner cases like this one, but also fixes a ton more issues, so It's for the better.

**Comment by silent-e** [comment]
Thanks for the clarification and the helper.  For future readers, the first param to `access_fixture` should be a string.  Passing as a symbol gave me this error

```ruby
Error:
Admin::OptionsController#test_0003_get edit should redirect to the login page:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/medens/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4/lib/active_record/test_fixtures.rb:302:in `block in access_fixture'
    /Users/medens/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4/lib/active_record/test_fixtures.rb:298:in `map'
    /Users/medens/.rbenv/versions/3.2.5/lib/ruby/gems/3.2.0/gems/activerecord-7.1.4/lib/active_record/test_fixtures.rb:298:in `access_fixture'
    test/support/option_fixtures.rb:4:in `options'
```

calling it as `access_helper('options', *args)` worked.  The `@loaded_fixtures` instance variable is a plain ol' hash with strings keys and not a `HashWithIndifferentAccess`.  FYI
