### PR TITLE
Use error_highlight gem to locate the columns where an error was raised

### PR DESCRIPTION
**Pull request by mame**
### Summary

This PR uses error_highlight (available since Ruby 3.1) to display the fine-grained location where an error occurred, not only a line number but also a column range of the code fragment in question.

Here is an example of `gsub` misspelled as `gsuub`:

image

This would be more useful for a method chain in one line. When `undefined method '[]' for nil:NilClass` occurs in a chain of `[]`s, you can immediately see which `[]` caused the error. This is an example of `:articles` misspelled as `:article`:

image

### Other Information

This PR has two steps:

* Prefer `Exception#backtrace_locations` to `Exception#backtrace` (because error_highlight requires the former to identify the column information).
* Use `ErrorHighlight.spot` to identify the column where the error occurred.

For more information on error_highlight, see https://bugs.ruby-lang.org/issues/17930 .

### CODE REVIEW

**Comment by mame** [comment]
I think I fixed the CI test failures caused by my change. I believe that the failures in the latest build are not due to my change.

I would be happy to hear your opinions! If you have any questions about the implementation, feel free to ask me.

File: Gemfile [hunk 1]
```diff
@@ -180,3 +180,10 @@ end
 
 gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
 gem "wdm", ">= 0.1.0", platforms: [:mingw, :mswin, :x64_mingw, :mswin64]
+
+# The error_highlight gem only works on CRuby 3.1 or later.
+# Also, Rails depends on a new API available since error_highlight 0.4.0.
+# (Note that Ruby 3.1 bundles error_highlight 0.3.0.)
+if RUBY_VERSION >= "3.1"
+  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
+end
```
Comment (st0012) [inline Gemfile:189]: I think you also need to put something like this into the [`Gemfile` template](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/Gemfile.tt), so the new apps will have it installed.

Comment (mame) [reply Gemfile:189]: Thank you! I have added it to Gemfile.tt.

File: railties/lib/rails/generators/rails/app/templates/Gemfile.tt [hunk 2]
```diff
@@ -56,6 +56,10 @@ group :development do
 <%- end -%>
   # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
   # gem "spring"
+
+<%- if RUBY_VERSION >= "3.1" -%>
+  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
```
Comment (byroot) [inline railties/lib/rails/generators/rails/app/templates/Gemfile.tt:61]: Ruby 3.1 ships with `error_highlight` `0.3` right?

Do you need `0.4.0` specifically, or could we just try to load the one shipped with Ruby?

**Review by byroot — APPROVED** [review]
That's awesome, just a small question.

File: railties/lib/rails/generators/rails/app/templates/Gemfile.tt (hunk 2 above)
Comment (jhawthorn) [reply railties/lib/rails/generators/rails/app/templates/Gemfile.tt:61]: I'm guessing we need 0.4.0 for the `backtrace_location` keyword added in https://github.com/ruby/error_highlight/commit/2735e4681ac0890dcc28857a5f74d954bcc9e316

I think that means we should probably guard for that keyword (or alternatively for the `error_highlight` version) above so that uses who happen to have `backtrace_location `0.3.0` don't have issues.

File: actionpack/lib/action_dispatch/middleware/exception_wrapper.rb [hunk 3]
```diff
@@ -168,19 +173,55 @@ def clean_backtrace(*args)
         end
       end
 
+      def extract_source(trace)
+        if defined?(ErrorHighlight)
+          spot = ErrorHighlight.spot(@exception, backtrace_location: trace)
```
Comment (jhawthorn) [inline actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: What happens on versions which don't support the `backtrace_location` keyword?

File: railties/lib/rails/generators/rails/app/templates/Gemfile.tt (hunk 2 above)
Comment (mame) [reply railties/lib/rails/generators/rails/app/templates/Gemfile.tt:61]: @jhawthorn is right. Ruby 3.1 ships error_highlight 0.3.0, which does not have an API for external (I regret not having it), so unfortunately it only works with error_highlight 0.4.0 or later.

File: actionpack/lib/action_dispatch/middleware/exception_wrapper.rb (hunk 3 above)
Comment (mame) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: Thank you @byroot and @jhawthorn for your comments!

Because error_highlight 0.3.0 provides `ErrorHighlight.spot` but it does not support `backtrace_location` keyword, it will raise an ArgumentError: `unknown keyword: :backtrace_location`.

I hope that it should not happen because Gemfile has a requirement `gem "error_highlight", ">= 0.4.0"`, but I'm a little worried. Unfortunately we can't use `defined?` or `respond_to?` or something to determine if the new keyword is supported.

Should I prepare another API method, say, `ErrorHighlight.spot_for_backtrace_location` or something? Then we can check it by `defined?(ErrorHighlight.spot_for_backtrace_location)`. If you prefer this approach, I will gladly do so. (I wonder what the name of the method should be.)

Comment (jhawthorn) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: Thanks, that makes sense. Unfortunately we don't have the ability to control what versions users have for optional requirements, we have the Rails Gemfile, but that's really just what we use for our tests, and we have the template Gemfile, but that's only used for newly generated apps. So we do need something additional to check for this feature.

How would you feel changing the test above to

``` ruby
defined?(ErrorHighlight) && Gem::Version.new(ErrorHighlight::VERSION) >= Gem::Version.new("0.4.0")
```

Comment (mame) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb]: > Unfortunately we don't have the ability to control what versions users have for optional requirements

Ah, I see! I understand very well, thank you for your explanation.

> How would you feel changing the condition to

I'm fine if you are okay for this. Sorry for messing up a bit the Rails code!

Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb]: Actually, I think the preferable pattern would be:

```ruby
begin
  gem "error_highlight", ">= 0.4.0"
rescue LoadError
end
```
At the top of the file.

Comment (mame) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb]: @byroot Thank you! I have added the idiom at the top of `actionpack/lib/action_dispatch/middleware/exception_wrapper.rb`

File: actionpack/lib/action_dispatch/middleware/exception_wrapper.rb [hunk 4]
```diff
@@ -1,5 +1,11 @@
 # frozen_string_literal: true
 
+begin
+  # Activate error_highlight 0.4.0 or later if possible
+  gem "error_highlight", ">= 0.4.0"
+rescue LoadError
+end
```
Comment (byroot) [inline actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:7]: Sorry I wasn't clear. We should record in a variable or something whether or not we managed to load the right version. So that we can later use that in conditionals.

Also I think `gem` doesn't load, so the full pattern may need to be:

```ruby
has_error_highlight = begin
  gem ...
  require ...
  true
rescue LoadError
  false
end

Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:7]: Also note to myself, ExceptionWrapper is supposed to only be loaded in test, but several production code paths reference it, I should refactor that.

Comment (mame) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:7]: Oh sorry, the approach doesn't work. The interpreter requires `error_highlight` at the startup, so error_highlight 0.3.0 is activated if Gemfile has no explicit denendency.

```
$ cat Gemfile
source "https://rubygems.org"

$ cat foo.rb
p ErrorHighlight::VERSION

$ bundle install

$ bundle exec ruby foo.rb
"0.3.0"
```

The idiom `gem "error_highlight", ">= 0.4.0"` does not work as error_highlight 0.3.0 is already activated.

```
$ cat foo.rb
gem "error_highlight", ">= 0.4.0"
p ErrorHighlight::VERSION

$ bundle exec ruby foo.rb
/.../rubygems_integration.rb:280:in `block (2 levels) in replace_gem': can't activate error_highlight (>= 0.4.0), already activated error_highlight-0.3.0. Make sure all dependencies are added to Gemfile. (Gem::LoadError)
        from foo.rb:1:in `<main>'
```

I guess there is no other way than to put `gem "error_highlight", ">= 0.4.0"` in Gemfile (or use Ruby 3.2 which will bundle error_highlight 0.4.0 or later). Then the interpreter activates 0.4.0 at the startup time, so everything works well.


```
$ cat Gemfile
source "https://rubygems.org"
gem "error_highlight", ">= 0.4.0"

$ cat foo.rb
p ErrorHighlight::VERSION

$ bundle install

$ bundle exec ruby foo.rb
"0.4.0"
```

Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:7]: Ah that's unfortunate :/

Well, then just checking version should be fine then.

File: railties/lib/rails/generators/rails/app/templates/Gemfile.tt [hunk 5]
```diff
@@ -56,6 +56,10 @@ group :development do
 <%- end -%>
   # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
   # gem "spring"
+
+<%- if RUBY_VERSION >= "3.1" -%>
```
Comment (byroot) [inline railties/lib/rails/generators/rails/app/templates/Gemfile.tt:60]: One minor thing: this template is mostly executed when creating a new app. So people upgrading either Rails or Ruby likely won't have this.

It would be nice if the error page would tell you you can add `error_highlight, 0.4` in your Gemfile if you are on Ruby >= 3.1 and the right error_highlight isn't loaded yet.

File: actionpack/lib/action_dispatch/middleware/exception_wrapper.rb (hunk 4 above)
Comment (mame) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:7]: I'll delete the idiom at the top of the file for now. But thanks for your suggestion!

File: railties/lib/rails/generators/rails/app/templates/Gemfile.tt (hunk 5 above)
Comment (mame) [reply railties/lib/rails/generators/rails/app/templates/Gemfile.tt:60]: Sounds good. I have implemented it. What do you think?

image

Do you want to include this change in this PR? I'm not too sure about the CSS or wording. Should I create another PR?

Here is a patch:

```diff
diff --git a/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb b/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
index 9f168357ed..0ab2967fe4 100644
--- a/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
+++ b/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
@@ -28,6 +28,9 @@
           </tr>
         </table>
       </div>
+      <%- if defined?(ErrorHighlight) && Gem::Version.new(ErrorHighlight::VERSION) < Gem::Version.new("0.4.0") -%>
+        <p class="error_highlight_tip">Tip: You may want to add <code>gem 'error_highlight', '&gt;= 0.4.0'</code> into your Gemfile, which will display the fine-grained error location.</p>
+      <%- end -%>
     </div>
   <% end %>
 <% end %>
diff --git a/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb b/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb
index 4230b43742..0a8face483 100644
--- a/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb
+++ b/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb
@@ -154,6 +154,12 @@
       text-decoration: #F00 wavy underline;
     }

+    .error_highlight_tip {
+      color: #666;
+      padding: 2px 2px;
+      font-size: 10px;
+    }
+
     .button_to {
       display: inline-block;
       margin-top: 0.75em;
```

Comment (byroot) [reply railties/lib/rails/generators/rails/app/templates/Gemfile.tt:60]: Looks great to me. No need for a second PR.

**Comment by byroot** [comment]
BTW: policy is to squash commits before merge. Since IMO this PR is either ready or almost ready, I think you can do it now.

File: actionpack/lib/action_dispatch/middleware/exception_wrapper.rb [hunk 6]
```diff
@@ -168,19 +173,56 @@ def clean_backtrace(*args)
         end
       end
 
+      def extract_source(trace)
+        # ErrorHighlight.spot with backtrace_location keyword is available since error_highlight 0.4.0
+        if defined?(ErrorHighlight) && Gem::Version.new(ErrorHighlight::VERSION) >= Gem::Version.new("0.4.0")
```
Comment (byroot) [inline actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: So I'm not too concerned by performance for what is essentially a dev only error reporting, but for clarity it may make sense to extract that version check in a class method and memoize it. So that you can use the same logic here and in the template.

Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: Or in a constant, as this could be checked at load time.

Comment (mame) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: Actually, they are not completely the same. The tip message should be displayed only when `ErrorHighlight` *is* available but its version is lower than 0.4.0. Otherwise, it will be shown on Ruby 2.7 or TruffleRuby, which are not supported by error_highlight.

I created a patch, but it is larger than I expected because it requires passing a new argument to ActionView of the error page. I'm not sure if it will really improve the performance. Do you want me to add this?

```diff
diff --git a/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb b/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb
index 2ac604d5e1..7d48eb703b 100644
--- a/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb
+++ b/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb
@@ -121,6 +121,7 @@ def create_template(request, wrapper)
           trace_to_show: wrapper.trace_to_show,
           routes_inspector: routes_inspector(wrapper.exception),
           source_extracts: wrapper.source_extracts,
+          error_highlight_available: wrapper.error_highlight_available?,
           line_number: wrapper.line_number,
           file: wrapper.file
         )
diff --git a/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb b/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb
index 49299ea4d2..d3d725321f 100644
--- a/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb
+++ b/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb
@@ -128,6 +128,14 @@ def source_extracts
       end
     end

+    def error_highlight_available?
+      # ErrorHighlight.spot with backtrace_location keyword is available since error_highlight 0.4.0
+      unless defined?(@@error_highlight_available)
+        @@error_highlight_available = defined?(ErrorHighlight) && Gem::Version.new(ErrorHighlight::VERSION) >= Gem::Version.new("0.4.0")
+      end
+      @@error_highlight_available
+    end
+
     def trace_to_show
       if traces["Application Trace"].empty? && rescue_template != "routing_error"
         "Full Trace"
@@ -174,8 +182,7 @@ def clean_backtrace(*args)
       end

       def extract_source(trace)
-        # ErrorHighlight.spot with backtrace_location keyword is available since error_highlight 0.4.0
-        if defined?(ErrorHighlight) && Gem::Version.new(ErrorHighlight::VERSION) >= Gem::Version.new("0.4.0")
+        if error_highlight_available?
           spot = ErrorHighlight.spot(@exception, backtrace_location: trace)
           if spot
             line = spot[:first_lineno]
diff --git a/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb b/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
index 0ab2967fe4..d0d7a0663e 100644
--- a/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
+++ b/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
@@ -28,7 +28,7 @@
           </tr>
         </table>
       </div>
-      <%- if defined?(ErrorHighlight) && Gem::Version.new(ErrorHighlight::VERSION) < Gem::Version.new("0.4.0") -%>
+      <%- if defined?(ErrorHighlight) && !error_highlight_available -%>
         <p class="error_highlight_tip">Tip: You may want to add <code>gem 'error_highlight', '&gt;= 0.4.0'</code> into your Gemfile, which will display the fine-grained error location.</p>
       <%- end -%>
     </div>
diff --git a/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb b/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb
index a68eaab8d7..60654ce3d6 100644
--- a/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb
+++ b/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb
@@ -11,7 +11,7 @@
   <%= render "rescues/message_and_suggestions", exception: @exception %>
   <%= render "rescues/actions", exception: @exception, request: @request %>

-  <%= render "rescues/source", source_extracts: @source_extracts, show_source_idx: @show_source_idx, error_index: 0 %>
+  <%= render "rescues/source", source_extracts: @source_extracts, error_highlight_available: @error_highlight_available, show_source_idx: @show_source_idx, error_index: 0 %>
   <%= render "rescues/trace", traces: @traces, trace_to_show: @trace_to_show, error_index: 0 %>

   <% if @exception.cause %>
@@ -26,7 +26,7 @@
     </div>

     <div id="<%= wrapper.exception.object_id %>" class="hidden">
-      <%= render "rescues/source", source_extracts: wrapper.source_extracts, show_source_idx: wrapper.source_to_show_id, error_index: index %>
+      <%= render "rescues/source", source_extracts: wrapper.source_extracts, error_highlight_available: wrapper.error_highlight_available, show_source_idx: wrapper.source_to_show_id, error_index: index %>
       <%= render "rescues/trace", traces: wrapper.traces, trace_to_show: wrapper.trace_to_show, error_index: index %>
     </div>
   <% end %>
```

**Comment by mame** [comment]
> BTW: policy is to squash commits before merge. Since IMO this PR is either ready or almost ready, I think you can do it now.

Thank you, I have squashed my commits.

File: actionpack/lib/action_dispatch/middleware/exception_wrapper.rb (hunk 6 above)
Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/exception_wrapper.rb:178]: > Do you want me to add this?

I think it's better yes.

File: actionpack/test/dispatch/exception_wrapper_test.rb [hunk 7]
```diff
@@ -53,6 +53,25 @@ def backtrace
       end
     end
 
+    if defined?(ErrorHighlight)
```
Comment (yahonda) [inline actionpack/test/dispatch/exception_wrapper_test.rb:56]: More precisely, this condition also needs to see if error_highlight version is 0.4.0 or higher.

Comment (mame) [reply actionpack/test/dispatch/exception_wrapper_test.rb]: I have fixed it, thank you!

(After the commit, I noticed that this might be covered by Rails' Gemfile because this is a test, but the change would be good to have.)

File: railties/lib/rails/generators/rails/app/templates/Gemfile.tt (hunk 5 above)
Comment (mame) [reply railties/lib/rails/generators/rails/app/templates/Gemfile.tt:60]: The change is merged into this PR. Thank you!

**Comment by byroot** [comment]
Thank you!

**Comment by mame** [comment]
Thank you very much for being so patient with this PR!

**Comment by byroot** [comment]
My pleasure, there really wasn't much to change and it's a great feature.

**Comment by olivierlacan** [comment]
Fantastic addition. Thanks everyone!
