### ISSUE TITLE
Setting self.response_body = nil no longer prevents DoubleRenderError

### ISSUE THREAD

**Issue by kdough** [rails/rails#25106]
### Steps to reproduce

I am attempting to prevent a `AbstractController::DoubleRenderError` in a controller by setting `self.response_body = nil` before a second call to `render`.  The reason that multiple renders occur is that I have `after_action` callbacks that call `render` after the action itself has already rendered its response.

It is my understanding that `self.response_body = nil` should drop the previously-rendered body to allow a subsequent render call to succeed without causing a DoubleRenderError.

This works in **Rails 4.2.6** but it no longer appears prevent double rendering exceptions in Rails 5+ (including current master).

This simplified example shows a scenario that properly renders 'something else' in Rails 4.2.6 but fails in 5.0.0.rc1 (and master):

```ruby
# Rails 4.2.6
def should_prevent_double_render
  render json: { foo: 'something' }
  self.response_body = nil
  performed? # => false
  render json: { foo: 'something else' }
end

# Rails 5.0.0.rc1
def should_prevent_double_render
  render json: { foo: 'something' }
  self.response_body = nil
  performed? # => ["{\"foo\":\"something\"}"]
  render json: { foo: 'something else' }
  # ... AbstractController::DoubleRenderError is raised
end
```

Complete gist with tests replicating this issue is available here: https://gist.github.com/kdough/c797c25088331ffc275bb2aa6159bde9

### Expected behavior
Setting `self.response_body = nil` before a subsequent call to `render` should drop a previously-rendered response body.

### Actual behavior
As of **Rails 5+**, a `AbstractController::DoubleRenderError` exception is raised when a second call to `render` is made.  The previously-rendered content remains in the result of `performed?`

In **Rails 4.2.6**, the second call to `render` succeeds as expected.

### System configuration

* **Working Setup**:
 * **Rails version**:  4.2.6
 * **Ruby version**:  2.3.1p112

* **Broken Setup**:
 * **Rails version**:  5.0.0.rc1
 * **Ruby version**:  2.3.1p112

**Comment by sevaorlov** [comment]
seems to be related to https://github.com/rails/rails/issues/23964

**Comment by matthewd** [comment]
> It is my understanding that `self.response_body = nil` should drop the previously-rendered body to allow a subsequent render call to succeed without causing a DoubleRenderError.

Being able to "unrender" at all seems surprising to me. Is there documentation somewhere consistent with your understanding?

**Comment by maclover7** [comment]
Agree with @matthewd, I think this is unsupported behavior 😬

**Comment by kdough** [comment]
Thanks for the comments, everyone.  I am using Pundit and saw [this approach](https://github.com/elabs/pundit/issues/72#issuecomment-28178007) for dealing with DoubleRenderErrors caused by `after_action` calls that do a subsequent `#render`.

The behavior that I am seeing (which is why `performed?` is truthy) is the following:

In Rails 4.2.6 (expected behavior):
```ruby
self.response_body = 'foo'
self.response_body # => ["foo"]
response.body # => "foo"

self.response_body = nil
self.response_body # => nil
response.body # => ""
```

In Rails 5.0.0.rc1 (note that the previously-set response_body lingers and is _not_ set to nil):
```ruby
self.response_body = 'foo'
self.response_body # => ["foo"]
response.body # => "foo"

self.response_body = nil
self.response_body # => ["foo"]   <-- I would expect this to be nil
response.body # => ""
```

This was introduced in https://github.com/rails/rails/commit/c4d85dfbc71043e2a746acd310e32f4f04db801a

If being able to "re-render" is indeed unsupported, a (hacky) workaround is to omit the second call to `#render` and to just set `self.response_body = render_to_string ...` directly.

This seems like a bug to me, but I am curious if others agree.

**Comment by rafaelfranca** [comment]
By c4d85df seems that setting `response_body` to `nil` is a valid use case, so I agree this is a regression.

**Comment by rthbound** [comment]
I'm curious @kdough have you checked whether this regression occurs at 5.0.0.beta1?

**Comment by kdough** [comment]
@rthbound Yes, I can confirm that this regression occurs with 5.0.0.beta1 -- albeit with a ``NoMethodError: undefined method `each' for nil:NilClass`` since `body` is `nil` at [v5.0.0.beta1/actionpack/lib/action_controller/metal.rb#L177](https://github.com/rails/rails/blob/v5.0.0.beta1/actionpack/lib/action_controller/metal.rb#L177).

**Comment by rthbound** [comment]
@rafaelfranca @maclover7 can we add the "With reproduction steps" tag?

**Comment by matthewd** [comment]
@rafaelfranca I agree setting it to nil shouldn't raise an error; I don't agree that it allows you to unsend the response.

If we wanted to allow that (I strongly feel that we should not), then it deserves to be a first-class API method, not a secret hidden behaviour.

**Comment by rthbound** [comment]
> From: /home/rth/Software/rails/actionpack/lib/action_controller/metal.rb @ line 177 ActionController::Metal#response_body=:

```
    174: def response_body=(body)
    175:   body = [body] unless body.nil? || body.respond_to?(:each)
    176:   response.reset_body!
 => 177:   return unless body #=> returns here when dev tries setting Response#response_body to nil
    178:   response.body = body
    179:   super
    180: end
```

My understanding from the conversation here and the work done on other (related?) issues is that it should be possible to reset the body as attempted by @kdough in normal requests and it should _not_ be possible to reset the body in this way for streaming requests. /cc @matthewd & @rafaelfranca

**Comment by toupeira** [comment]
I ran into the same issue while developing an [OpenID Connect extension](https://github.com/doorkeeper-gem/doorkeeper-openid_connect) for the doorkeeper gem, the use-case is that certain behaviours are user-defined and might involve redirects, but in some cases I have to ignore that response and send my own. It would be nice to have a supported API for this, maybe a `reset_body!` method on the controller to mirror the one from the response.

Also, as a temporary workaround the following seems to work fine on 5.0.0.1 with non-streaming responses:

```ruby
self.response_body = nil
@_response_body = nil
```

**Comment by tomrossi7** [comment]
I just wanted to add another use case. We run into this problem when attempting to resolve a double render issue while rescuing from `ActionController::InvalidCrossOriginRequest`

```
  rescue_from ActionController::InvalidCrossOriginRequest, with: :raise_nothing

  def raise_nothing
    self.response_body = nil
    render status: 500, layout: false, file: 'public/500.html'
  end
```

Maybe this should be a separate issue related to the  `rescue_from` method?

**Comment by saiqulhaq** [comment]
I am having this issue with rails 5.0.7.2

**Comment by MacksMind** [comment]
`@_response_body = nil` seems to have the desired effect, but also reeks of code smell.

**Comment by MacksMind** [comment]
Missed seeing that @toupeira already discovered this workaround, so take my comment as confirmation it still works in 5.2.4.4.

**Comment by intrip** [comment]
@matthewd @rafaelfranca 
Looks like the community needs a proper way of unsending a response, I'd like to make a PR introducing this functionality adding an ad-hoc method to the public API: sounds good to you?
