### ISSUE TITLE
Race condition in `ConnectionPool::Checkout` on `@pinned_connection`

### ISSUE THREAD

**Issue by SjoerdL** [rails/rails#53980]
### Steps to reproduce

The `checkout` method in `ConnectionPool` can crash, if another thread is cleaning up the `@pinned_connection`. 
This happens for us in CI with system tests.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "~> 7.2.2"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

# Create our own monitor, so that we can pass the thread at the right moment
class MyMonitor < ActiveSupport::Concurrency::ThreadLoadInterlockAwareMonitor
  def synchronize
    # If we get called from `checkout`, we want to have our other thread clean up the `@pinned_connection`.
    # When that is done, the continuation in `checkout` will fail, because it assumes `@pinned_connection` is still there.
    if caller[0].include?('checkout')
      Thread.pass
      sleep(0.1)
    end
  
    super # continue with the normal flow of `ThreadLoadInterlockAwareMonitor`
  end
end

class BugTest < Minitest::Test
  def test_threading_stuff
    pool = ActiveRecord::Base.connection_pool

    # Pin a connection, similar to what we do in `setup_transactional_fixtures`
    pool.pin_connection!(true)

    # We overwrite the locker set on @pinned_connection with our own version
    pinned_connection = pool.instance_variable_get(:@pinned_connection)
    pinned_connection.instance_variable_set(:@lock, MyMonitor.new)

    Thread.new {
      sleep(0.2)
      
      # Checkout a connection. This can happen in a system spec when the system (eg front-end) makes async requests
      pool.checkout
    }.join(0.1)

    Thread.new {
      sleep(0.2)

      # Unpin the connection, similar to what is happening in `teardown_transactional_fixtures`
      pool.unpin_connection!
    }.join(0.1)

    # Pass the test. The test will raise when the thread is trying to use the pinned connection, while it is being cleaned up
    assert_equal 0, 0

    # Sleep so that we still catch the error during the runtime of this spec
    sleep(2)
  end
end
```

### Expected behavior

The code should not crash in the `checkout` method. The `checkout` of a connection should work, just as if there is no `pinned_connection`.

### Actual behavior

The code crashes. It throws a `NoMethodError`:

```ruby
Users/myname/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:554:in `block (2 levels) in checkout': undefined method `verify!' for nil:NilClass (NoMethodError)

              @pinned_connection.verify!
                                ^^^^^^^^
	from /Users/myname/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/monitor.rb:202:in `synchronize'
	from /Users/myname/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/monitor.rb:202:in `mon_synchronize'
	from /Users/myname/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:553:in `block in checkout'
```

### System configuration

**Rails version**:
Rails 7.2.2.1

**Ruby version**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by SjoerdL** [comment]
I believe this issue is caused by #52235. It now synchronizes on the `@pinned_connection.lock` first (line 544), but doesn't have a lock yet on the `ConnectionPool`. That only happens on line 545.
