### ISSUE TITLE
undefined method in_rendering_context

### ISSUE THREAD

**Issue by aniketstiwari** [rails/rails#41048]
After updating from rails 5.2 to rails 6. I am getting this error. The issue lies in the render method

NoMethodError - undefined method `in_rendering_context' for #<TransactionPdf:0x000056199a9e1ec0>:
  app/controllers/users_controller.rb:39:in `download_receipt'
  app/controllers/application_controller.rb:345:in `set_current_user'
  app/middleware/skip_trackable.rb:8:in `call'

```
def download_receipt
  @presenter = UserPresenter.new
  pdf = TransactionPdf.new(@presenter)
  send_data pdf.render, type: 'application/pdf', filename: @presenter.file_name
end
```

I was going through this articles https://github.com/komposable/komponent/issues/133 but didn't got much help. Anyone else has encountered this issue or any help will be appreciated

This PR: https://github.com/rails/rails/commit/3077cdf921fed35c1e743db5911d7e4b589a684e has change the method internally from in_context to in_rendering_context

I have ask the same question on SO: https://stackoverflow.com/questions/65623726/undefined-method-in-rendering-context but haven't got any response

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
It seems that some library you are using need to change the method name. 
Can you provide an example application that reproduce the issue?

**Comment by donnykurnia** [comment]
I got this failed rspec test after updating from rails 5.2.8 to 6.0.6.1

```
  2) Api::V1::Documents::MergedDocumentsController entry guids present in the params POST #show delegates to the properly configured content generator
     Failure/Error:
       send_data(
         pdf,
         filename: custom_filename || filename,
         type: 'application/pdf',
         disposition: 'inline'
       )

     NoMethodError:
       undefined method `in_rendering_context' for :view_context:Symbol
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionview-6.0.6.1/lib/action_view/rendering.rb:116:in `_render_template'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionview-6.0.6.1/lib/action_view/rendering.rb:103:in `render_to_body'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/abstract_controller/rendering.rb:25:in `render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:36:in `render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/mongoid-7.4.3/lib/mongoid/railties/controller_runtime.rb:27:in `cleanup_view_runtime'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/remotipart-1.4.4/lib/remotipart/render_overrides.rb:23:in `render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/wicked_pdf-2.6.3/lib/wicked_pdf/pdf_helper.rb:18:in `render'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/data_streaming.rb:111:in `send_data'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:58:in `block in send_data'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180:in `block in instrument'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180:in `instrument'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:57:in `send_data'
     # ./app/controllers/api/v1/documents/merged_documents_controller.rb:196:in `send_pdf'
     # ./app/controllers/api/v1/documents/merged_documents_controller.rb:13:in `show'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/abstract_controller/base.rb:195:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/public_activity-2.0.2/lib/public_activity/utility/store_controller.rb:27:in `store_controller_for_public_activity'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actiontext-6.0.6.1/lib/action_text/rendering.rb:19:in `with_renderer'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actiontext-6.0.6.1/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:121:in `instance_exec'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180:in `block in instrument'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180:in `instrument'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/mongoid-7.4.3/lib/mongoid/railties/controller_runtime.rb:21:in `process_action'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/abstract_controller/base.rb:136:in `process'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionview-6.0.6.1/lib/action_view/rendering.rb:39:in `process'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/metal.rb:190:in `dispatch'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/test_case.rb:517:in `process'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/devise-4.9.4/lib/devise/test/controller_helpers.rb:35:in `block in process'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/devise-4.9.4/lib/devise/test/controller_helpers.rb:104:in `catch'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/devise-4.9.4/lib/devise/test/controller_helpers.rb:104:in `_catch_warden'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/devise-4.9.4/lib/devise/test/controller_helpers.rb:35:in `process'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/actionpack-6.0.6.1/lib/action_controller/test_case.rb:403:in `post'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/integration.rb:16:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/api/v1/documents/merged_documents_controller_spec.rb:638:in `verify_content_generator_with'
     # ./spec/controllers/api/v1/documents/merged_documents_controller_spec.rb:72:in `block (3 levels) in <module:Documents>'
     # /app/heroku/ruby/bundle/ruby/2.7.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
```

**Comment by donnykurnia** [comment]
Please reopen this issue
