### ISSUE TITLE
ActiveRecord 4.2 - undefined method `type_cast_from_database'

### ISSUE THREAD

**Issue by fatim** [rails/rails#18739]
After updating ActiveRecord to 4.2 certain database queries crash with:
".. /lib/ruby/gems/2.1.0/gems/activerecord-.2.0/lib/active_record/attribute.rb:94:in `type_cast': undefined method `type_cast_from_database' for "NUMBER(9)":String (NoMethodError)"

I'm accessing database via activerecord-oracle_enhanced-adapter (1.5.5).
Is this an issue with ActiveRecord or with activerecord-oracle_enhanced-adapter calling deprecated methods ?

**Comment by rafaelfranca** [comment]
I think it is an issue with `activerecord-oracle_enhanced-adapter` cc @yahonda.

Could you create an reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by rafaelfranca** [comment]
Actually this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by yahonda** [comment]
@fatim Add this entry to your Gemfile then this issue should be fixed since it is similar with rsim/oracle-enhanced#536

```ruby
gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'rails42'  
```
If you still reproduce this issue, please report it to https://github.com/rsim/oracle-enhanced/

@rafaelfranca 
It's not a Rails issue you can go ahead to close this.

**Comment by rafaelfranca** [comment]
Thanks

**Comment by shouquan** [comment]
this issue had been solved by anybody?can somebody tell me how to handle with this issue? thank you!

**Comment by rolandoivan23** [comment]
You can use ActiveRecord -v 4.1.10 it works for me

**Comment by shouquan** [comment]
ok~i will try it.Thank you for your reply!






在 2015-04-29 05:21:53，"Rolando Iván Vázquez" <notifications@github.com> 写道：


You can use ActiveRecord -v 4.1.10 it works for me
