### PR TITLE
Fix default_url_options accessor

### PR DESCRIPTION
**Pull request by dtaniwaki**
### Summary

I found this issue when I tested my helper including routes url_helper such as `xxx_path`.

screen shot 2016-04-21 at 12 05 51 pm

The `helper` of `rspec-rails` does not have `default_url_options` originally because it's not `ActionController` nor `ActionMailer`. In this case, we can't take `default_url_options` to call `xxx_path` even though `ActionDispatch::Routing::UrlFor` defines the setter on the `included` hook.

### CODE REVIEW

**Comment by schneems** [comment]
cc/ @pixeltrix

**Comment by pixeltrix** [comment]
I managed to replicate the error in a single script like this:

``` ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '5.0.0.beta3'
  gem 'rspec-rails', '3.5.0.beta3'
end

require "rails"
require 'action_controller/railtie'
require 'action_view/railtie'
require 'rspec/rails'
require 'rspec/autorun'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.eager_load = false
  config.logger = Logger.new($stdout)
end

Rails.application.initialize!

Rails.application.routes.draw do
  root to: 'pages#index'
end

module ApplicationHelper
  include Rails.application.routes.url_helpers
end

class ApplicationController < ActionController::Base
  protect_from_forgery
end

class PagesController < ApplicationController
  def index; end
end

RSpec.describe "url helpers", type: :helper do
  let(:headers) { helper.request.env }

  describe "#root_url" do
    before do
      ActionController::Base.default_url_options = { host: 'www.foobar.com' }
    end

    it "generates 'http://www.foobar.com/'" do
      expect(helper.root_url).to eq('http://www.foobar.com/')
    end
  end
end
```

This gives the following error:

```
F

Failures:

  1) url helpers #root_url generates 'http://www.foobar.com/'
     Failure/Error: expect(helper.root_url).to eq('http://www.foobar.com/')

     NameError:
       undefined local variable or method `default_url_options' for #<#<Class:0x007fb274510850>:0x007fb274501210>
     # /Users/andyw/.rvm/gems/ruby-2.2.4@rails-5-0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/url_for.rb:198:in `optimize_routes_generation?'
     # /Users/andyw/.rvm/gems/ruby-2.2.4@rails-5-0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/route_set.rb:192:in `optimize_routes_generation?'
     # /Users/andyw/.rvm/gems/ruby-2.2.4@rails-5-0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/route_set.rb:172:in `call'
     # /Users/andyw/.rvm/gems/ruby-2.2.4@rails-5-0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/routing/route_set.rb:295:in `block (2 levels) in define_url_helper'
     # rails-24679.rb:59:in `block (3 levels) in <main>'

Finished in 0.00603 seconds (files took 0.49304 seconds to load)
1 example, 1 failure

Failed examples:

rspec rails-24679.rb:58 # url helpers #root_url generates 'http://www.foobar.com/'
```

However I think this is possibly an error in your `spec/rails_helper.rb` file because moving these two lines:

``` ruby
require 'rspec/rails'
require 'rspec/autorun'
```

to after the definition of `PagesController` makes the spec pass. Can you double check that the

```
require 'rspec/rails'
```

line is after line that loads Rails in your `spec/rails_helper.rb` file - thanks.

**Comment by dtaniwaki** [comment]
Hi @pixeltrix Thank you for debugging the issue.
I found easier way to reproduce this issue. It's actually happens without rspec.

```rb
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '5.0.0.beta3'
end

require "rails"
require 'action_controller/railtie'
require 'action_view/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'
  
  config.eager_load = false
  config.logger = Logger.new($stdout)

  routes.default_url_options = { host: 'www.foobar.com' }
end

Rails.application.initialize!

Rails.application.routes.draw do
  root to: 'pages#index'
end

module ApplicationHelper
  include Rails.application.routes.url_helpers
end

class ApplicationController < ActionController::Base
  protect_from_forgery
end

class PagesController < ApplicationController
  def index; end 
end

class Foo 
  include ApplicationHelper
end

puts Rails.application.routes.url_helpers.root_url
# => http://www.foobar.com/
puts Foo.new.root_url
# => undefined local variable or method `default_url_options' for #<Foo:0x007fd52202aa40 @_routes=nil> (NameError)
```

You can actually reproduce this in your rails console as well.

```rb
[1] 2.3.0-p0(main)> module Foo; include Rails.application.routes.url_helpers; end
=> Foo
[2] 2.3.0-p0(main)> include Foo
=> Object
[3] 2.3.0-p0(main)> root_path
NameError: undefined local variable or method `default_url_options' for main:Object
```

I think modules including `Rails.application.routes.url_helpers` are able to work independently since `Rails.application.routes.url_helpers` is.

**Comment by pixeltrix** [comment]
@dtaniwaki that's because you're not using `ActiveSupport::Concern`, e.g:

``` irb
>> module Foo; extend ActiveSupport::Concern; include Rails.application.routes.url_helpers; end
>> include Foo
>> root_path
=> "/"
```

By not using it you're not executing [this block of code][1]:

``` ruby
included do
  unless method_defined?(:default_url_options)
    # Including in a class uses an inheritable hash. Modules get a plain hash.
    if respond_to?(:class_attribute)
      class_attribute :default_url_options
    else
      mattr_writer :default_url_options
    end

    self.default_url_options = {}
  end

  include(*_url_for_modules) if respond_to?(:_url_for_modules)
end
```

However that's largely irrelevant - AFAICS a vanilla Rails 5.0b3 app with RSpec for Rails 3.5.0b3 exposes url helpers on the `helper` object. Do you have a example where that isn't true?

[1]: https://github.com/rails/rails/blob/e007afd3cd7255c752fe8ab7fa24b59526ab95cb/actionpack/lib/action_dispatch/routing/url_for.rb#L89-L102

**Comment by dtaniwaki** [comment]
@pixeltrix That's true.

I made sure that `require 'rspec/rails'` is after the rails initialization as below.

screen shot 2016-04-24 at 11 24 21 pm

However, it still throws the same exception. It might be a problem of rspec-rails.

https://github.com/rspec/rspec-rails/blob/ae6ff7beeca8a73394ee98a388d0440ec10e2208/lib/rspec/rails/example/helper_example_group.rb#L31

I will investigate it more when I have time.

**Comment by pixeltrix** [comment]
Closing due to inactivity
