### PR TITLE
Fixes #51780: prevent shared PostgreSQL queries from racing with reconnects

### LINKED ISSUE #51780: Possible race condition in postgresql type_map initialization
### Steps to reproduce
Since upgrading from Rails 7.0 to 7.1 we've started to see the following exception:

```
# activerecord (7.1.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb in get_oid_type
undefined method `key?' for nil:NilClass (NoMethodError)
          if !type_map.key?(oid)
                      ^^^^^
```

I haven't been able to replicate the behavior outside of production where it occurs when the application briefly loses its connection to the postgres database while under load. This is a multi-threaded environment. The server never recovers after entering this state. 

I know there was a change to type_map initialization at https://github.com/rails/rails/commit/dc4420c564565affadcd0d68db1af7ce2183bea4, and it looks to me like it's possible there's a race condition here. I'll update this issue with steps to replicate if I can manage to trigger this outside of production.

### Expected behavior
The application should recover from a brief database outage and reconnect.

### Actual behavior
The server is never able to reconnect. 

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.2.4

### PR DESCRIPTION
**Pull request by oneearedrabbit**
### Motivation / Background

abstract_adapter.rb with default settings has a race condition. Rails 7.1 introduced a regression in https://github.com/rails/rails/pull/46519 by assuming that connections are never shared across threads. In practice, that assumption doesn't always hold, especially in applications that use a connection pool together with RDS Proxy. PostgreSQLAdapter requires a lock since type_map is initialized lazily, a change made in https://github.com/rails/rails/pull/44570.

Cross-referencing https://github.com/rails/rails/issues/51780#issuecomment-4583353372.

### Detail

Add a `connection_lock` database config for applications that share a connection across threads or fibers. When enabled, ActiveRecord locks the adapter during reconnect and PostgreSQL result processing so a shared connection cannot be used while it is being reconnected.

I noticed that some type_map readers were not guarded, I added `@lock.synchronize` in a few additional places. I am leaving this to your best judgement since that work ballooned beyond connection_pool, abstract_adapter, and postgresql_adapter classes, and I am less familiar with database_statements class.

### Additional information

Repro of the original issue:
```ruby
$ cat Gemfile
ruby "3.3.4"
gem "activerecord", "=8.1.3"

$ cat database.yml
development:
  adapter: postgresql
  url: postgres://localhost:5432/giza_development
  database: giza_development
  username: postgres
  gssencmode: disable
  pool: 5

$ cat repro.rb
require "active_record"
require "yaml"
config = YAML.load(File.read("database.yml"))["development"]
ActiveRecord::Base.establish_connection(config)
Thread.abort_on_exception = true
ActiveRecord::Base.connection_pool.with_connection do |connection|
  Thread.new(connection) do |pg|
    pg.reconnect!
  end
  p connection.select_values("SELECT 1")
end

$ irb -r ./repro.rb
/opt/homebrew/lib/ruby/gems/3.3.0/gems/activerecord-8.1.3/lib/active_record/connection_adapters/postgresql_adapter.rb:876:in `get_oid_type': undefined method `key?' for nil (NoMethodError)

          if !type_map.key?(oid)
                      ^^^^^
```

After the following patch is applied, the error is no longer reproducible:
```ruby
module ActiveRecord::ConnectionAdapters::PostgreSQLAdapterPatch
  def initialize(
    config_or_deprecated_connection,
    deprecated_logger = nil,
    deprecated_connection_options = nil,
    deprecated_config = nil
  )
    super
    @lock = ActiveSupport::Concurrency::ThreadMonitor.new
  end
end

class ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
  prepend ActiveRecord::ConnectionAdapters::PostgreSQLAdapterPatch
end
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by jondavidschober** [comment]
+1 for this. I’ve been hesitant to upgrade rails because this was such an impactful regression for us

**Comment by skipkayhil** [comment]
> by assuming that connections are never shared across threads

This is a valid assumption though, you _should not_ be sharing connections between threads.

> I’ve been hesitant to upgrade rails because this was such an impactful regression for us

Have you followed the progress in the linked issue? There were many fixes applied/released to address the `type_map` issue.

**Comment by oneearedrabbit** [comment]
@skipkayhil I don't disagree :-) My point is that there is a known race condition in ActiveRecord/PostgreSQLAdapter which `lock_thread` was originally meant to guard against. Apparently, there were quite a few reports showing that the shared connections contract isn't always followed, and with `NullLock` that became a weak spot which led to #51780.

Conceptually, there are two possible directions:
1. If connections are truly never shared, then we should brainstorm on enforcing the contract and making violations easier to detect.
2. If connections are not supposed to be shared, but in practice they are, whether intentionally or not, then `lock_thread` should be configurable from application code.

Right now, the implementation is at midpoint: the mechanism exists, but users can neither configure it nor easily diagnose underlying issues.

Option 1 is essentially "not a bug; fix the vendor libraries", which probably also means adding better diagnostics so users can find culprits more easily, while Option 2 is a more practical and user-friendly compromise.

At the very least, I do hope we can agree that a race condition itself is undesirable regardless of any external factors.

**Comment by byroot** [comment]
> you _should not_ be sharing connections between threads.

Yep.

> making violations easier to detect.

So you mention RDS proxy being a cause, which seems weird to me because I don't see what a proxy would change in term of in process concurrent accesses.

Have you yourself ran a modified version of the adapter that raises on concurrent access to try to find the root cause?

**Comment by oneearedrabbit** [comment]
Writing this here down for archival purposes and for any future spelunkers, since I haven't yet been able to isolate the issue cleanly in our environment:
1. Rails 8.0.3 to Rails 8.0.5 upgrade -> no significant changes observed.
2. Rails 8.0.5 to Rails 8.1.3 upgrade -> escalated both `TypeMap` and `get_oid_type` errors. I'm providing stack traces below, but these are side-effects and don't seem by themselves explain much.
3. Reduced max_age -> escalated both errors again.
4. pg gem 1.5.8 to 1.6.3 upgrade -> no changes.

Some additional application specific notes:
1. Long-running Temporal activities
2. We applied two patches to the PostgreSQLAdapter to avoid connection pinning in RDS Proxy, https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-pinning.html:
    - deleted DISCARD ALL in `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#reset!`
    - replaced SET statements in `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#configure_connection`

I was unable to identify any cross-thread shared database connections through static analysis beyond the standard Rails mechanism.

After we changed the `max_age` setting, my working hypothesis was the reaper thread marks a connection as stale and ultimately calls "connect", which instantiates a new `@raw_connection` instance and therefore `@type_map`, creating a small window in which the PG connection is in an incomplete state. That was a stretching theory, and I am unable to prove it by using standard interfaces. The earlier repro mechanically called `reconnect!`, and I am not confident I fully understand the conditions under which the issue manifests beyond what's been said already.

We continue to investigate the issue.

Stack traces:

<details>
<summary>Stack trace for the TypeMap error</summary>
<pre>
lib/pg/result.rb:17:in `type_map=': wrong argument type nil (expected PG::TypeMap) (TypeError)
	from lib/pg/result.rb:17:in `map_types!'
	from postgresql/database_statements.rb:16:in `query'
	from connection_adapters/postgresql_adapter.rb:1058:in `column_definitions'
	from abstract/schema_statements.rb:110:in `columns'
	from connection_adapters/schema_cache.rb:345:in `block (2 levels) in columns'
	from abstract/connection_pool.rb:457:in `with_connection'
	from connection_adapters/schema_cache.rb:344:in `block in columns'
	from connection_adapters/schema_cache.rb:343:in `fetch'
	from connection_adapters/schema_cache.rb:343:in `columns'
	from connection_adapters/schema_cache.rb:354:in `block in columns_hash'
	from connection_adapters/schema_cache.rb:353:in `fetch'
	from connection_adapters/schema_cache.rb:353:in `columns_hash'
	from connection_adapters/schema_cache.rb:54:in `columns_hash'
	from connection_adapters/schema_cache.rb:198:in `columns_hash'
	from active_record/model_schema.rb:609:in `load_schema!'
	from active_record/counter_cache.rb:212:in `load_schema!'
	from encryption/encryptable_record.rb:127:in `load_schema!'
	from active_record/model_schema.rb:555:in `block in load_schema'
	from active_record/model_schema.rb:552:in `synchronize'
	from active_record/model_schema.rb:552:in `load_schema'
	from active_record/model_schema.rb:444:in `columns_hash'
	from active_record/attributes.rb:257:in `block in _default_attributes'
	from abstract/connection_pool.rb:463:in `with_connection'
	from active_record/connection_handling.rb:313:in `with_connection'
	from active_record/attributes.rb:256:in `_default_attributes'
	from active_model/attribute_registration.rb:38:in `attribute_types'
	from active_record/attribute_methods.rb:261:in `_has_attribute?'
	from active_record/inheritance.rb:61:in `new'
</pre>
</details>

<details>
<summary>Stack trace for the get_oid_map error</summary>
<pre>
connection_adapters/postgresql_adapter.rb:876:in `get_oid_type': undefined method `key?' for nil (NoMethodError)
	from postgresql/database_statements.rb:188:in `block in cast_result'	
from <internal:numeric>:237:in `times'
	from postgresql/database_statements.rb:185:in `cast_result'
	from abstract/database_statements.rb:555:in `internal_exec_query'
	from abstract/database_statements.rb:708:in `select'
	from abstract/database_statements.rb:76:in `select_all'
	from abstract/query_cache.rb:275:in `block in select_all'
	from abstract/query_cache.rb:313:in `block (2 levels) in cache_sql'
	from abstract/query_cache.rb:90:in `compute_if_absent'
	from abstract/query_cache.rb:311:in `block in cache_sql'
	from concurrency/null_lock.rb:9:in `synchronize'
	from abstract/query_cache.rb:310:in `cache_sql'
	from abstract/query_cache.rb:275:in `select_all'
	from active_record/querying.rb:68:in `_query_by_sql'
	from active_record/querying.rb:53:in `block in find_by_sql'
	from abstract/connection_pool.rb:457:in `with_connection'
	from active_record/connection_handling.rb:313:in `with_connection'
	from active_record/querying.rb:52:in `find_by_sql'
	from active_record/statement_cache.rb:156:in `execute'
	from active_record/core.rb:455:in `block in cached_find_by'
	from abstract/connection_pool.rb:463:in `with_connection'
	from active_record/connection_handling.rb:313:in `with_connection'
	from active_record/core.rb:443:in `cached_find_by'
	from active_record/core.rb:278:in `find'
</pre>
</details>
