### PR TITLE
Fix `ActiveSupport::Inflector.humanize(nil)`

### PR DESCRIPTION
**Pull request by robinjam**
### Motivation / Background

Fixes a regression introduced in #48348.

In activesupport v7.0.5.1, `ActiveSupport::Inflector.humanize(nil)` returned `""`.
In activesupport v7.0.6, it raises ``NoMethodError: undefined method `end_with?' for nil:NilClass``.

### Detail

This PR adds a regression test to surface the issue, and restores the original behaviour.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by byroot** [comment]
Thanks. Backported to `7-0-stable`.
