### ISSUE TITLE
ActiveRecord::ActiveRecordError: Cannot lease connection, it is already in use by a different thread

### ISSUE THREAD

**Issue by sonalkr132** [rails/rails#25585]
### Steps to reproduce
* rails new my_app
* export DISABLE_SPRING=true
* rails g scaffold post title:string body:text
* echo "gem 'pg'" >> Gemfile & bundle
* set up database.yml
```yml
development: &DEVELOPMENT
  adapter: postgresql
  database: myapp_development
  username: <username>
  password: <password>
  host: localhost
  pool: 5
  timeout: 5000

test: &TEST
  <<: *DEVELOPMENT
  database: myapp_test
  min_messages: warning
```
* rake db:create db:migrate
* Change models/post.rb to:
```Ruby
 def self.update_body(title)
    post = Post.find_by(title: title)
    post.update_attributes(body: 'body body')
  end
```

* Change test/models/post_test.rb to:
```Ruby
require 'test_helper'

class PostTest < ActiveSupport::TestCase

  test "something" do
    post = Post.create(body: 'some body', title: 'some title')
    assert_equal 'some body', post.body
  end

  uses_transaction :test_update_body_atomically
  def test_update_body_atomically
    Post.create(body: 'some body', title: 'some title')

    25.times do
      Array.new(4) do
        Thread.new { Post.update_body('some title')}
      end.each(&:join)
    end
    assert_equal 'body body', Post.find_by(title: 'some title').body
  ensure
    Post.delete_all
  end
end
```
* Run `rails test test/models/post_test.rb` until you see the error (Should be less than 20 times.. so may be write a script for it :stuck_out_tongue: )

### Expected behavior
Test should have passed

### Actual behavior
```
message type 0x54 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
message type 0x54 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
E

Error:
PostTest#test_update_body_atomically:
ActiveRecord::ActiveRecordError: Cannot lease connection, it is already in use by a different thread: #<Thread:0x00000004a24f78>. Current thread: #<Thread:0x00000003f03018>.
    app/models/post.rb:4:in `update_body'
    test/models/post_test.rb:16:in `block (3 levels) in test_update_body_atomically'
```

### System configuration
**Rails version**:
5.0.0.rc2
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**pg gem version**
0.18.4
**postgres version**
9.4.7

I won't be able the explain the logicality of the test or that function. I am just trying to mimic what I am doing in my real app. If you would rather see the real build failure you can check it out [here](https://travis-ci.org/rubygems/rubygems.org/jobs/140831890#L1126). 
I am sorry but I don't have much to provide other than "this was not an issue on rails 4.2.6". Let me know how I can help debug this.

EDIT: Simplified method and removed cases where the error was not reproduceable.

**Comment by maclover7** [comment]
Can you try and do a `git bisect` to figure out where this behavior was introduced?

**Comment by sonalkr132** [comment]
I need help writing script for it. Following gives `undefined method 'uses_transaction' for BugTest:Class (NoMethodError)`:
```Ruby
require 'active_record'
require 'minitest/autorun'
require 'logger'

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(
  adapter: 'postgresql',
  database: 'myapp_test',
  username: <user>,
  password: <password>,
  host: 'localhost',
  pool: 5,
  timeout: 5000
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.text :body
    t.string :title
  end
end

class Post < ActiveRecord::Base
   def self.update_body(title)
    post = Post.find_by(title: title)
    post.update_attributes(body: 'body body')
  end
end

class BugTest < ActiveSupport::TestCase
  test "something" do
    post = Post.create(body: 'some body', title: 'some title')
    assert_equal 'some body', post.body
  end

  uses_transaction :test_update_body_atomically
  def test_update_body_atomically
    Post.create(body: 'some body', title: 'some title')

    25.times do
      Array.new(4) do
        Thread.new { Post.update_body('some title')}
      end.each(&:join)
    end
    assert_equal 'body body', Post.find_by(title: 'some title').body
  ensure
    Post.delete_all
  end
end
```

**Comment by maclover7** [comment]
Hmm, can you try adding `include ActiveRecord::TestFixtures`? This along with some other items are required with Rails' default `test_helper` --> https://github.com/rails/rails/blob/master/railties/lib/rails/test_help.rb#L18

**Comment by matthewd** [comment]
Is `uses_transaction` necessary to reproduce the problem?

**Comment by sonalkr132** [comment]
`git bisect` got me here https://github.com/rails/rails/commit/e92f5a99d6a6306d96b4c7dd8f96c2822f2f2c7b

> Is uses_transaction necessary to reproduce the problem?

No.
