### PR TITLE
Fix #47561 and Streaming responses

### LINKED ISSUE #47561: ActiveStorage Proxy fails on Puma with: undefined method `to_ary'
### Steps to reproduce
Started with a barebones rails edge install with active_storage installed and a minimal test case:

app/models/picture_frame.rb
```
class PictureFrame < ApplicationRecord
  has_one_attached :picture
end
```

db/migrate/20230302181354_create_picture_frames.rb
```
class CreatePictureFrames < ActiveRecord::Migration[7.0]
  def change
    create_table :picture_frames do |t|

      t.timestamps
    end
  end
end
```

config/initializers/active_storage.rb
```
Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy
```

in rails console I manually set up a simple test case:
```
irb(main):001:0> p = PictureFrame.create
=> #<PictureFrame:0x000000010bb801a8 id: 2, created_at: Thu, 02 Mar 2023 19:37:21.674961000 UTC +00:00, updated_at: Thu, 02 Mar 2023 19:37:21.674961000 UTC +00:00>
irb(main):002:0> f = File.open('test.jpg')
=> #<File:test.jpg>
irb(main):003:0> p.picture.attach(io: f, filename: 'test.jpg', content_type: 'image/jpg')
...
irb(main):004:0> p.save
=> true
irb(main):005:0> app.rails_representation_path(p.picture)
=> "/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsiZGF0YSI6NCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1cee12a7b22044d58c2e760c4e6bc5768191c94/test.jpg"
```

Same result when using variations too.

### Expected behavior
As seen with rails commit e89b2e42711e7f2a9001cf6ee50c1dc37cdc18c1
```
=> Booting Puma
=> Rails 7.1.0.alpha application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 6.1.1 (ruby 3.2.0-p0) ("The Way Up")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 6636
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1nPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--b8d84e5130fbf7942217e6aed28288da994320d2/test.jpg" for ::1 at 2023-03-02 11:27:05 -0800
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by ActiveStorage::Blobs::ProxyController#show as JPEG
  Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1nPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--b8d84e5130fbf7942217e6aed28288da994320d2", "filename"=>"test"}
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Disk Storage (1.3ms) Downloaded file from key: avir98wqd0j07jcgpk5c19sb4mgt
Completed 200 OK in 70ms (ActiveRecord: 1.5ms | Allocations: 30861)
```

### Actual behavior
As seen with all commits starting with 218ec10df8ec9a84a5090b5c2b985dfcd8e7b820
```
=> Booting Puma
=> Rails 7.1.0.alpha application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 6.1.1 (ruby 3.2.0-p0) ("The Way Up")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 18300
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1nPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--b8d84e5130fbf7942217e6aed28288da994320d2/test.jpg" for ::1 at 2023-03-02 11:28:44 -0800
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by ActiveStorage::Blobs::ProxyController#show as JPEG
  Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6Ik1nPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--b8d84e5130fbf7942217e6aed28288da994320d2", "filename"=>"test"}
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Disk Storage (4.2ms) Downloaded file from key: avir98wqd0j07jcgpk5c19sb4mgt
2023-03-02 11:28:45 -0800 Read: #<NoMethodError: undefined method `to_ary' for #<Thread::SizedQueue:0x00000001049dd140>>
Completed 200 OK in 124ms (ActiveRecord: 1.6ms | Allocations: 31071)
```

### System configuration
**Rails version**: Anything after 218ec10df8ec9a84a5090b5c2b985dfcd8e7b820

**Ruby version**: 3.2.0

**Rack version**: Didn't seem to matter but the bulk of my tests were using 2.2.6.2

**Puma version**: 6.1.1 but saw similar results with earlier versions.

Likely caused by #47092

### PR DESCRIPTION
**Pull request by JoeDupuis**
[Changes to support Rack 3 ](https://github.com/rails/rails/pull/47092)broke Streaming responses 
Streaming responses are [failing with undefined method `to_ary'](https://github.com/rails/rails/issues/47561) 

Live::Response should not respond to `to_ary` since they cannot be
buffered safely.

I also added a system test (with a dummy app) to fix the gap in testing. It was failing for a while without the test suite alerting us.

### Detail

So that reviewers can try the test with and without the fix and to make it easier to review the PR (reviewing by commits to remove the noise of the dummy app), the PR is split in 3 commits
- The dummy app 
- The test
- The fix

I can merge them into one commit before merging.

### Additional information

I didn't want to add a dummy app, and resort to a system test, but  I can't figure out how to write a valid test for it without system tests.
Rack::Test doesn't support streaming which prevent usage of integration tests. 
I can pair if you want to give it a shot. I thought of fixing Rack::Test to support streaming, but I am not sure if the fix would be accepted upstream and I think the system test setup could come handy in the future.

We could potentially call the (rack) app directly and assert on the reponse. It would still load everything, but it would skip the server and browser part.

### CODE REVIEW

**Comment by JoeDupuis** [comment]
@guilleiguaran Just saw [your fix](https://github.com/rails/rails/commit/017428390115b1f7f7c1366fc60cac1032fd0ed5)

 I can close this PR or strip my version of the fix from this PR and just keep the test. 
 Your fix pass the test I added. 

The test I added is heavy, but I feel like we have a gap in coverage here and it's hard to test streaming without doing it e2e.

I can try to write a test calling `engine#call` directly without Rack::Test, we should be able to assert on the stream without it getting buffered.

 What do you think?

**Comment by guilleiguaran** [comment]
> I can try to write a test calling engine#call directly without Rack::Test, we should be able to assert on the stream without it getting buffered.

@JoeDupuis Let's try this approach, the e2e setup seems too heavy for a single test.
