### ISSUE TITLE
Association using unscope: NoMethodError: undefined method `children' for nil:NilClass

### ISSUE THREAD

**Issue by dvandersluis** [rails/rails#38811]
### Steps to reproduce
Have the following models:

```ruby
class Post < ApplicationRecord
  has_many :tags, -> { unscope(:where) }
end

class Tag < ApplicationRecord
  default_scope { where(locale: :en) }
end
```

The following code will crash (even if the `default_scope` is removed):

```ruby
Post.joins(:tags).to_sql
```

### Expected behavior
Join tags to posts without the default scope being applied. Should generate a query something like:

```
SELECT "posts".* FROM "posts" INNER JOIN "tags" ON "tags"."post_id" = "posts"."id"
```

This was the behaviour in Rails 5.2.3.

### Actual behavior
```
Exception: NoMethodError: undefined method `children' for nil:NilClass
--
 0: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:39:in `block in join_constraints'
 1: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:30:in `reverse_each'
 2: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:30:in `with_index'
 3: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency/join_association.rb:30:in `join_constraints'
 4: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:162:in `make_constraints'
 5: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:155:in `block in make_join_constraints'
 6: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:154:in `each'
 7: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:154:in `flat_map'
 8: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:154:in `make_join_constraints'
 9: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/associations/join_dependency.rb:85:in `join_constraints'
10: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1179:in `build_join_query'
11: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1164:in `build_joins'
12: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1044:in `build_arel'
13: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1016:in `arel'
14: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:810:in `block in exec_queries'
15: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:828:in `skip_query_cache_if_necessary'
16: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:797:in `exec_queries'
17: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:615:in `load'
18: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:250:in `records'
19: /Users/daniel/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:245:in `to_ary'
```

### System configuration
**Rails version**:
Works in 5.2.3, broken in 5.2.4.2 and 6.0.2.2.

**Ruby version**:
2.6.2

**Comment by kamipo** [comment]
Can you provide a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by dvandersluis** [comment]
@kamipo Absolutely!

[https://gist.github.com/dvandersluis/86eb48649747c763dd06fb1bc35a4321](https://gist.github.com/dvandersluis/86eb48649747c763dd06fb1bc35a4321)

**Comment by kevinhq** [comment]
@kamipo - Is this already fixed? Just run that test and I confirmed it works.

**Comment by mechanicles** [comment]
I also tested this issue but found that it does work perfectly with Ruby version `2.6.0` and Rails versions `5.2.4.2` and `6.0.2.2`.

It also works fine with recent Ruby version and Rails version.

**Comment by alboyadjian** [comment]
I'm getting the same error after upgrading to 5.2.4.2. Created a reproduction gist based on @kevinhq 's
https://gist.github.com/alboyadjian/189e062cc814b57d8ab1a48e94486d36

**Comment by dvandersluis** [comment]
I tried to track this down and I think it relates to this line: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L479

If `unscope` is just given a symbol (`:where` in this case) the entire key is deleted from `@values`, which seems to mean the join conditions are killed too. Previously (as of 5.2.3), it replaced them with the default values instead, which I think included join conditions.

A workaround I've found is to use the hash form `unscope(where: :foo)`, which is a bit more brittle depending on how often your default scope is being changed but avoids the error.

**Comment by alboyadjian** [comment]
Thanks @dvandersluis. Changing to the hash form fixed the tests that were failing because of this. There don't seem to be any problems with unscope when used inside a scope, just when it's used in an association definition.

**Comment by kevinhq** [comment]
> I'm getting the same error after upgrading to 5.2.4.2. Created a reproduction gist based on @kevinhq 's
> https://gist.github.com/alboyadjian/189e062cc814b57d8ab1a48e94486d36

Confirmed this too.
`Error:
BugTest#test_association_stuff:
NoMethodError: undefined method `children' for nil:NilClass`
