### PR TITLE
undefined method 'to_i' for true in ActiveRecord 8.1+

### LINKED ISSUE #58292: `undefined method 'to_i' for true` in ActiveRecord 8.1+
### Steps to reproduce

**Not database-specific.** Reproduction code is on SQLite with a plain `t.boolean`, but we hit this on MySQL, where `tinyint(1)` maps to `:boolean` via `emulate_booleans`, so any `tinyint(1)` column with a non-null default and an integer `attribute` override breaks. We have small enums saved in these `tinyint(1)` columns.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '8.1.3' # fails
  # gem 'rails', '8.0.5' # passes

  gem 'sqlite3'
end

require 'active_record/railtie'
require 'minitest/autorun'

# This connection will do for database-independent bug reports.
ENV['DATABASE_URL'] = 'sqlite3::memory:'

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = 'secret_key_base'
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :status, default: true # On MySQL a tinyint(1) column holding a small integer maps to :boolean the same way.
  end
end

ActiveRecord::Base.partial_inserts = true # default before Rails 7.0; test 2 needs it

class Post < ActiveRecord::Base
  attribute :status, :integer
end

class BugTest < ActiveSupport::TestCase
  def test_default_is_cast_with_the_overridden_attribute_type
    assert_equal 1, Post.new.status
  end

  def test_non_boolean_values_can_be_written
    assert_equal 2, Post.create!(status: 2).reload.status
  end
end
```

### Expected behavior

`Post.new.status` returns `1` — the schema default, cast by the type the model declared. The test
passes on Rails 7.2 and 8.0:

```
2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

On Rails 8.1.3, reading the attribute raises:

```
  1) Error:
BugTest#test_non_boolean_values_can_be_written:
NoMethodError: undefined method 'to_i' for true
    activemodel-8.1.3/lib/active_model/type/integer.rb:64:in 'ActiveModel::Type::Integer#deserialize'
    activemodel-8.1.3/lib/active_model/attribute.rb:183:in 'ActiveModel::Attribute::FromDatabase#type_cast'
    activemodel-8.1.3/lib/active_model/attribute.rb:51:in 'ActiveModel::Attribute#original_value'
    activemodel-8.1.3/lib/active_model/attribute.rb:49:in 'ActiveModel::Attribute#original_value'
    activemodel-8.1.3/lib/active_model/attribute.rb:170:in 'ActiveModel::Attribute#changed_from_assignment?'
    activemodel-8.1.3/lib/active_model/attribute.rb:67:in 'ActiveModel::Attribute#changed?'
    activemodel-8.1.3/lib/active_model/attribute_mutation_tracker.rb:79:in 'ActiveModel::AttributeMutationTracker#attribute_changed?'
    activemodel-8.1.3/lib/active_model/attribute_mutation_tracker.rb:45:in 'ActiveModel::AttributeMutationTracker#changed?'
    activemodel-8.1.3/lib/active_model/attribute_mutation_tracker.rb:15:in 'block in ActiveModel::AttributeMutationTracker#changed_attribute_names'
    activemodel-8.1.3/lib/active_model/attribute_mutation_tracker.rb:15:in 'Array#select'
    activemodel-8.1.3/lib/active_model/attribute_mutation_tracker.rb:15:in 'ActiveModel::AttributeMutationTracker#changed_attribute_names'
    activerecord-8.1.3/lib/active_record/attribute_methods/dirty.rb:182:in 'ActiveRecord::AttributeMethods::Dirty#changed_attribute_names_to_save'
    activerecord-8.1.3/lib/active_record/attribute_methods/dirty.rb:251:in 'ActiveRecord::AttributeMethods::Dirty#attribute_names_for_partial_inserts'
    activerecord-8.1.3/lib/active_record/attribute_methods/dirty.rb:239:in 'ActiveRecord::AttributeMethods::Dirty#_create_record'
    activerecord-8.1.3/lib/active_record/callbacks.rb:445:in 'block in ActiveRecord::Callbacks#_create_record'
    activesupport-8.1.3/lib/active_support/callbacks.rb:911:in 'ActiveRecord::Base#_run_create_callbacks'
    activerecord-8.1.3/lib/active_record/callbacks.rb:445:in 'ActiveRecord::Callbacks#_create_record'
    activerecord-8.1.3/lib/active_record/timestamp.rb:116:in 'ActiveRecord::Timestamp#_create_record'
    activerecord-8.1.3/lib/active_record/persistence.rb:925:in 'ActiveRecord::Persistence#create_or_update'
    activerecord-8.1.3/lib/active_record/callbacks.rb:441:in 'block in ActiveRecord::Callbacks#create_or_update'
    activesupport-8.1.3/lib/active_support/callbacks.rb:911:in 'ActiveRecord::Base#_run_save_callbacks'
    activerecord-8.1.3/lib/active_record/callbacks.rb:441:in 'ActiveRecord::Callbacks#create_or_update'
    activerecord-8.1.3/lib/active_record/timestamp.rb:127:in 'ActiveRecord::Timestamp#create_or_update'
    activerecord-8.1.3/lib/active_record/persistence.rb:424:in 'ActiveRecord::Persistence#save!'
    activerecord-8.1.3/lib/active_record/validations.rb:54:in 'ActiveRecord::Validations#save!'
    activerecord-8.1.3/lib/active_record/transactions.rb:385:in 'block in ActiveRecord::Transactions#save!'
    activerecord-8.1.3/lib/active_record/transactions.rb:438:in 'block (3 levels) in ActiveRecord::Transactions#with_transaction_returning_status'
    activerecord-8.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:648:in 'block in ActiveRecord::ConnectionAdapters::TransactionManager#within_new_transaction'
    activesupport-8.1.3/lib/active_support/concurrency/null_lock.rb:9:in 'ActiveSupport::Concurrency::NullLock#synchronize'
    activerecord-8.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:645:in 'ActiveRecord::ConnectionAdapters::TransactionManager#within_new_transaction'
    activerecord-8.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:386:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#within_new_transaction'
    activerecord-8.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:378:in 'ActiveRecord::ConnectionAdapters::DatabaseStatements#transaction'
    activerecord-8.1.3/lib/active_record/transactions.rb:434:in 'block (2 levels) in ActiveRecord::Transactions#with_transaction_returning_status'
    activerecord-8.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:485:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_pool_transaction_isolation_level'
    activerecord-8.1.3/lib/active_record/transactions.rb:430:in 'block in ActiveRecord::Transactions#with_transaction_returning_status'
    activerecord-8.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:457:in 'ActiveRecord::ConnectionAdapters::ConnectionPool#with_connection'
    activerecord-8.1.3/lib/active_record/connection_handling.rb:313:in 'ActiveRecord::ConnectionHandling#with_connection'
    activerecord-8.1.3/lib/active_record/transactions.rb:429:in 'ActiveRecord::Transactions#with_transaction_returning_status'
    activerecord-8.1.3/lib/active_record/transactions.rb:385:in 'ActiveRecord::Transactions#save!'
    activerecord-8.1.3/lib/active_record/suppressor.rb:56:in 'ActiveRecord::Suppressor#save!'
    activerecord-8.1.3/lib/active_record/persistence.rb:55:in 'ActiveRecord::Persistence::ClassMethods#create!'
    reproduction.rb:50:in 'BugTest#test_default_non_boolean_values_can_be_written'

  2) Error:
BugTest#test_default_is_cast_with_the_overridden_attribute_type:
NoMethodError: undefined method 'to_i' for true
    activemodel-8.1.3/lib/active_model/type/integer.rb:64:in 'ActiveModel::Type::Integer#deserialize'
    activemodel-8.1.3/lib/active_model/attribute.rb:183:in 'ActiveModel::Attribute::FromDatabase#type_cast'
    activemodel-8.1.3/lib/active_model/attribute.rb:43:in 'ActiveModel::Attribute#value'
    activemodel-8.1.3/lib/active_model/attribute_set.rb:51:in 'ActiveModel::AttributeSet#fetch_value'
    activerecord-8.1.3/lib/active_record/attribute_methods/read.rb:39:in 'ActiveRecord::AttributeMethods::Read#_read_attribute'
    activemodel-8.1.3/lib/active_model/attribute_methods.rb:273:in 'Post::GeneratedAttributeMethods#status'
    reproduction.rb:42:in 'BugTest#test_default_is_cast_with_the_overridden_attribute_type'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skip
```

### System configuration

**Rails version**: 8.1.3

**Ruby version**: 4.0.6 (2026-07-14 revision 03b6d3f889) +PRISM [arm64-darwin25]

### PR DESCRIPTION
**Pull request by nicolasva**
Fixes #58292

### Motivation / Background

Since Rails 8.1, overriding the type of a column that has a default value can raise or silently return the wrong value:

```ruby
create_table :posts do |t|
  t.boolean :status, default: true # tinyint(1) + emulate_booleans on MySQL
end

class Post < ActiveRecord::Base
  attribute :status, :integer
end

Post.new.status # => NoMethodError: undefined method 'to_i' for true
```

I bisected this to 13bc31ef4fa35d70e8cf17e82ac0c25f43a0404c ("Deserialize column defaults", #54556), which made `_default_attributes` deserialize the default *before* any `attribute` override is applied:

```ruby
 columns_hash.transform_values do |column|
-  ActiveModel::Attribute.from_database(column.name, column.default, type_for_column(connection, column))
+  type = type_for_column(connection, column)
+  default = column.default
+  default = type.deserialize(default) unless default.nil?
+  ActiveModel::Attribute.from_database(column.name, default, type)
 end
```

On current `main` the eager deserialization has moved one step further upstream, into `Column#initialize`, so `column.default` itself is already `true`.

`attribute :status, :integer` then swaps the type through `ActiveModel::Attribute#with_type`, which keeps `value_before_type_cast` as is and only replaces the type. The attribute therefore ends up calling `ActiveModel::Type::Integer#deserialize(true)` → `true.to_i` → `NoMethodError`. Before the regression `value_before_type_cast` was still the raw `"1"`, and `Integer#deserialize("1")` returned `1`.

| Revision | `column.default` | `_default_attributes["status"].value_before_type_cast` |
| --- | --- | --- |
| `13bc31ef~1` | `"1"` | `"1"` |
| `13bc31ef` | `"1"` | `true` |
| `main` | `true` | `true` |

This is not MySQL or boolean specific, as the reporter noted: any column whose column type deserializes the default into something the overriding type cannot handle is affected. Some combinations do not even raise, they silently change the default (`attribute :status, :string` returns `"true"` instead of `"1"`), and a custom type no longer receives the raw database value in `#deserialize`, which breaks its documented contract.

### Detail

The fix keeps the deserialized default (it is what made #54556 fast) but also keeps the value the database reported, so that an overriding type can deserialize it again from the raw value.

**`ActiveRecord::ConnectionAdapters::Column`**

* Keeps the raw default in a new `#default_before_type_cast`. `#default` is unchanged and still returns the deserialized default.
* `#default_before_type_cast` falls back to `@default` when the ivar is missing or `nil`, so columns restored from a schema cache dumped by an older version (YAML `init_with` or Marshal) keep working.
* The raw default is included in `==`, `hash`, `deduplicated`, `init_with` and `encode_with`.

**`ActiveModel::Attribute::FromDatabaseDefault`** (new, private, built via `Attribute.from_database_default`)

* Holds the *raw* default and deserializes lazily, so `#with_type` can re-deserialize from the raw value instead of type casting an already deserialized value.
* `#value_before_type_cast` returns the deserialized value, so `*_before_type_cast` keeps returning what reading the column back from the database returns — except for mutable types, which stay serialized so mutations of the shared default cannot leak from one record to the next.
* `#original_value` deserializes again rather than reusing `#value`, so in place mutations are not reflected in the original value.
* `#with_type` falls back to `with_value_from_user(value)` when the value was mutated in place, so mutations survive an override.
* `#forgetting_assignment` restores the raw default, and `init_with`/`encode_with` round trip it through YAML.

**`ActiveRecord::Attributes#_default_attributes`**

* Builds defaults with `Attribute.from_database_default(column.name, column.default_before_type_cast, type_for_column(column))`. This covers `enum` too, since it overrides the type of the column it is declared on.

**Callers that deserialize the default themselves** now use `#default_before_type_cast` instead of `#default`, which was being deserialized twice: `SchemaDumper#schema_default` and the SQLite3 `copy_table`.

**SQLite3 adapter**

* SQLite reports boolean defaults as the literals `TRUE`/`FALSE`. `Type::Boolean` deserializes both fine, but an overriding type would receive `"TRUE"`, which is not a value any other type can make sense of. `new_column_from_field` now normalizes them to `"1"`/`"0"` for boolean columns, which is what the other adapters report and what the column type already deserializes identically.

### Additional information

Tests:

* `activemodel/test/cases/attribute_test.rb` covers `FromDatabaseDefault` directly: casting from the raw value, mutable values staying serialized, `with_type` re-casting from the raw value, in place mutations surviving `with_type`, and the YAML round trip.
* `activerecord/test/cases/defaults_test.rb` adds `DefaultsWithOverriddenAttributeTypeTest`, which covers the reported case and the variants raised in the issue thread: `:integer`, `:string`, `:datetime` and custom type overrides, a custom type receiving the raw default, `enum` on a column with a default, `attribute ... default:` still winning, partial inserts, round tripping written values, columns whose type is *not* overridden being unaffected, and the schema cache fallbacks.

Alternatives considered:

* #58293 only normalizes booleans, and the issue is not boolean specific (a `:date` column overridden as `:datetime` is affected too, while `:datetime` is not, because `Type::DateTime` is `mutable?`).
* Reverting the eager deserialization would reintroduce the slowdown #54556 fixed, and would no longer be enough on `main` since `Column#default` is now deserialized on construction.
* Deserializing the default lazily with the final type only, without keeping the raw value, would break `Column#default`, which is public API and is expected to return a deserialized value.

Ping @joklek-vinted, who reported the issue and had a patch in the works, and @Edilbek.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

File: activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb [hunk 1]
```diff
@@ -602,6 +602,14 @@ def extract_value_from_default(default)
           end
         end
 
+        def normalize_boolean_default(default)
+          case default
+          when "TRUE" then "1"
+          when "FALSE" then "0"
+          else default
+          end
+        end
```
Comment (byroot) [inline activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:611]: This is a pretty big smell IMO.

The original issue was about MySQL tinyint, which indeed are ambiguous because they can be integers or booleans.

But here the database very clearly gave us a boolean, if you want to change the type of the attribute in your model, it seems logical to me that you'd also have to provide a new default.

```ruby
attribute :status, :integer, default: 1
```

File: activerecord/lib/active_record/connection_adapters/column.rb [hunk 2]
```diff
@@ -32,6 +35,19 @@ def has_default?
...
+      # the default themselves, in particular with another type, must use this
+      # rather than #default, which may already be deserialized.
+      def default_before_type_cast
+        if !defined?(@default_before_type_cast) || @default_before_type_cast.nil?
+          # Columns restored from a schema cache dumped before this attribute
+          # existed only have the (possibly deserialized) default.
+          @default
+        else
+          @default_before_type_cast
+        end
```
Comment (byroot) [inline activerecord/lib/active_record/connection_adapters/column.rb:48]:
```suggestion
        if defined?(@default_before_type_cast)
          @default_before_type_cast
        else
          # Columns restored from a schema cache dumped before this attribute
          # existed only have the (possibly deserialized) default.
          @default
        end
```

File: activemodel/lib/active_model/attribute.rb [hunk 3]
```diff
@@ -202,6 +206,78 @@ def _original_value_for_database
...
 
+      # Column defaults are read from the schema as raw database values, and are
+      # deserialized so that +*_before_type_cast+ returns the same thing as
+      # reading the column back from the database.
+      #
+      # The raw value is kept around because a model can override the type of a
+      # column with ActiveModel::AttributeRegistration::ClassMethods#attribute.
+      # When that happens the default has to be deserialized again, with the
+      # overridden type rather than with the type of the column.
+      class FromDatabaseDefault < FromDatabase # :nodoc:
```
Comment (byroot) [inline activemodel/lib/active_model/attribute.rb:217]: I'm not a big fan of adding yet another `Attribute` subclass.

It might make more sense to have that logic in `def _default_attributes`.

**Comment by byroot** [comment]
I spent quite a while digging in this, and the more it goes the more I think the only proper way out of this is to essentially revert https://github.com/rails/rails/pull/54585

It sucks, and adds a bunch of complexity left and right, but is better than that alternative -_-.
