### PR TITLE
config_for accepts root shared as an array

### LINKED ISSUE #42698: config_for raises an error for arrays when there's only a shared key
### Steps to reproduce

I'm using a config files to blacklist some jwt tokens like this:

```yaml
# config/jwt_blacklist.yml
---
shared:
  - token1
  - token2
```

In `application.rb`

```ruby
config.jwt_whitelist = config_for(:jwt_whitelist)
```

### Expected behavior

```ruby
Rails.configuration.jwt_whitelist
=> ["token1", "token2"]
```

### Actual behavior

```ruby
railties-6.1.4/lib/rails/application.rb:252:in `config_for': undefined method `deep_merge' for ["token1", "token2"]:Array (NoMethodError)
```

It worked on rails 6.1.3.2, I think it has been introduced with https://github.com/rails/rails/commit/3fe0ab52dff018ed940ad45885c9d90208eb3cac (related issue: https://github.com/rails/rails/issues/42037 )

Thanks to [this issue](https://github.com/rails/rails/issues/37800) I think it should accepts arrays.

Moreover, I tried the following:

```yaml
production: []
test: []
development: []
shared:
  - token1
  - token2
```

And it returns an empty array:

```ruby
Rails.configuration.jwt_whitelist
=> []
```

Not sure if it's a normal behaviour too.

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.7.2p137

### PR DESCRIPTION
**Pull request by skelz0r**
### Summary

Fix a bug when a configuration has only a shared root array key for `config_for`.

Closes #42698

### CODE REVIEW

File: railties/lib/rails/application.rb [hunk 1]
```diff
@@ -247,9 +247,11 @@ def config_for(name, env: Rails.env)
         config, shared = all_configs[env.to_sym], all_configs[:shared]
 
         if shared
-          config = {} if config.nil?
-          if config.is_a?(Hash)
+          config = {} if config.nil? && shared.is_a?(Hash)
+          if config.is_a?(Hash) && shared.is_a?(Hash)
             config = shared.deep_merge(config)
+          elsif config.nil? && shared.is_a?(Array)
```
Comment (byroot) [inline railties/lib/rails/application.rb:253]: I don't think you need the `shared.is_a?(Array)`. If `config` is `nil`, then we get the entire `shared` regardless of it's type.

Comment (skelz0r) [reply railties/lib/rails/application.rb:253]: Indeed

**Comment by byroot** [comment]
Also please squash your commits into one. Once the `is_a?(Array)` thing is solved, it's good to me.

**Comment by skelz0r** [comment]
> Also please squash your commits into one. Once the `is_a?(Array)` thing is solved, it's good to me.

Done

**Comment by byroot** [comment]
Urk, CI is mostly broken because the yarn registry is down, and I can't retry the build :/

Looks good to me though, so I'll merge.
