### ISSUE TITLE
config_for returns Hash instead of OrderedOptions for empty environment keys

### ISSUE THREAD

**Issue by jasonkarns** [rails/rails#42037]
### Steps to reproduce

Given a yaml file: config/sample.yml

```yml
shared:
  foo: "default value"

development:
  foo: "dev value"

test:

production:
  foo: "prod value"
```

When: `Rails.application.config_for(:sample, env: :test).foo`

### Expected behavior

I expected to get `"default value"` as merged from `shared`.

(I would expect the returned configuration to be of type `ActiveSupport::OrderedOptions`)

### Actual behavior

Instead, I get `NoMethodError: undefined method 'foo' for {:foo=>"default value"}:Hash` because the returned configuration object is of type `Hash` instead of `OrderedOptions`.

Temporary workaround: explicitly forcing empty environment keys to be empty hashes instead of nil ensures they are wrapped as OrderedOptions correctly. ie `test: {}` in the yaml file.

I believe this behavior was introduced by https://github.com/rails/rails/pull/37850. At this point: https://github.com/rails/rails/blob/d927db7eec984a980e5533dc307164e24c137690/railties/lib/rails/application.rb#L249-L253 if the environment key is `nil`, it fails the `is_a? Hash` check, and quickly returns `config || shared`. However, at that point, the `shared` key is a `Hash` instead of `OrderedOptions`, so the final return value is a `Hash`.
### System configuration
**Rails version**: 6.1.3.1
**Ruby version**: 2.7.3p183

**Comment by byroot** [comment]
Thanks for the clear bug report, I think I have a fix ready here: https://github.com/rails/rails/pull/42038

I'll merge and backport it to 6.1 once CI passes.
