### ISSUE TITLE
Exception Webpacker::Manifest::MissingEntryError raised in Articles#index when following along with the getting started guide

### ISSUE THREAD

**Issue by brianewell** [rails/rails#41970]
Getting a Webpacker::Manifest::MissingEntryError exception when attempting to follow the [getting started](https://guides.rubyonrails.org/getting_started.html) guide under Illumos/SmartOS.

### Steps to reproduce

Follow the steps outlined in the getting started guide, and them some, specifically:

Spun up a new instance (base-64-lts 20.4.0)

Installed/updated the documented rails prerequisites:

```
# pkgin -y install ruby27 sqlite3 nodejs yarn
```

Additionally installed undocumented prerequisites (required for compiling native extensions):

```
# pkgin -y install gcc9 gmake
```

Installed rails according to documentation:

```
# gem install rails
```

Created a new blog according to documentation:

```
$ rails new blog
```

First hint of potential trouble occurred when it got to the `webpacker:install` section:

```
info fsevents@2.3.2: The platform "sunos" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "sunos" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/2] ⠠ waiting...
error /root/blog/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /root/blog/node_modules/node-sass
Output:
Building: /opt/local/bin/node /root/blog/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/opt/local/bin/node',
gyp verb cli   '/root/blog/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.16.0 | sunos | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/root/blog/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/root/blog/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/root/blog/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /root/blog/node_modules/which/which.js:89:16
gyp verb `which` failed     at /root/blog/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /root/blog/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/root/blog/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/root/blog/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/root/blog/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /root/blog/node_modules/which/which.js:89:16
gyp verb `which` failed     at /root/blog/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /root/blog/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /opt/local/bin/python
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /opt/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System SunOS 5.11
gyp ERR! command "/opt/local/bin/node" "/root/blog/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/blog/node_modules/node-sass
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

Installing dev server for live reloading
         run  yarn add --dev webpack-dev-server from "."
yarn add v1.22.10
info No lockfile found.
```

Start the development server:

```
# cd blog
# rails server
```

Open a new terminal and generate the ArticleController as per the documentation:

```
# ./bin/rails generate controller Articles index --skip-routes
```

Set `config/routes.rb` as per the documentation:

```
Rails.application.routes.draw do
  root "articles#index"

  get "/articles", to: "articles#index"
end
```

Test in the browser and enjoy an unexpected exception:
![image_2021-04-13_222305](https://user-images.githubusercontent.com/469097/114658530-d2331780-9ca6-11eb-8927-922e2afcfb4e.png)

The following was returned from the server's stdout:

```
Started GET "/" for X.X.X.X at 2021-04-14 05:21:24 +0000
Cannot render console from X.X.X.X! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by ArticlesController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering articles/index.html.erb within layouts/application
  Rendered articles/index.html.erb within layouts/application (Duration: 0.7ms | Allocations: 103)
[Webpacker] Compiling...
[Webpacker] Compilation failed:
yarn run v1.22.10
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


error Command "webpack" not found.

  Rendered layout layouts/application.html.erb (Duration: 3122.5ms | Allocations: 16953)
Completed 500 Internal Server Error in 3130ms (Allocations: 18018)



ActionView::Template::Error (Webpacker can't find application.js in /root/blog/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
     7:     <%= csp_meta_tag %>
     8:
     9:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    10:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    11:   </head>
    12:
    13:   <body>

app/views/layouts/application.html.erb:10
```

At this point, I'm unsure of how to proceed.

### Expected behavior

Was expecting to be able to proceed to the next step in the guide.

### Actual behavior

Was prevented from proceeding further by previously described exception.

### System configuration

**Rails version**: rails-6.1.3.1

**Ruby version**: ruby-2.7.2

**Sqlite3 version**: 3.34.0

**Node version**: 14.16.0

**Yarn version**: 1.22.10

**SmartOS instance version**: base-64-lts 20.4.0

### Additional Information

I'm more than happy to provide compute time on one or more SmartOS instances to assist in resolving this issue.

**Comment by brianewell** [comment]
I've since followed up with installing python2.7 and re-running `rails webpacker:install` before restarting the development server:

```
# pkgin -y py27
...
# rails webpacker:install
...
# rails server
```

Everything appears to be working properly now.  Python 2 was a surprising dependency.

**Comment by juliusdelta** [comment]
Looks like python is required by [node-gyp](https://github.com/nodejs/node-gyp).

**Comment by brianewell** [comment]
According to their documentation, node-gyp works with Python v3.6-3.9.  SmartOS base64-lts-20.4.0 already comes with Python 3.8.6, but wouldn't work until after I had installed Python 2.7.18.

**Comment by softwaregravy** [comment]
I think I am seeing the same issue. Here's me reproducing it.

I'm using OSX and RVM

```
# mkdir Blog
... create .ruby-gemset an .ruby-version
# cd Blog
ruby-2.7.2 - #gemset created /Users/johnhinnegan/.rvm/gems/ruby-2.7.2@Blog
ruby-2.7.2 - #generating Blog wrappers - please wait
# ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
# node --version
v15.12.0
# yarn --version
1.22.10
# gem install rails
...
# rails --version
Rails 6.1.3.1
# rails new ./ --database=postgresql --skip-git --skip-test
...
# rake db:create
...
# rails server
...
// all good, Yay, You're on Rails screen comes up just fine!
# rails g controller Articles index
# rails server
```

So now I visit `localhost:3000/articles/index` and I get an error

```
Started GET "/articles/index" for ::1 at 2021-04-18 07:26:33 -0400
Processing by ArticlesController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering articles/index.html.erb within layouts/application
  Rendered articles/index.html.erb within layouts/application (Duration: 0.3ms | Allocations: 104)
[Webpacker] Compiling...
[Webpacker] Compilation failed:
yarn run v1.22.10
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


error Command "webpack" not found.

  Rendered layout layouts/application.html.erb (Duration: 739.8ms | Allocations: 17577)
Completed 500 Internal Server Error in 742ms (ActiveRecord: 0.0ms | Allocations: 18713)



ActionView::Template::Error (Webpacker can't find application.js in /Users/johnhinnegan/workspace/Blog/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
     7:     <%= csp_meta_tag %>
     8:
     9:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    10:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    11:   </head>
    12:
    13:   <body>

app/views/layouts/application.html.erb:10
```

First attempt to fix

```
# rails webpacker:install
...
gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/johnhinnegan/workspace/Blog/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/15.12.0/bin/node" "/Users/johnhinnegan/workspace/Blog/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/johnhinnegan/workspace/Blog/node_modules/node-sass
gyp ERR! node -v v15.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

Installing dev server for live reloading
         run  yarn add --dev webpack-dev-server from "."
yarn add v1.22.10
...
Webpacker successfully installed
```

I did get an error. Worth noting, I do have the lastest XCode and CommandLineTools installed. 

``` 
# rails server
```

same error on loading

**Comment by johnpitchko** [comment]
Experiencing the exact same issue.

Using rails v6.1.4.1. Doing a brand new install following the Getting Started article in the [guide](https://guides.rubyonrails.org/getting_started.html).

Followed the steps that @softwaregravy suggested but no joy.

Using python 3.9.5 so *shouldn't* be related to the issue that @brianewell encountered.

**Comment by zhylmzr** [comment]
After initializing the project according to the official [guide](https://guides.rubyonrails.org/getting_started.html), I found that the `coa` and `@rails/webpacker` packages were not installed, and the problem was solved after manual installation

```bash
yarn add coa @rails/webpacker
```
