### ISSUE TITLE
undefined method `expr' for nil:NilClass when try to eager_load a record with sql query association for a model

### ISSUE THREAD

**Issue by asnad** [rails/rails#34456]
### Steps to reproduce
Create a association with sql query in my case I have models.

```ruby
class Machine < ApplicationRecord
  has_many :machine_part_changes
  has_one :current_identifier_part_change, -> {
    sql = <<-SQL
      INNER JOIN "machine_parts"
      ON "machine_parts"."id" = "machine_part_changes"."machine_part_id"
      AND "machine_parts"."is_machine_external_identifier" = 1
    SQL
    installed.joins(sql)
    },
    class_name: 'MachinePartChange'
end

class MachinePartChange < ApplicationRecord
  belongs_to :machine_part
  belongs_to :machine, touch: true
end
```
there is a similar [issue](https://github.com/rails/rails/issues/32671)
### Expected behavior
It was working with `rails 4.2` but I upgraded to `5.2` I'm getting error on eager loading the association 
```
Failure/Error: machine = Machine.eager_load(:current_identifier_part_change).find(create_machine.id)
 
 NoMethodError:
   undefined method `expr' for nil:NilClass
```
### Actual behavior
I could pass the test or I was able to eager load such association

### System configuration
**Rails version**:
5.2.1
**Ruby version**:
2.5.0

**Comment by asnad** [comment]
Please reply on this

**Comment by rafaelfranca** [comment]
When someone have time they will comment on this. Until there, if you were in a hurry, I'd recommend you to investigate yourself. You can start by creating a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb and trying to fix yourself.

**Comment by davidtaylorhq** [comment]
I ran into this issue recently. It seems to be exactly the same as #32671, which has been automatically marked stale. The test case in #32671 is still failing against the master branch. For reference, here is another failing test case I used to reproduce the issue, following the up-to-date bug report template. 

@asnad described `eager_load` failing. The same bug also seems to affect `.includes(:blah).pluck`, and `.joins(:blah)`.

``` ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end

  create_table :likes, force: true do |t|
    t.integer :comment_id
    t.boolean :verified
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  has_many :verified_liked_comments,
              -> {
                joins("
                  LEFT JOIN likes on likes.comment_id = comments.id")
                  .where("likes.verified": true)
              },
    class_name: 'Comment'
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :likes
end

class Like < ActiveRecord::Base
  belongs_to :comment
end

class BugTest < Minitest::Test
  def setup
    post = Post.create!
    post.comments << comment = Comment.create!
    comment.likes << Like.create!(verified: true)
  end

  def test_should_be_joinable
    ids = Post.joins(:verified_liked_comments).map(&:id)
    assert_equal [1], ids

    ids = Post.includes(:verified_liked_comments).pluck(:id)
    assert_equal [1], ids

    ids = Post.eager_load(:verified_liked_comments).map(&:id)
    assert_equal [1], ids
  end

end
```
Fails with
```
Error:
BugTest#test_should_be_joinable:
NoMethodError: undefined method `expr' for nil:NilClass
```
