### ISSUE TITLE
Can't drop or reset db after upgrading to 6.1.0

### ISSUE THREAD

**Issue by katelovescode** [rails/rails#41047]
### Steps to reproduce

```
╰─$ bundle exec rails db:reset
undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007f93fad34ce0>
Did you mean?  configuration_hash
Couldn't drop database 'development'
rails aborted!
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007f93fad34ce0>
Did you mean?  configuration_hash
bin/rails:10:in `<top (required)>'
bin/spring:15:in `require'
bin/spring:15:in `<top (required)>'

Caused by:
NoMethodError: private method `configuration_hash' called for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007f93fad34ce0>
bin/rails:10:in `<top (required)>'
bin/spring:15:in `require'
bin/spring:15:in `<top (required)>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
```

### Expected behavior
The db should drop and recreate

### Actual behavior
This command and `db:drop` both fail

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.6.6

**Comment by eugeneius** [comment]
I couldn't reproduce this in a new Rails 6.1.0 app using PostgreSQL. Can you run `bundle exec rails db:reset --trace` and post the full backtrace?

**Comment by katelovescode** [comment]
```
$ bundle exec rails db:reset --trace
** Invoke db:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:drop
** Invoke db:drop:_unsafe (first_time)
** Invoke db:load_config 
** Execute db:drop:_unsafe
undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007ff34a6afe60>
Did you mean?  configuration_hash
Couldn't drop database 'development'
rails aborted!
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007ff34a6afe60>
Did you mean?  configuration_hash
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/pgreset-0.1.1/lib/pgreset.rb:14:in `drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:199:in `drop'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `block in drop_current'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/tasks/database_tasks.rb:214:in `drop_current'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activerecord-6.1.1/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/command.rb:52:in `invoke'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
/Users/user/Projects/project/bin/rails:10:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/user/.rvm/gems/ruby-2.6.6@project/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/user/Projects/project/bin/spring:15:in `require'
/Users/user/Projects/project/bin/spring:15:in `<top (required)>'
bin/rails:4:in `load'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop:_unsafe
```

**Comment by katelovescode** [comment]
Ahh never mind, looks like it's logged in pgreset: https://github.com/dafalcon/pgreset/issues/2  I just got an upgrade PR from dependabot for that library.  Thanks for looking, though, @eugeneius
