### PR TITLE
Allow nil params on controller HTTP test methods

### PR DESCRIPTION
**Pull request by r7kamura**
## Summary

The following controller test code works fine on Rails 5.0.7:

```rb
get :index, params: nil
```

but on Rails 5.1 or the later versions, NoMethodError is raised with the following error message:

```
NoMethodError: undefined method `symbolize_keys' for nil:NilClass
```

I think this behavior was changed at https://github.com/rails/rails/commit/98b8309569a326910a723f521911e54994b112fb.

## Other Information

Here is an example code to reproduce this error:

```rb
# controller_params_test.rb
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  # gem 'rails', '5.0.7'
  gem 'rails', '5.1.6'
end

require 'action_controller/railtie'
require 'minitest/autorun'
require 'rails/test_help'

class TestApp < Rails::Application
  secrets.secret_key_base = 'secret_key_base'

  ::Rails.logger = ::Logger.new(nil)

  routes.draw do
    get '/' => 'test#index'
  end
end

class TestController < ActionController::Base
  include ::Rails.application.routes.url_helpers

  def index
    head(200)
  end
end

class ControllerParamsTest < ActionController::TestCase
  def setup
    super
    @controller = ::TestController.new
  end

  def test_params_with_empty_hash
    get :index, params: {}
    assert_equal 200, response.status
  end

  def test_params_with_nil
    get :index, params: nil
    assert_equal 200, response.status
  end
end
```

### Expected

```
$ ruby controller_params_test.rb
Run options: --seed 8188

# Running:

..

Finished in 0.069279s, 28.8688 runs/s, 28.8688 assertions/s.
2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

### Actual

```
$ ruby controller_params_test.rb
Run options: --seed 46396

# Running:

.E

Error:
ControllerParamsTest#test_params_with_nil:
NoMethodError: undefined method `symbolize_keys' for nil:NilClass



bin/rails test controller_params_test.rb:43



Finished in 0.065820s, 30.3859 runs/s, 15.1930 assertions/s.
2 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

### FYI

ActionDispatch::IntegrationTest can take nil params like this:

```rb
class RequestParamsTest < ActionDispatch::IntegrationTest
  def test_params_with_nil
    get '/', params: nil
    assert_equal 200, response.status
  end
end
```

### CODE REVIEW

**Comment by kaspth** [comment]
Was this ever documented to be supported? Seems weird to pass in nil directly.

**Comment by r7kamura** [comment]
> Was this ever documented to be supported? Seems weird to pass in nil directly.

This is a good point ☝️ 

Before creating this pull request, I read this comment line and interpreted it as `nil` can be directly passed as `params`:

https://github.com/rails/rails/blob/2f6456cbe1da73c13b37e23720caa8716df85e78/actionpack/lib/action_controller/test_case.rb#L377

**Comment by kaspth** [comment]
It sounds like it's a leftover from when we had positional parameters `get :index, nil, { 'CONTENT_TYPE' => '…' }`. Ref: https://github.com/rails/rails/commit/baf14ae513337cb185acf865e93dfc48f3aabf6a#diff-600d5368b55e46ed961abb4295977ac3L498

Except there's also the `:body` option, which requires that `:params` can be nil.
