### ISSUE TITLE
after upgrading from 5.1.4 to 5.1.5: undefined method `arel' for nil:NilClass

### ISSUE THREAD

**Issue by jarkelen** [rails/rails#32356]
My application is running on Rails 5.1.4 fine.
When I upgrade to 5.1.5 I get this error: `undefined method `arel' for nil:NilClass' on this line of code: `unless testruns.blank?`. When I downgrade Rails back to 5.1.4 everything is fine again.

I am not using the Arel gem in my Gemfile, so what is causing this error?

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Frexuz** [comment]
Same here going to 5.1.5.

Controller
```
  def index
    # Works
    @conversations = current_user ? current_user.conversations.joins(:property, :messages) : [] 

   # Adding `includes` break
    @conversations = current_user ? current_user.conversations.joins(:property, :messages).includes(:property, :messages) : []
  end
```

Conversation
```
class Conversation < ApplicationRecord
  belongs_to :property, counter_cache: true
  has_many :messages, dependent: :destroy
  scope :active_conversations, -> { where('messages_count > 0') }
end
```

User
```
class User < ApplicationRecord
  has_many :conversations

  def conversations
    Conversations::ActiveQuery.new.results(id)
  end
end
```

Query
```
module Conversations

  class ActiveQuery

    def results(user_id)
      Conversation.where('conversations.user_id = :user_id OR other_user_id = :user_id', user_id: user_id)
                  .active_conversations
                  .order(created_at: :desc)
    end

  end

end
```

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by rafaelfranca** [comment]
Oh, just saw that you are overriding the association reader to return something different. I'd not be surprised that is broken, that is not something we support. If you can reproduce that without doing that we can consider that a bug.

**Comment by Frexuz** [comment]
I dont see how that's any different, since it just returns an active record query.
It's the same as doing:
(also throws the same error)
```
Conversation
  .where('conversations.user_id = :user_id OR other_user_id = :user_id', user_id: current_user.id)
  .active_conversations
  .order(created_at: :desc)
  .joins(:property, :messages)
  .includes(:property, :messages)
```

But i'll try creating a template..

**Comment by Frexuz** [comment]
1. Created bug_report_template. No bug there.
2. Started ripping out all gems, adding them back slowly.
3. Running `bundle` after every step
4. Restart server and theck the bug again.

5. All gems are back
6. No bug anymore
7. Profit

Not sure how this works :P I ended up with several new version of all kinds of gems, but I don't see that any of them have anything to do with active-record or json serialization.

So no bug for me anymore :P

**Comment by eileencodes** [comment]
Thanks for the update @Frexuz! Sounds like there isn't a bug here? I'll close for now, please reopen/let me know if you see it again and have more information.

**Comment by trevororeilly** [comment]
I ran into this as well and was able to fix it by updating [Bullet](https://github.com/flyerhzm/bullet) to 5.7.5.

**Comment by patleb** [comment]
Actually, this isn't fixed. @jarkelen, the one who opened the ticket, didn't have the same issue as @Frexuz. On Rails 5.1.4, when eager_load is used and there are no record associated, `ActiveRecord::RecordNotFound` is raised. Since Rails 5.1.5, Arel builds an object with an id to nil if the record isn't found instead of raising, but one way to make it work is to use `includes` instead of `eager_load` and I'm guessing that's what @jarkelen did since he didn't comment back.

**Comment by patleb** [comment]
Finally, I've digged more into what the bug was on my side and it turns out that it's related to the gem [rails_select_on_includes](https://github.com/alekseyl/rails_select_on_includes) which is used to address this [issue](https://github.com/rails/rails/issues/15185). So, my previous comment was actually wrong, sorry for that.
