### ISSUE TITLE
Arel union on active record relations results in unbound value for polymorphic type

### ISSUE THREAD

**Issue by sauberia** [rails/rails#23694]
Something that worked as (I) expected in Rails 4.1 no longer works in Rails 4.2.5 or 5.0.0.beta2.

```ruby
ActiveRecord::Schema.define do

  create_table :books, force: true do |t|
  end

  create_table :products, force: true do |t|
    t.integer :sellable_id
    t.string  :sellable_type
  end

end

class Book < ActiveRecord::Base
  has_one :product, as: :sellable
end

class Product < ActiveRecord::Base
  belongs_to :sellable, polymorphic: true
end


class BugTest < Minitest::Test

  def test_union

    relation_one = Book.joins(:product)
    relation_two = Book.joins(:product)
    union        = relation_one.union(relation_two)

    expected_sql = %q("products"."sellable_type" = 'Book')

    assert_includes(relation_one.to_sql, expected_sql) # Pass
    assert_includes(relation_two.to_sql, expected_sql) # Pass
    assert_includes(union.to_sql, expected_sql) # Failure

  end

end

```

The first two assertions are true - the sellable_type in the relation is set to Book. In the union however, sellable_type is set to a question mark.

I gather this is the same [issue](https://github.com/rails/rails/issues/20280) that @matthewd commented that:
> Raw Arel (union) + AR::Relation bind values = :worried:, as you have found.

But I'm hoping that my simple, contrived example may help solve it.

---

Bug report template:

https://gist.github.com/sauberia/31247ea5aaaef9ea

**Comment by rafaelfranca** [comment]
Arel is private API of Rails we don't guarantee that its usages in application with Active Record will work.
