### PR TITLE
Fix `link_to` with a model passed as an argument twice

### LINKED ISSUE #43913: in rails 7 link_to @article, @article not working as in rails 6
### Steps to reproduce

```ruby
link_to @article  # => <a href="/articles/1">article name</a>
link_to @article, '\pippo' # => <a href="\pippo">article name</a>
link_to @article.to_s, @article # => <a href="/articles/1">article name</a>
link_to @article, article_path(article) # => <a href="/articles/1">article name</a>

link_to @article, @article # raise undefined method `empty?' for #<Article id: 1,

```

### Expected behavior
```ruby
link_to @article, @article # => <a href="/articles/1">article name</a>
```
This form of link_to was ok in rails 6. 
In rails 7 no more. 

The documentation in ActionView 

> More concise yet, when +name+ is an Active Record model that defines a
> +to_s+ method returning a default value or a model instance attribute

propose only the `link_to @article` version but on rails 6 also `link_to @article, @article` was working.
I have a lot of code like this and maby many like me.

### Actual behavior
```ruby
link_to @article, @article # raise undefined method `empty?' for #<Article id: 1,
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

### PR DESCRIPTION
**Pull request by ghiculescu**
Fixes https://github.com/rails/rails/issues/43913 which found a regression in https://github.com/rails/rails/pull/42234

### CODE REVIEW

File: actionview/lib/action_view/helpers/url_helper.rb [hunk 1]
```diff
@@ -3,6 +3,7 @@
 require "active_support/core_ext/array/access"
 require "active_support/core_ext/hash/keys"
 require "active_support/core_ext/string/output_safety"
+require "active_support/core_ext/object/blank"
```
Comment (jonathanhefner) [inline actionview/lib/action_view/helpers/url_helper.rb:6]: Rails automatically includes `active_support/core_ext/object/blank` and a [handful of other Active Support core extensions](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/rails.rb), so no need to require here.

File: actionview/lib/action_view/helpers/url_helper.rb [hunk 2]
```diff
@@ -743,7 +744,7 @@ def convert_options_to_data_attributes(options, html_options)
         end
 
         def url_target(name, options)
-          if name.respond_to?(:model_name) && options.empty?
+          if name.respond_to?(:model_name) && options.blank?
```
Comment (jonathanhefner) [inline actionview/lib/action_view/helpers/url_helper.rb:747]: Is this change just relying on the fact that `options` will always implement `blank?` (as opposed to `empty?`) regardless of whether it is a Hash or model instance?  If so, it might be more clear to check for what we're really interested in:

```suggestion
          if name.respond_to?(:model_name) && options.is_a?(Hash) && options.empty?
```

Or just:

```suggestion
          if name.respond_to?(:model_name) && options == {}
```

**Comment by jonathanhefner** [comment]
I think the build failures can be solved by rebasing (specifically from 0afa65723a061d247d4a599398056030b10f982a).

File: actionview/lib/action_view/helpers/url_helper.rb (hunk 2 above)
Comment (ghiculescu) [reply actionview/lib/action_view/helpers/url_helper.rb:747]: Yeah, that's right. I suppose this is a better way to do it.

Comment (ghiculescu) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: I'm not sure we should even be changing the type of `options` actually... if it's blank, let it be blank.

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: > I'm not sure we should even be changing the type of `options` actually

I'm not sure what you mean.  We wouldn't be changing the type of `options`; rather, we would be checking whether `options` can be safely ignored (i.e. it is an empty Hash).  Unless I am misunderstanding the code?

Comment (ghiculescu) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: I was referring to https://github.com/rails/rails/blob/39d22f9bf263f08e605c7da479553d6564d11502/actionview/lib/action_view/helpers/url_helper.rb#L211

There's no reason for this line (with my `blank?`) change. The only other place that `options` is referred to is used is https://github.com/rails/rails/blob/39d22f9bf263f08e605c7da479553d6564d11502/actionview/lib/action_view/helpers/url_helper.rb#L753 which already checks for its type (and it would be the same outcome if it were nil, or an empty hash).

So I think it is better to just remove the `||=` line.

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: > There's no reason for this line (with my `blank?`) change. The only other place that `options` is referred to is used is ...

I feel like relying on this is a bit fragile.  `link_to_remote_options?` is already one step removed from `options ||= {}` via `convert_options_to_data_attributes`:

https://github.com/rails/rails/blob/39d22f9bf263f08e605c7da479553d6564d11502/actionview/lib/action_view/helpers/url_helper.rb#L211-L215

The code in either `convert_options_to_data_attributes` or `link_to_remote_options?` could change.  `options ||= {}` ensures that neither `convert_options_to_data_attributes` nor `link_to_remote_options?` nor any code they call (either now or in the future) needs to check for `nil`.

Comment (ghiculescu) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: Yeahh, I get that what you're saying. I'm not as worried because the test coverage is quite good.

To the original point, it feels wrong to do `options.is_a?(Hash) && options.empty?`, because if you pass anything except a hash for `options`, the `url_for(name)` code path will be called. And thus your `options` will be ignored silently.

It is better IMO to only call `url_for(name)` if there's *nothing* passed for `options` (hence `options.blank?)`, and in all other cases, delegate to `url_for(options)`. Which will then raise if `options` is not valid.

Comment (jonathanhefner) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: > it feels wrong to do `options.is_a?(Hash) && options.empty?`, because if you pass anything except a hash for `options`, the `url_for(name)` code path will be called. And thus your `options` will be ignored silently.

It is the opposite, no?

Using `options.is_a?(Hash) && options.empty?`, only empty Hashes will be ignored.  Any other value for `options` will trigger the `url_for(options)` path, which can then raise on bad input.

Using `options.blank?`, `link_to @workshop, "\n"` would trigger the`url_for(name)` path, and ignore the bad `"\n"` input.

Comment (ghiculescu) [reply actionview/lib/action_view/helpers/url_helper.rb:745]: Wow yeah I'm having a slow day. Yes, it is the opposite.
