### PR TITLE
Use a NullFlash object when the session is disabled

### LINKED ISSUE #42165: EtagWithFlash Crashes When the Session Store is Disabled
`EtagWithFlash` is the default module used for calculating etags. It errors out when the session store is disabled. 

### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.session_store :disabled

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    stale?(weak_etag: 'foo')
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
The test should pass.

### Actual behavior
The test fails with an error stack trace:
```
NoMethodError (undefined method `flash' for #<ActionDispatch::Request:0x00007fd4ec404818>):
```

### System configuration
**Rails version**:  7.0.0.alpha

**Ruby version**: 2.7.2

### PR DESCRIPTION
**Pull request by ricardotk002**
### Summary
Fixes #42165

This etagger (introduced in #26250) uses flash. However, when the
session store is not set (or disabled), it will raise an error because
the flash middleware is included only if a session store is present.

### Other Information
I'm not completely sure if this is the right way to check application
settings in a base class. Any help would be appreciated.

### CODE REVIEW

**Comment by ricardotk002** [comment]
@byroot Agree. These are two options that I tried too:

```diff
diff --git a/actionpack/lib/action_controller/metal/etag_with_flash.rb b/actionpack/lib/action_controller/metal/etag_with_flash.rb
index 38899e2f16..a18e901685 100644
--- a/actionpack/lib/action_controller/metal/etag_with_flash.rb
+++ b/actionpack/lib/action_controller/metal/etag_with_flash.rb
@@ -12,7 +12,7 @@ module EtagWithFlash
     include ActionController::ConditionalGet
 
     included do
-      etag { flash unless flash.empty? }
+      etag { flash unless Hash === session || flash.empty? }
     end
   end
 end
```

```diff
diff --git a/actionpack/lib/action_controller/metal/etag_with_flash.rb b/actionpack/lib/action_controller/metal/etag_with_flash.rb
index 38899e2f16..65897fc482 100644
--- a/actionpack/lib/action_controller/metal/etag_with_flash.rb
+++ b/actionpack/lib/action_controller/metal/etag_with_flash.rb
@@ -12,7 +12,9 @@ module EtagWithFlash
     include ActionController::ConditionalGet
 
     included do
-      etag { flash unless flash.empty? }
+      if defined?(Rails.application) && Rails.application && !Rails.application.config.session_store
+        etag { flash unless flash.empty? }
+      end
     end
   end
 end
```

Another option is to always include the flash middleware (except in API mode), considering that when no session store is set, the session is just a Hash object.

**Comment by byroot** [comment]
I don't have time to dig into this just yet, but intuitively I think that if session is disabled, most methods should still behave more or less the same, e.g. NullObject pattern.

I'll see if I can look at this later this week end, but feel free to explore.

**Comment by ricardotk002** [comment]
When the session store is disabled, the session seems to be just a Hash object that you can write/read, so I guess that's the null object. However, when the session store is disabled, the middleware `ActionDispatch::Flash` is not included as per:

https://github.com/rails/rails/blob/a31f764/railties/lib/rails/application/default_middleware_stack.rb#L65-L71

In this case, any calls to flash will raise an error. Adding a "null flash middleware" seemed like a lot. I agree that neither option seems elegant.

Thanks for reviewing this!

File: actionpack/lib/action_dispatch/middleware/flash.rb [hunk 1]
```diff
@@ -79,6 +80,23 @@ def reset_session # :nodoc:
       end
     end
 
+    class NullFlash #:nodoc:
+      def []=(...)
```
Comment (byroot) [inline actionpack/lib/action_dispatch/middleware/flash.rb:84]: I think the signature should match a real Flash object.

File: actionpack/lib/action_dispatch/middleware/flash.rb [hunk 2]
```diff
@@ -45,6 +45,7 @@ module RequestMethods
       # read a notice you put there or <tt>flash["notice"] = "hello"</tt>
       # to put a new one.
       def flash
+        return Flash::NullFlash.new unless session.respond_to?(:loaded?)
```
Comment (byroot) [inline actionpack/lib/action_dispatch/middleware/flash.rb:48]: The object has no state, might as well have `NullFlash` be a self extending module as to not bother allocating a new one every time. Not that I expect this to be a hotspot, but it's easy enough to avoid.

Comment (ricardotk002) [reply actionpack/lib/action_dispatch/middleware/flash.rb]: Good point. I addressed that and the comment about the signatures. Thanks again for reviewing!

File: actionpack/lib/action_dispatch/middleware/flash.rb [hunk 3]
```diff
@@ -45,6 +45,7 @@ module RequestMethods
       # read a notice you put there or <tt>flash["notice"] = "hello"</tt>
       # to put a new one.
       def flash
+        return Flash::NullFlash unless session.respond_to?(:loaded?)
```
Comment (byroot) [inline actionpack/lib/action_dispatch/middleware/flash.rb:48]: I'm not too fan of that `respond_to?` What is `session` returning when disabled? I'd rather call an actual method. e.g `unless session.disabled?`

Ohter than that the PR looks good to me now.

Comment (ricardotk002) [reply actionpack/lib/action_dispatch/middleware/flash.rb:48]: Agree. It returns a hash (empty in the text example, but I guess it could be populated too), which is the default Rack session. I noticed this pattern is used in the following places:

https://github.com/rails/rails/blob/8efcf9b/actionpack/lib/action_dispatch/middleware/flash.rb#L70
https://github.com/rails/rails/blob/8efcf9b/actionpack/lib/action_dispatch/http/request.rb#L365

I can change it to something like this if that's better:

```suggestion
        return Flash::NullFlash if Hash === session
```

Comment (byroot) [reply actionpack/lib/action_dispatch/middleware/flash.rb:48]: Hum, no I think checking for Hash type is even worse, as it's even less clear what we are checking for.

I'll have a deeper look tomorrow, see if I can find something better. Otherwise I see we already have a bunch of similar `respond_to?` checks, so I don't think we'd be making anything worse.

**Comment by casperisfine** [comment]
Ok, so I've dug deeper. 

The "default session" comes from `rack`:

  - https://github.com/rack/rack/blob/ef58db35e282af324ee04320174ca3ffc629d945/lib/rack/request.rb#L168-L172
  - https://github.com/rack/rack/blob/ef58db35e282af324ee04320174ca3ffc629d945/lib/rack/request.rb#L554

So I think it could make sense to override `default_session` to return a `NullSession` object, which could then cleanup all these `respond_to?` calls. But one thing at a time, and I think your PR is acceptable for now.

**Review by byroot — APPROVED** [review]

**Comment by byroot** [comment]
I'll give a bit of time for other contributors to chime in, otherwise I'll merge in a couple days.

**Comment by ricardotk002** [comment]
@byroot Yes, the default session never seems to be in a null-ish state. It comes as that hash from Rack. I agree that we should probably enrich that a little bit on Rails side to avoid the `respond_to?` calls which are effective but not really communicative about the intent.
