### ISSUE TITLE
Flash error when in API mode

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#43922]
In an API only app (no session store) I'm seeing an error because the session is a hash:
https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/flash.rb#L62

The Flash middleware is not in my stack, because I'm in API mode.
```
[Honeybadger::Rack::UserInformer, Honeybadger::Rack::UserFeedback, Honeybadger::Rack::ErrorNotifier,
 ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor,
 ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, ActionDispatch::RequestId,
 RequestStore::Middleware, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions,
 ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, Rack::Head,
 Rack::ConditionalGet, Rack::ETag]
```

This used to work in rails 6.1, but starts failing after upgrading to 7.0.0

I believe this is because Metal calls commit_flash directly: https://github.com/rails/rails/blame/main/actionpack/lib/action_controller/metal.rb#L189

And the object returned by `Rack::Request#session` is a plain Hash

and this change did not account for this use case: https://github.com/rails/rails/commit/ca7c820c6962788d510c99a68e725de83cbe9cad

```
Failures:

  1) Update a workflow step for an object with error XML updates the step with error message/text
     Failure/Error: put "/dor/objects/#{druid}/workflows/#{wf.workflow}/#{wf.process}", params: process_xml

     NoMethodError:
       undefined method `enabled?' for {}:Hash
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/flash.rb:62:in `commit_flash'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb:189:in `dispatch'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb:251:in `dispatch'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb:32:in `serve'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb:50:in `block in serve'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb:850:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:99:in `run_callbacks'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/rack/logger.rb:25:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb:37:in `tagged'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb:99:in `tagged'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/rack/logger.rb:25:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/request_id.rb:26:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/static.rb:23:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/agent.rb:426:in `with_rack_env'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/error_notifier.rb:30:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/user_feedback.rb:31:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/user_informer.rb:21:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:530:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/testing/integration.rb:279:in `process'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/testing/integration.rb:34:in `put'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/testing/integration.rb:370:in `put'
```

**Comment by pedrofurtado** [comment]
Same error here, @jcoyne, after upgrade from Rails 6.1.4 to 7.0. In my case, we are using the Web mode, but the error is the same: `undefined method enabled? for {...}:Hash `

**Comment by jcoyne** [comment]
@ricardotk002 do you have any ideas how we might rectify this?

**Comment by pedrofurtado** [comment]
My workaround, for a while, is a monkey patch like this below:

```ruby
# config/initializers/rails_7_patch.rb

class Rack::Session::Abstract::PersistedSecure::SecureSessionHash
  def enabled?
    true
  end
end
```

**Comment by rafaelfranca** [comment]
> And the object returned by `Rack::Request#session` is a plain Hash

Why you have a `Rack::Request` object at that point? The default request object of Rails is `ActionDispatch::Request` and it never returns a hash as session.

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by jcoyne** [comment]
@rafaelfranca it is a `ActionDispatch::Request` object. I was under the impression there was some inheritance relationship, but apparently that is not true.

**Comment by jcoyne** [comment]
I've found that if I put a breakpoint in ActionController::Metal#dispatch, and inspect the session prior to `Metal#process`, then it doesn't have this problem:

```
 $ bundle exec rspec spec/requests/workflows/create_workflow_spec.rb:24
...

Create a workflow
  deprecated PUT create

[183, 192] in /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb
   183:     end
   184:
   185:     def dispatch(name, request, response) # :nodoc:
   186:       byebug
   187:
=> 188:       set_request!(request)
   189:       set_response!(response)
   190:       process(name)
   191:       request.commit_flash
   192:       to_a
(byebug) request.session
#<ActionDispatch::Request::Session:0x7be8 not yet loaded>
(byebug) c
    creates new workflows

Finished in 8.84 seconds (files took 3.82 seconds to load)
1 example, 0 failures
```

When I don't inspect the value it fails:

```
Create a workflow
  deprecated PUT create

[183, 192] in /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb
   183:     end
   184:
   185:     def dispatch(name, request, response) # :nodoc:
   186:       byebug
   187:
=> 188:       set_request!(request)
   189:       set_response!(response)
   190:       process(name)
   191:       request.commit_flash
   192:       to_a
(byebug) c
    creates new workflows (FAILED - 1)

Failures:

  1) Create a workflow deprecated PUT create creates new workflows
     Failure/Error: put "/#{repository}/objects/#{druid}/workflows/#{workflow}?version=1", params: request_data, headers: headers

     NoMethodError:
       undefined method `enabled?' for {}:Hash
     # ./spec/requests/workflows/create_workflow_spec.rb:27:in `block (4 levels) in <top (required)>'
     # ./spec/requests/workflows/create_workflow_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 1.25 seconds (files took 3.8 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/requests/workflows/create_workflow_spec.rb:24 # Create a workflow deprecated PUT create creates new workflows
```

**Comment by jcoyne** [comment]
The workaround I found is to add:
```
Rails.application.config.middleware.use ::ActionDispatch::Flash
```

Which seems to point at Rails.application.config.middleware.use ::ActionDispatch::Flash
 being the root cause.

**Comment by ricardotk002** [comment]
It's confusing that it's raising an error in the Flash code, considering that it's not present in the middleware chain (normal API mode behavior). My guess, after a quick investigation, is that [the loading approach used for the flash's request methods](https://github.com/rails/rails/blob/310d62a443b9157bb48d778f49ba236e18b06b63/actionpack/lib/action_dispatch/middleware/flash.rb#L295-L297) can be triggered just by declaring the constant `ActionDispatch::Flash` anywhere at boot time, in this case those methods will be prepended regardless if the middleware was included or not.

I think something like this could help with that:

```diff
diff --git a/actionpack/lib/action_dispatch/middleware/flash.rb b/actionpack/lib/action_dispatch/middleware/flash.rb
index c085feeca8..3106d7a2cf 100644
--- a/actionpack/lib/action_dispatch/middleware/flash.rb
+++ b/actionpack/lib/action_dispatch/middleware/flash.rb
@@ -289,10 +289,9 @@ def stringify_array(array) # :doc:
         end
     end
 
-    def self.new(app) app; end
-  end
-
-  class Request
-    prepend Flash::RequestMethods
+    def self.new(app)
+      Request.prepend(Flash::RequestMethods)
+      app
+    end
   end
 end
```

I wasn't able to reproduce the exact error, specifically how the app ends up using a hash session.

**Comment by yoshikouki** [comment]
I had the same error, but I found that the cause was a test sign-in process


```ruby
module SignInHelpers
  def sign_in(user)
    allow_any_instance_of(ActionDispatch::Request).to receive(:session).and_return({ user_id: user.id })
  end
end
```

It may be the same cause, so share it

**Comment by jcoyne** [comment]
It looks like the Flash constant is being loaded in the test setup:
```

[1, 10] in /Users/jcoyne85/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-7.0.3/lib/action_dispatch/testing/test_process.rb
    1: # frozen_string_literal: true
    2:
    3: require "action_dispatch/middleware/cookies"
=>  4: require "action_dispatch/middleware/flash"
```

**Comment by twohlix** [comment]
I am able to reproduce this on 7.0.8.7 running a capybara feature through puma. Specifically when an ActiveStorage blob redirect in specs is called:

```
Randomized with seed 29033
Capybara starting Puma...
* Version 6.5.0, codename: Sky's Version
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:44769/
2025-01-20 20:49:05 +0000 Rack app ("GET /rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ac752be2374000521e30765cc7a87c46d6ca8bfd/ball_of_fun.jpg" - (127.0.0.1)): #<NoMethodError: undefined method `enabled?' for {"session_id"=>"63ca1738dcd8395e3739cdf791fed299ed8f44469ce6b99f0ffd75319583d91a", "current_owner_id"=>1}:Rack::Session::Abstract::PersistedSecure::SecureSessionHash

        return unless session.enabled?
                             ^^^^^^^^^>
```

@pedrofurtado's monkey patch work to fix it.
