### ISSUE TITLE
NoMethodError: undefined method `prepend' for []:Array

### ISSUE THREAD

**Issue by hemver** [rails/rails#43477]
### Expected behavior
Ideally below error should not come after upgrade to rails from 5.2 to 6.1

```
NoMethodError: undefined method `prepend' for []:Array
```

### Actual behavior
Facing the issue while commenting the usage of prepend on the code.

### System configuration
**Rails version**:
rails 6.1.4

**Ruby version**:
ruby 2.7.4p191

**Comment by ghiculescu** [comment]
Could you please provide a backtrace, or more info on how to replicate the issue?

Note that if you are upgrading from 5.2, you're better off upgrading to 6.0 first, then upgrading to 6.1 once you're live on 6.0.
