### ISSUE TITLE
Delegation error handling regression in Ruby 3.4: indirect calls raise NameError instead of Module::DelegationError

### ISSUE THREAD

**Issue by abalmeida7** [rails/rails#55463]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

Somewhere = Struct.new(:street, :city) do
  attr_accessor :name
end

Someone = Struct.new(:name, :place) do
  delegate :street, to: :place

  def indirect_call_to_street
    street
  end
end

class BugTest < ActiveSupport::TestCase
  def test_direct_call_works
    david = Someone.new("David")
    # This is how it's tested in Rails: https://github.com/rails/rails/blob/13ebd1ec865ae17a174457b80ab251a9b05b430b/activesupport/test/core_ext/module_test.rb#L336-L339
    assert_raise(Module::DelegationError) { david.street }
  end

  def test_indirect_call_does_not_work
    david = Someone.new("David")
    # this raises a `NameError` instead, this test fails
    assert_raise(Module::DelegationError) { david.indirect_call_to_street }
  end
end
```

### Expected behavior

Both direct and indirect calls to delegated methods should raise `Module::DelegationError` when the delegation target is nil. The test should pass completely with both assertions succeeding.

This is the behavior that works correctly in Ruby 3.3.1:
```
Run options: --seed 8607

# Running:

..

Finished in 0.000462s, 4329.0041 runs/s, 4329.0041 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior

In Ruby 3.4.4, direct calls to delegated methods correctly raise `Module::DelegationError`, but indirect calls (when the delegated method is called from within another method of the same class) raise `NameError` instead:

```
Run options: --seed 55570

# Running:

F.

Finished in 0.000827s, 2418.3797 runs/s, 2418.3797 assertions/s.

  1) Failure:
BugTest#test_indirect_call_does_not_work [delegation_test.rb:36]:
[ActiveSupport::DelegationError] exception expected, not
Class: <NameError>
Message: <"undefined local variable or method 'street' for nil">
---Backtrace---
delegation_test.rb:19:in 'Someone#street'
delegation_test.rb:22:in 'Someone#indirect_call_to_street'
delegation_test.rb:36:in 'block in BugTest#test_indirect_call_does_not_work'
---------------

2 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration

**Rails version**: 8.0.2

**Ruby version**: Issue occurs in Ruby 3.4.4, works correctly in Ruby 3.3.1

**Comment by Earlopain** [comment]
Looks like a ruby bug. I openend https://bugs.ruby-lang.org/issues/21535
