### PR TITLE
[regresion] Allow using mountable engine route helpers in System Tests (v6.0.1)

### LINKED ISSUE #37754: Rails v6.0.1 error when using engine routes in System Tests
### Steps to reproduce
When you use a Rails mountable engine, and in your System Tests you try to use the route helpers (aka, `engine_name.root_url`), in Rails v6.0.1 you get an undefined error.

This only affect tests that inherit from `ActionDispatch::SystemTestCase` (System Tests)...
Tests using `ActionDispatch::IntegrationTest` work just as expected...

After bisecting, this is the first bad commit:
https://github.com/rails/rails/commit/7982363

And, per the changelog, this seems to be the code what is breaking this:

```
# actionpack/CHANGELOG.md
*   `ActionDispatch::SystemTestCase` now inherits from `ActiveSupport::TestCase`
    rather than `ActionDispatch::IntegrationTest`. This permits running jobs in
    system tests.
    *George Claghorn*, *Edouard Chin*
```

I guess the `actionpack` commit is:
https://github.com/rails/rails/commit/ea77dbff

- [ ] create test to reproduce error
- [x] find root cause in Rails v6.0.1 associated gems

### Expected behavior
Same as Rails v6.0.0:
System Tests should be able to use Rails engine route helpers.

### Actual behavior
In Rails 6.0.1:
Rails engine route helpers (`engine_name.root_url`) cannot be used because `engine_name` is undefined:

```
NameError: undefined local variable or method `engine_name' for #<SystemTest:0x00007f93eb38d278>
```

### System configuration
**Rails version**:
Rails v6.0.1

**Ruby version**:
reproduced with Ruby 2.6.5

### PR DESCRIPTION
**Pull request by chalofa**
# Summary

Fixes: https://github.com/rails/rails/issues/37754

After the System Tests refactor in Rails v6.0.1 https://github.com/rails/rails/commit/7982363, when you use a Rails mountable engine, and in your System Tests you try to use the route helpers (aka, engine_name.root_url), you get an undefined error.

### Other Information

This only affect tests that inherit from ActionDispatch::SystemTestCase (System Tests)...
Tests using ActionDispatch::IntegrationTest work just as expected...

I have no idea how to add a test for this, but I'm basically copy/pasting the same code that exists for the `IntegrationTest`:
https://github.com/chalofa/rails/blob/6-0-stable/actionpack/lib/action_dispatch/testing/integration.rb#L339-L340

Fix is for `6-0-stable` branch, it's a different line for `master`, but the change is basically the same

### CODE REVIEW

**Comment by chalofa** [comment]
tried to add a test, but almost all tests are for `ActionDispatch::IntegrationTest` (I guess because before Rails v6.0.1, `SystemTestCase` inherited from it).

I think we need a similar test like this (but for `ActionDispatch::SystemTestCase`) to avoid a regression:
https://github.com/chalofa/rails/blob/6-0-stable/actionpack/test/dispatch/mount_test.rb#L52-L57

**Review by jimmypocock — APPROVED** [review]

**Comment by chalofa** [comment]
any chance that you can review this change? @eileencodes @rafaelfranca @gmcgibbon

I saw you were involved in the main app routes changes for this SystemTestCase refactor

**Comment by eileencodes** [comment]
PR's need to be opened against master and then we will backport to 6-0-stable.

**Comment by chalofa** [comment]
ok, that's an easy fix... lemme do it

**Comment by chalofa** [comment]
@eileencodes ✅ done... PR now points to `master`

**Comment by eileencodes** [comment]
Failing builds are unrelated so I'm going to merge and backport this.
