### ISSUE TITLE
After update to 7.0.2: NoMethodError: undefined method `record_changed?

### ISSUE THREAD

**Issue by Tiikara** [rails/rails#44371]
### Steps to reproduce
This error encountered on `model.update(attrs)` after update rails from 7.0.1 to 7.0.2. On 7.0.1 works perfectly.

### Expected behavior
Should successfull update

### Actual behavior

```
NoMethodError: undefined method `record_changed?' for #<Invoice id: 1393, contractor_id: 9618, storage_id: 2676, price_type_id: nil, shipment_id: nil, shipment_number: "", quantity: nil, purchase_sum: nil, sum: nil, invoice_date: nil, invoice_code: "">
Did you mean?  _record_changed?

  0) InvoicesController base rest controller test PATCH update should pass simple request
     Failure/Error: if model.update(attrs)

     NoMethodError:
       undefined method `record_changed?' for #<Invoice id: 1393, contractor_id: 9618, storage_id: 2676, price_type_id: nil, shipment_id: nil, shipment_number: "", quantity: nil, purchase_sum: nil, sum: nil, invoice_date: nil, invoice_code: "">
       Did you mean?  _record_changed?
```

### System configuration
**Rails version**: 7.0.2

**Ruby version**: 3.1.0

**Comment by akpatternica** [comment]
https://github.com/rails/rails/commit/0bb76f5de5fce6d046abdedd4b8d6b6b20ea6674 look like yes, _record_changed?
