### ISSUE TITLE
`ActiveSupport::ErrorReporter` and string messages

### ISSUE THREAD

**Issue by viralpraxis** [rails/rails#53997]
### Steps to reproduce

Some error reporting services, including Sentry, [allow capturing not only exceptions but also string messages](https://docs.sentry.io/platforms/ruby/usage/#capturing-messages). Recently, support for this functionality was [added](https://github.com/getsentry/sentry-ruby/issues/2460) on Sentry's side, and everything worked fine with Rails version 7.2.

Unfortunately, Rails 8 introduced changes that now require error-like objects to respond (at minimum) to `#cause` and `#backtrace`.
This is kind of expected since AFAIK it was never stated that `ErrorReporter` should work with strings, but I'm curious if we could enhance it to support this use-case?
### Expected behavior

```ruby
Rails.error
=> #<ActiveSupport::ErrorReporter:0x000078f59cf4b478 @subscribers=[#<Sentry::Rails::ErrorSubscriber:0x000078f594637768>], @logger=nil, @debug_mode=true>
Rails.error.report("Some message")
=> nil # works fine on 7.2
```

### Actual behavior

```ruby
> Rails.error.report("Some message") rescue $!
=> #<NoMethodError: undefined method `backtrace' for an instance of String>
```
### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.3.6

**Comment by nvasilevski** [comment]
>Some error reporting services, allow capturing not only exceptions but also string messages

I wonder if this is an argument to why Rails may want to keep API narrow and only support exception instances to be reported. Having strict API hopefully makes error reporting services willing to support it and potentially even provide a subscriber implementation themselves (like Sentry does) which allows applications to never depend on any particular error reporting services, migrate easily or potentially try multiple services at once to decide which one is a better fit.

Of course services not supporting string reporting is not a huge blocker since subscribers could always do the wrapping like
`ReportingService.notify(StandardError.new("error string")` which is not great as different errors may end up being categorized as the same one but still allows applications to somewhat easily migrate to a different provider.

Which brings me to the next point I'm curious about. There is an argument to be made that reporting raw strings could mean that we are reporting things that are not that exceptional and we are abusing error reporting services by using it as a logging/notifications platform to monitor things. Reporting things that are not actionable or do not need to be actioned immediately is a dangerous path, it leads to a messy errors log which is hard to use, new exceptions become unnoticed, people don't act on exceptions as it may not be actionable, quotas exceeded, etc And if a truly exceptional & unexpected needs to be reported - wrapping it into a distinct exception class like `Rails.error.report(MyError.new("message"))` (and potentially attaching a stacktrace to it) may not be a huge price to pay and may be helpful for debugging purposes (raw string may not carry enough context to properly trace what lead to the error) and categorization purposes (depends on error reporting service).

Of course error reporting mess may be prevented by a good discipline in a smaller teams but in my personal experience it becomes much harder to keep the error reporting pristine when hundreds of developers work on the same application and unintentionally end up reporting things that are not actionable. I'm worried allowing strings to be reported will only contribute to the issue, at least in our case.

Perhaps a concrete example of what kind of message an application may be reporting as an exception which doesn't deserve it's own exception class. Because I suspect that the real intention of string-based messages is to log an error-like event ([Rails is considering adding a support for structured event logging](https://github.com/rails/rails/issues/50452)), for example "Could not complete payment" which is an expected situation due to the nature of payments and not exceptional until all of the payments are failing in which case it should be reported as a metric and actioned when the metric exceeds thresholds

**Comment by kiku1705** [comment]
@nvasilevski 👍  I can't agree more.

**Comment by zzak** [comment]
Noting that this was introduced in #43625 (7.0) but was changed in #52684 (8.0) without a deprecation warning, only a changelog.

I've made #54032 to restore the original behavior, but I realize that API change may have been by design. I can see @nvasilevski's argument for keeping the API restricted for `report` and the cases you only have a string can either wrap your own exception or use `unexpected`. We should probably document that though.

/cc @byroot

**Comment by byroot** [comment]
Yeah, I'm not sure it's really a good idea to encourage reporting raw strings, and the `#unexpected` API kinda already fit that niche. And yes, reporting String kinda only worked accidentally, otherwise I would have added tests for it.

We could merge and backport https://github.com/rails/rails/pull/54032 to ease the transition though.

**Comment by rafaelfranca** [comment]
I prefer to not support strings. Let's just document the change. The fix is easy enough for users.
