### PR TITLE
[ActiveRecord] ToSql#HomogeneousIn uses visitor pattern to produce Attribute sql

### PR DESCRIPTION
**Pull request by kbrock**
### Summary

In `ToSql`, operators that generate the sql for an `Attribute` use `visit(o.left, collector)`
This can be seen in `Equality` (and friends), `Case`, `SelectStatement`, and `In`.

### Before

`HomogeneousIn` manually produces the sql for an `Attribute`, introduced in 72fd0bae

To get this to work, knowledge of attributes and table aliases need to be in the node.

running the test it fails in this error:

```
Arel::Nodes::HomogeneousInTest#test_custom_attribute_node:
NoMethodError: undefined method `relation' for #<Arel::Nodes::HomogeneousInTest::TypedNode>
        attribute.relation.table_alias || attribute.relation.name
                 ^^^^^^^^^
    rails/activerecord/lib/arel/nodes/homogeneous_in.rb:40:in `table_name'
    rails/activerecord/lib/arel/visitors/to_sql.rb:336:in `visit_Arel_Nodes_HomogeneousIn'
```

### After

This change makes `HomogeneousIn` follow the pattern by delegating to `ToSql#Attribute`.

### Why

Our code base uses `Arel` on the left hand of the `where()` clauses. This change lets it flow nicely.

### CODE REVIEW

**Comment by kbrock** [comment]
Hey @matthewd -- pretty sure you know the background of my intent, please push me in what ever direction you want me to take. (even if it is for a pet project of yours)

@tenderlove if it was a conscious intention to code the attribute handling in `HomogeneousIn`, please share.

Thanks all

File: activerecord/lib/arel/visitors/to_sql.rb [hunk 1]
```diff
@@ -333,7 +333,7 @@ def visit_Arel_Nodes_Grouping(o, collector)
         def visit_Arel_Nodes_HomogeneousIn(o, collector)
           collector.preparable = false
 
-          collector << quote_table_name(o.table_name) << "." << quote_column_name(o.column_name)
+          visit o.left, collector
```
Comment (eileencodes) [inline activerecord/lib/arel/visitors/to_sql.rb:336]: Can you write a failing test for the behavior you're changing?

I'm not quite following the code example or the changes in the linked PR. Generally Arel is considered a private API so understanding what's broken will inform us whether we want to accept a change to this internal implementation.

**Review by eileencodes — CHANGES_REQUESTED** [review]

**Comment by kbrock** [comment]
Hi @eileencodes 

This is all about an internal API, so thank you for the consideration.

If you look in `to_sql.rb`, [almost] all the places that produce SQL for an attribute delegate to the `Attribute` visitor via `visit o.left, collector`. I'm hoping we can do the same in `HomogeneousIn`.

The performance gains you and Aaron made were on the right hand side / the casting portion. Such a great find that you two made.

reproducer: https://gist.github.com/kbrock/7e7d2343801f0211fef11d6024e72e37

**Review by matthewd — APPROVED** [review]
Yeah, this is internal behaviour, but I agree the proposed change is more correct, even though we don't yet officially support a public API that would show a difference: it's more consistent with the visitor pattern to leave the formatting detail of the LHS up to that node (and e.g. in theory a DB adapter might use something other than `.` to table-qualify a column reference).

Mostly, just from a layering perspective, there's no compelling motivation for HomogeneousIn to reach down and assume its LHS is an Attribute.

**Comment by matthewd** [comment]
While acknowledging that it's indistinguishable from public API, so not testable at the AR level, @kbrock can you see how practical it is to cover this with an Arel-internal test (`activerecord/test/cases/arel/`)? If we're saying this is a technically better implementation, it'd be good to make it obvious if we later make a change that undoes it.

**Comment by kbrock** [comment]
@matthewd not sure if you wanted a test that is testing basic `In` functionality, or if you wanted one that would fail without these changes. I put one of each but am more than happy to pull out the second one if you think it is too much.

The casting is a little out of scope for Arel and crosses the line into ActiveRecord. I tried to not put ActiveRecord or ActiveModel code into the tests.

Thanks for the help

**Comment by kbrock** [comment]
update:
- rebased

@matthewd I did put in an arel only test for `HomogeneousIn`. Let me know if you need more tests for this or any other nodes.

**Review by eileencodes — APPROVED** [review]

**Comment by kbrock** [comment]
Thank you @eileencodes 
This is changing an internal interface and I appreciate you humoring me on this change.

Sorry to /cc Mathew on this and not you. I did it because he is familiar with my project's code base and can give me flack when I am asking for something stupid.

Thanks agin for the incredible `HomogeneousIn` changes that you made (among thousands of other improvements). This code rocks.

**Comment by eileencodes** [comment]
I'm not offended you didn't cc me, I still saw the email about the test but didn't merge it because I wanted to wait if Matthew had any objections or suggestions.
