### ISSUE TITLE
Can't resolve image into URL when using ActiveStorage in mountable Engine

### ISSUE THREAD

**Issue by Bramjetten** [rails/rails#31325]
### Steps to reproduce

- Create a new 5.2 app and setup ActiveStorage using a simple form as described [in this blogpost](http://blog.jasonkim.ca/blog/2017/11/13/Using-ActiveStorage-Today/)
- Create a new mountable engine and move the `PostsController` and views into the engine's namespace.
- Add the newly created engine to your app's Gemfile and mount the engine 

### Expected behavior
`url_for` should still work with ActiveStorage models.

### Actual behavior
ArgumentError when using `url_for` or `image_tag` after form submission.
`Can't resolve image into URL: undefined method `to_model' for #<ActiveStorage::Variant`

### System configuration
**Rails version**:
5.2.0.beta2

**Ruby version**:
2.4.2

**Comment by pixeltrix** [comment]
@Bramjetten does adding the following to your isolated engine's routes.rb file help:

```
resolve("ActiveStorage::Variant") { |variant, options| main_app.route_for(:rails_variant, variant, options) }
```

It looks like `polymorphic_url` inside an isolated engine doesn't pickup the custom polymorphic mappings defined by Active Storage (not even sure that it should).

**Comment by Bramjetten** [comment]
@pixeltrix No, still `undefined method 'to_model'`.

**Comment by pixeltrix** [comment]
@Bramjetten is it possible to put this in a public repo on GitHub so I can take a look?

**Comment by Bramjetten** [comment]
@pixeltrix https://github.com/Bramjetten/active_storage_test

**Comment by Bramjetten** [comment]
We've included a helper in [Spina CMS](https://www.spinacms.com) to circumvent this problem for now. Is this something that will be picked up after the 5.2 release?

```ruby
module Spina
  module ImagesHelper

    def variant(file, options)
      variant = file.variant(options)
      main_app.rails_blob_variation_path(variant.blob.signed_id, variant.variation.key, variant.blob.filename)
    end

  end
end
```

**Comment by gregblass** [comment]
This is exactly what I need when trying to serve a resized image URL through an API.

**Comment by pipboy3000** [comment]
`Spina::ImagesHelper` works fine on Rails 5.2 RC1. but return `undefined method 'rails_blob_variation_path'` on 5.2 RC2. 

I try to this code, it works on my engine.
``` ruby
<%= image_tag image.variant(resize: '100x100').processed.service_url %>
```

**Comment by Bramjetten** [comment]
Apparently the name of the route changed to `rails_blob_representation_path`. Changing it in the `variant` method fixes it.

**Comment by fauxparse** [comment]
Have you tried `main_app.url_for(variant)`?

**Comment by mainangethe** [comment]
so I've found someone advising that the `image_tag` has changed in v5.2+
Unlike v5.1 where you could pass an uploader-object and rails would guess, now in v5.2+ you can only pass the URL.

**Comment by HatsuMora** [comment]
I have the same issue using 
      rails (~> 5.2.3)
      spina (~> 1.0, >= 1.0.3)
ruby 2.6.0p0 (2018-12-25 revision 66547)

**Comment by kdiogenes** [comment]
After a long digging, I think I found a workaround worth sharing.

@pixeltrix already pointed that isolated engines don't pick up polymorphic mappings in https://github.com/rails/rails/issues/31325#issuecomment-349949120. The usage of [`resolve`](https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/CustomUrls.html#method-i-resolve) makes routes resolution totally hidden from engines.

In my case, I was getting an undefined method for `attachment_path`, even calling `main_app.attachment_path` give the same error.

This happens because the `resolve` method doesn't create URL helpers, it populates a structure inside the routes called `polymorphic_mappings`. Polymorphic methods, like `url_for`, `link_to`, etc, check this structure using the [`polymorphic_mapping`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L325) method. When using an isolated engine, the `target` parameter in this method is related to the engine, and there is no mapping for ActiveStorage objects like Variant, Preview, Blob or Attachment.

After trying a lot of combinations of initializers to add these mappings to my engine routes I ended up implementing a `before_action` in my main engine controller:

```ruby
before_action :import_main_app_polymorphic_mappings

private
  def import_main_app_polymorphic_mappings
    MyEngine::Engine.routes.polymorphic_mappings.merge! Rails.application.routes.polymorphic_mappings
  end
```

After this, you will probably get undefined method errors for `rails_blob_url` or `rails_representation_url`. To overcome this, I implemented the following methods, to call the undefined method on `main_app`, in `MyEngine::ApplicationHelper`:

```ruby
def method_missing(method, *args, &block)
  if method.to_s.end_with?("_path", "_url")
    if main_app.respond_to?(method)
      main_app.send(method, *args)
    else
      super
    end
  else
    super
  end
end

def respond_to?(method)
  if method.to_s.end_with?("_path", "_url")
    if main_app.respond_to?(method)
      true
    else
      super
    end
  else
    super
  end
end
```

Is this something Rails should care about? Or the best approach is to dump `isolate_namespace`?

**Comment by niciliketo** [comment]
This is also something we are facing on our project and Rails 6. 
we are using @kdiogenes workaround
I believe action text is going through some changes, would this make this simpler.

**Comment by pixeltrix** [comment]
Just got burnt by this myself with Action Text this week - the best fix for anyone else affected is to change this line in the blob partial:

https://github.com/rails/rails/blob/17cde11cd13cf07a7d6c712cb1593881496abacb/actiontext/app/views/active_storage/blobs/_blob.html.erb#L3

to:

``` erb
 <%= image_tag main_app.url_for(blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])) %> 
```

It might be possible to fix this for everyone by using `main_app.polymorphic_url` here:

https://github.com/rails/rails/blob/17cde11cd13cf07a7d6c712cb1593881496abacb/actionview/lib/action_view/helpers/asset_tag_helper.rb#L631
