### ISSUE TITLE
SerializedAttributeTest#test_serialized_attribute_works_under_concurrent_initial_access is flaky

### ISSUE THREAD

**Issue by itsWill** [rails/rails#35983]
### Steps to reproduce
The test has been flaky on the master branch failing on a couple of builds: 

* https://buildkite.com/rails/rails/builds/60448#1cf76300-2b69-4608-80b3-5e8daf8859bb
* https://buildkite.com/rails/rails/builds/60484#0c26d1b1-148f-436e-abb8-e5711f43124a

An easy way to reproduce the issue in isolation is to wrap the test in a loop: 

``` ruby
 def test_serialized_attribute_works_under_concurrent_initial_access
    loop do 
      model = Class.new(Topic)

      topic = model.create!
      topic.update group: "1"

      model.serialize :group, JSON
      model.reset_column_information

      # This isn't strictly necessary for the test, but a little bit of
      # knowledge of internals allows us to make failures far more likely.
      model.define_singleton_method(:define_attribute) do |*args|
        Thread.pass
        super(*args)
      end

      threads = 4.times.map do
        Thread.new do
          topic.reload.group
        end
      end

      # All the threads should retrieve the value knowing it is JSON, and
      # thus decode it. If this fails, some threads will instead see the
      # raw string ("1"), or raise an exception.
      assert_equal [1] * threads.size, threads.map(&:value)
  end
end
```
And run the specific test. 

I have dug in a bit but have not made much progress. 

@kamipo you've done the most recent work here: https://github.com/rails/rails/commit/893c647da37189543b2c2d55b07d414b1ba8b0d0

any ideas? 

### Expected behavior

The test should pass. 

### Actual behavior
The test raises the following stacktrace: 

```
SerializedAttributeTest#test_serialized_attribute_works_under_concurrent_initial_access:
NoMethodError: undefined method `fully_committed?' for nil:NilClass
    /vagrant/rails/activerecord/lib/active_record/transactions.rb:476:in `sync_with_transaction_state'
    /vagrant/rails/activerecord/lib/active_record/persistence.rb:439:in `persisted?'
    /vagrant/rails/activerecord/lib/active_record/associations.rb:261:in `clear_association_cache'
    /vagrant/rails/activerecord/lib/active_record/associations.rb:254:in `reload'
    /vagrant/rails/activerecord/lib/active_record/autosave_association.rb:231:in `reload'
    test/cases/serialized_attribute_test.rb:392:in `block (3 levels) in test_serialized_attribute_works_under_concurrent_initial_access'
```

### System configuration
**Rails version**: Rails 6.0.0.beta3
**Ruby version**:ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by kamipo** [comment]
Thanks for the issue, this flakyness is caused by 8180c3961063c5786305a94a7d204ab4bc72c381. I've fixed in f7e126beae6249ad75d94bc585f53234b8ae5016.
