### ISSUE TITLE
ActionView::Template::Error: undefined method `concat' for ActionView::OutputBuffer

### ISSUE THREAD

**Issue by kyrofa** [rails/rails#45777]
### Steps to reproduce
First of all, I really appreciate how easy you make it to submit test cases on issues, but I couldn't figure out how to make one for this particular situation. I can tell you, though, that after a bisect, this issue is introduced by 4e8e82829182cc2c1dc07997acc210bc0656eda4.

My test case is pretty simple. I have a HAML view that makes use of a helper like this:

```
def icons
  content_tag(:span, class: "my-icons") do
    concat image_tag('path/to/image.svg')
  end
end
```

### Expected behavior
This helper should render a span with an image contained within it. Before 4e8e82829182cc2c1dc07997acc210bc0656eda4, that's what happened.

### Actual behavior
An error is raised:

```
ActionView::Template::Error: undefined method `concat' for #<ActionView::OutputBuffer:0x000055751f13e310 @raw_buffer="">
    /home/app/foo/vendor/bundle/ruby/2.7.0/gems/haml-5.2.2/lib/haml/helpers/action_view_xss_mods.rb:41:in `concat_with_haml_xss'
    /home/app/foo/app/helpers/icons_helper.rb:80:in `block in icons'
    <snip>
```

### System configuration
**Rails version**: main
**Ruby version**: 2.7.4

**Comment by kyrofa** [comment]
From 4e8e82829182cc2c1dc07997acc210bc0656eda4:

> So ideally we want the buffer not to be a String subclass. Luckily, the Action View buffer is for internal use only, so we can replace inheritance by composition without much work.

Is HAML [using an internal API here](https://github.com/haml/haml/blob/31727c9af7795f7997b4eca8f81343d84df9175a/lib/haml/helpers/action_view_xss_mods.rb#L41), then? Or should we add a concat method back in?

**Comment by natematykiewicz** [comment]
Seems like it'd be preferable to have HAML just switch to `<<`. 

If you call `contact` with 1 argument, the C code calls `rb_str_concat`. https://github.com/ruby/ruby/blob/v3_1_2/string.c#L3384

The Ruby method `<<` is the C method `rb_str_concat`.
https://github.com/ruby/ruby/blob/v3_1_2/string.c#L3418

I don't understand why `concat` was used in the first place. It seems like it's just extra overhead, since it's got to check the argument length and then call another method.

**Comment by kyrofa** [comment]
I can propose that (note that I'm not involved in HAML maintenance), but what will prevent this from happening in the future? Given that comment, it will still be considered internal API and could break at any time. Do we need to start considering it public? Or is there a public API way to do what HAML is doing?

**Comment by natematykiewicz** [comment]
ActionView::OutputBuffer has a [:nodoc: on it](https://github.com/rails/rails/blob/main/actionview/lib/action_view/buffers.rb#L21), which means it's part of the private API and subject to change without notice.

cc @byroot

**Comment by byroot** [comment]
We can add `concat` back as an alias, that's no problem, no need to break HAML. I'll do that tomorrow.
