### ISSUE TITLE
        undefined method `public_id' for nil:NilClass after update to 6.0.2.1

### ISSUE THREAD

**Issue by seb-sykio** [rails/rails#38030]
when I run rspec, I got now this error :

      NoMethodError:
        undefined method `public_id' for nil:NilClass
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/session/cookie_store.rb:106:in `write_session'
      # gems/rack-2.0.8/lib/rack/session/abstract/id.rb:381:in `commit_session'
      # gems/rack-2.0.8/lib/rack/session/abstract/id.rb:261:in `context'
      # gems/rack-2.0.8/lib/rack/session/abstract/id.rb:253:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
      # gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
      # gems/railties-6.0.2.1/lib/rails/rack/logger.rb:38:in `call_app'
      # gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
      # gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
      # gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
      # gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
      # gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
      # gems/rack-2.0.8/lib/rack/method_override.rb:22:in `call'
      # gems/rack-2.0.8/lib/rack/runtime.rb:22:in `call'
      # gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
      # gems/rack-2.0.8/lib/rack/sendfile.rb:111:in `call'
      # gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
      # gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
      # gems/rack-2.0.8/lib/rack/urlmap.rb:68:in `block in call'
      # gems/rack-2.0.8/lib/rack/urlmap.rb:53:in `each'
      # gems/rack-2.0.8/lib/rack/urlmap.rb:53:in `call'
      # gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
      # gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
      # gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
      # gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
      # gems/capybara-3.29.0/lib/capybara/rack_test/browser.rb:65:in `process'
      # gems/capybara-3.29.0/lib/capybara/rack_test/browser.rb:43:in `process_and_follow_redirects'
      # gems/capybara-3.29.0/lib/capybara/rack_test/browser.rb:23:in `visit'
      # gems/capybara-3.29.0/lib/capybara/rack_test/driver.rb:45:in `visit'
      # gems/capybara-3.29.0/lib/capybara/session.rb:276:in `visit'
      # gems/capybara-3.29.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by seb-sykio** [comment]
it sems to happen after doing

session.instance_variable_set('@loaded', true)

**Comment by st0012** [comment]
Hey @seb-sykio 👋

Given that you only provided limited information, I can only give you some of my guess instead of an actual investigation. So the following is just an assumption I have right now.

According to this piece of code:

https://github.com/rails/rails/blob/d2ae2c3103e93783971d5356d0b3fd1b4070d6cf/actionpack/lib/action_dispatch/request/session.rb#L225-L239

It looks like Rails uses `@loaded` (`loaded?`) to determine if the session has been loaded or not and whether it should create a session from the user's cookie (assume you're using cookie storage). 

And in your case, the session and session's id will be `nil` because you skipped the above part by manually setting `session.instance_variable_set('@loaded', true)`.

This started causing you problems since version `6.0.2.1` because of this [commit](https://github.com/rails/rails/commit/92ec9f270d696a17ba7604b3d02931f07c3e7c6a#diff-24599ba98c260e53c03684e6e6964c1fR105) was introduced, which expects the session id is present instead of `nil`.

Assume the change doesn't cause any other issue, I think this is not a bug because you are not using actionpack in a proper way. Can you tell us why do you want to do this `session.instance_variable_set('@loaded', true)`?

**Comment by igormorse** [comment]
I'm facing the same issue because of this commit but with 

> undefined method `public_id' for #<String:0x00007f7731bd90e8>

Did you found any fix @seb-sykio ?

**Comment by mayaeh** [comment]
I had a similar error in my environment.

    NoMethodError (undefined method 'public_id' for #<String:0x00007f86d1decce0>):
    vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/session/cookie_store.rb:111:in 'write_session'

This occurred in the following environment:
  Application: Mastodon latest master ( Ruby v2.6.5 / rails 5.2.4.1 )

1. Log in while running on rails 5.2.4.
1. Update to rails 5.2.4.1 without logout the session, restart and access again.
1. I got this error.

After that, when I cleared the web browser session and login again, it was displayed correctly.

**Comment by igormorse** [comment]
Solution that worked for me:

* Generating a new Secret Key to invalidate all previous Sessions

Steps:

1) Rails secrets
2) Copy the secret key 
3) Create config/secrets.yml if doesnt exists

4) Copy Secret Key to secrets.yml

Example of Secrets.yml

``` Secrets
your_enviroment ( Ex: development ):
    secret_key_base: YOUR_SECRET_KEY
```

**Comment by pushcx** [comment]
I've reproduced this bug on Lobsters, an open source codebase. We're tracking it here: https://github.com/lobsters/lobsters/issues/1693

We are doing something unusual! We're trying to clear the session cookie when there is no session data. It's a scaling concern. If a future request has no cookies, Caddy can present the full-page cache without having to try to look inside the session to know if a user has logged in (user personalization means the cache would be invalid for them).

We introduced it in this PR: https://github.com/lobsters/lobsters/pull/1672/files and the core functions are:

```
  def remove_unknown_cookies
    cookies.each do |key, _value|
      next if key == TAG_FILTER_COOKIE.to_s # don't clear tag filters cookie
      next if key == Rails.application.config.session_options[:key] # don't clear session cookie
      next if key == "__profilin" && (Rails.env.development? || @user&.is_moderator?) # don't clear Rack::MiniProfiler cookie
      next unless VALID_COOKIE_KEY.match?(key)
      cookies.delete(key)
    end
  end

  # clear Rails session cookie if not logged in so nginx uses the page cache
  # https://ryanfb.xyz/etc/2021/08/29/going_cookie-free_with_rails.html
  def clear_session_cookie
    key = Rails.application.config.session_options[:key] # "lobster_trap"
    cookies.delete(key) if @user.blank? && session.empty?
    request.session_options[:skip] = @user.blank? && session.empty?
  end
```

Maybe there's a proper API for clearing unused sessions that we missed?
