### ISSUE TITLE
NoMethodError: undefined method `singularize' for :companies:Symbol

### ISSUE THREAD

**Issue by johan-smits** [rails/rails#27921]
### Models
```ruby
class Device < ApplicationRecord
  belongs_to :account
end

class Account < ApplicationRecord
  belongs_to :company
  has_many :devices, dependent: :destroy
end

class Company < ApplicationRecord
  has_many :accounts
end

#Controller action:
Device.includes(:account, :company).where(account_id: 1,
                                                    account: {
                                                        companies: {
                                                            id: [1,2,3]}})
```

### Expected behavior
Migrated from 5.0.0.1 to 5.0.1 and this code fails during the test.

### Actual behavior
```ruby
NoMethodError: undefined method `singularize' for :companies:Symbol
```
Changing the code to a string 'companies' => {} works.

### System configuration
**Rails version**: 5.0.1

**Ruby version**: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by utilum** [comment]
What if you create the association to company in Device?

**Comment by meinac** [comment]
I think the problem has been solved in #27598. Btw you don't need to explicitly set all dependencies of a relation on where clause which means this works:
```ruby
Device.includes(account: :company).where(account_id: 1, companies: { id: [1,2,3] })
```

**Comment by johan-smits** [comment]
@utilum This is one part of the route. There are also other models linked to the account.

@meinac Changing to this notation works indeed.

**Comment by aguynamedben** [comment]
FYI, if it helps for any future reference, I had the same problem when using a nested join.

This query worked in Rails 5.0.0.1, but when I upgraded to Rails 5.0.3 failed with `NoMethodError: undefined method 'singularize' for :questions:Symbol`
```rb
  scope :top_in_groups, lambda { |groups|
    select("tags.*, COUNT(tag_items.id) AS tag_items_count").
      joins(tag_items: [{ question: [:group] }]).
      where(tag_items: { questions: { group_id: groups } }).
      group("tags.id").
      order("tag_items_count DESC")
  }
```

This is how I fixed it (note the removal of `tag_items` in the where clause)

```rb
  scope :top_in_groups, lambda { |groups|
    select("tags.*, COUNT(tag_items.id) AS tag_items_count").
      joins(tag_items: [{ question: [:group] }]).
      where(questions: { group_id: groups }).
      group(:id).
      order("tag_items_count DESC")
  }
```

I agree it's related to #27598, which also cites interesting history in #20308 and #27599.

**Comment by thiagogabriel** [comment]
@aguynamedben a solution for your first example is replace the symbol with a string on line 4:
```ruby
where(tag_items: { "questions" => { group_id: groups } }).
# instead of
where(tag_items: { questions: { group_id: groups } }).
```
I'm not sure if it was fixed on Rails 5.1

**Comment by chamnap** [comment]
The code is merged on Rails 5.1.
