### ISSUE TITLE
PG result is nil when using `async`

### ISSUE THREAD

**Issue by Vagab** [rails/rails#52405]
### Steps to reproduce

on a fresh `rails 7.2.0.beta3` with async gem and postgres this fails:
```ruby
Sync do
  barrier = Async::Barrier.new
  s = Semaphore.new(10, parent: barrier)
  1.upto(10).map do |i|
    s.async do
      ApplicationRecord.connection.execute("select pg_sleep(1)")
    end
  end
  barrier.wait
end
```
with:
```
|   NoMethodError: undefined method `count' for nil:NilClass (NoMethodError)
|
|                 notification_payload[:row_count] = result.count
|                                                          ^^^^^^
|   → /Users/barseek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.2.0.beta3/lib/active_record/connection_adapters/postgresql_adapter.rb:896 in `block (2 levels) in exec_no_cache'
|     /Users/barseek/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.2.0.beta3/lib/active_record/connection_adapters/abstract_adapter.rb:1004 in `block in with_raw_connection'
```

I'm not sure if it's an `async` or `pg` thing but it worked with rails < 7.2.0

### Expected behavior

It should just slee[ for 1-3 seconds

### Actual behavior

it crashes

### System configuration
**Rails version**: 7.2.0.beta3

**Ruby version**: 3.2.2

**Comment by ruyrocha** [comment]
Could you please create a test script using [this template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb)?

**Comment by Vagab** [comment]
@ruyrocha seems to work fine with sqlite, at least with `:memory:`. I used pg, but it requires you to create the db first. I included a line which does this for mac but let me know if you have something else. Here's the [gist](https://gist.github.com/Vagab/8856cfe9fb0565526b5f6ee24b47a010)

**Comment by ruyrocha** [comment]
@Vagab there are some different results for the other adapters:

* SQLite: raises `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such function: usleep`
* MySQL: raises `ActiveRecord::StatementInvalid: Mysql2::Error: This connection is in use by: #<Fiber:0x0000fffeb2b6ee30`
* Postgres: raises `NoMethodError: undefined method `count' for nil (NoMethodError)`

Trilogy adapter performs a little bit better and I can see the actual queries:

```shell
 ~/G/r/activerecord (main)> ruby run-52405.rb
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
ERROR:  database "thingy" already exists
Run options: --seed 4712

# Running:

D, [2024-07-23T16:29:28.390276 #919394] DEBUG -- :    (4.2ms)  select sleep(1);
D, [2024-07-23T16:29:28.390359 #919394] DEBUG -- :    (4.2ms)  select sleep(1);
D, [2024-07-23T16:29:28.390430 #919394] DEBUG -- :    (4.4ms)  select sleep(1);
D, [2024-07-23T16:29:29.390564 #919394] DEBUG -- :    (1004.6ms)  select sleep(1);
  0.0s     warn: Async::Task [oid=0x1838] [ec=0x184c] [pid=919394] [2024-07-23 16:29:29 -0300]
               | Task may have ended with unhandled exception.
               |   ActiveRecord::ConnectionFailed: Trilogy::QueryError: trilogy_query_recv: TRILOGY_INVALID_SEQUENCE_ID 
```

And later I receive a segfault: 

```shell
activerecord/lib/active_record/connection_adapters/trilogy/database_statements.rb:49: [BUG] Segmentation fault at 0x0000000000000008
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [aarch64-linux]

-- Control frame information -----------------------------------------------
c:0035 p:---- s:0228 e:000227 CFUNC  :query                       
...
-- C level backtrace information -------------------------------------------
fish: Job 1, 'ruby run-52405.rb' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Vagab** [comment]
sqlite is complaining because `usleep` doesn’t exist, so that’s a different thing. Importantly, postgres would fail with `execute(“select 1;”)`, sqlite wouldn’t.
As to the segfault, I got that at some point as well

**Comment by Vagab** [comment]
sqlite is complaining because `usleep` doesn’t exist, so that’s a different thing. Importantly, postgres would fail with `execute(“select 1;”)`, sqlite wouldn’t.
As to the segfault, I got that at some point as well

**Comment by ruyrocha** [comment]
I'm afraid there's no built-in `sleep` function for SQLite:

```
 ~/D/R/resume-builder (main)> sqlite3 storage/development.sqlite3
SQLite version 3.42.0 2023-05-16 12:36:15
Enter ".help" for usage hints.
sqlite> select usleep(1000000);
1000000
sqlite> select sleep(1000000);
Parse error: no such function: sleep
  select sleep(1000000);
         ^--- error here
sqlite> 

```

**Comment by Vagab** [comment]
Yes I’m aware. But as I mentioned postgres fails without sleep as well, just a plain `select 1;`. Why sqlite does not

**Comment by Vagab** [comment]
for anyone else coming here, it seems that this is fixed by putting `config.active_support.isolation_level = :fiber` in the relative environment/`application.rb`
