### PR TITLE
[7-1-stable] Fix Dirty test supports_identity_columns?

### PR DESCRIPTION
**Pull request by zzak**
Fixes this [build failure](https://buildkite.com/rails/rails/builds/107916#018fd1be-20a9-4de2-9930-91123e5b0682), which I believe was caused by 47722e8b4f8fee206358e2b2d87dc728e6429544.

1. `git checkout 7-1-stable`
2. `cd activerecord && bundle exec rake db:postgresql:rebuild postgresql:test`

```
/rails/activerecord/test/cases/dirty_test.rb:975:in `<class:DirtyTest>': undefined method `supports_identity_columns?' for DirtyTest:Class (NoMethodError)
  if current_adapter?(:PostgreSQLAdapter) && supports_identity_columns?
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  supports_nulls_not_distinct?
	from /rails/activerecord/test/cases/dirty_test.rb:11:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `select'
	from /usr/local/bundle/gems/rake-13.2.1/lib/rake/rake_test_loader.rb:6:in `<main>'
```

I can't explain why this only fails in `7-1-stable`, maybe @yahonda or @fatkodima knows?

### CODE REVIEW

**Comment by skipkayhil** [comment]
https://github.com/rails/rails/blob/5dabff4b7bf4cc5e2e552efb78c6a3f3e44bed37/activerecord/test/support/adapter_helper.rb#L61

It's defined on `main`/`7-2-stable` here, appears to not be defined in the same place on `7-1-stable`

**Comment by zzak** [comment]
@skipkayhil Oh, I missed that, nice catch. Would you send a PR? :bow:
