### ISSUE TITLE
On arm64 ubuntu ruby 2.3.2, the model's order method has problem

### ISSUE THREAD

**Issue by scriptfans** [rails/rails#27104]
### Steps to reproduce

On my Nvidia jetson tx1 development board (arm64 architecture, ubuntu 16.04), when I upgrade ruby to 2.3.2, the ActiveRecord's order method is break:

![33bceafb-d179-4892-b210-8fd9e665837d](https://cloud.githubusercontent.com/assets/359790/20453471/88eae4b4-ae61-11e6-878d-0170e0a4b048.png)

### System configuration

**System architecture**: arm64 ubuntu 16.04

**Rails version**: 5.0.0.1

**Ruby version**: 2.3.2

**Comment by matthewd** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by scriptfans** [comment]
@matthewd I think this is a bug for rails, so I post it to here.

**Comment by scriptfans** [comment]
@matthewd 

In fact, after I test, This bug is present in several development boards(Their environment are both rails 5.0.01, ruby 2.3.2, postgresql 9.5):

2.3.0 :004 > a = User.order :created_at
(Object doesn't support #inspect)
 =>
2.3.0 :005 > a.count
NoMethodError: undefined method `blank?' for #<Arel::Nodes::Ascending:0x3080cb8>

as you can see, both armhf and arm64 system has this problem. Don't you think this is a bug for rails?

**Comment by slowjack2k** [comment]
@matthewd I think this can be related to #27064 . This is more lickly an issue with ruby 2.3.2 and not with the used hardware architecture.

**Comment by scriptfans** [comment]
@slowjack2k Thanks! but this bug is not found on other operating systems(ubuntu x86 64bit 14.04, macOS 10.12.1), It appears only on specific armhf and arm64 ubuntu operating systems.
