### ISSUE TITLE
Regression in 6.0.2-rc1 for routes with controller names passed as symbols

### ISSUE THREAD

**Issue by Vasfed** [rails/rails#37857]
This is introduced in a077f94fb3194e301333d3dfd363c0bfa76f638c and is already fixed by 63256bc5d7dd77b2cce82df46c53249dab2dc2a8 in master, but fix is not present in `6-0-2`/`6-0-stable` branches

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

install = true
gemfile(install) do
  source "https://rubygems.org"
  # gem "rails", "6.0.1" # passes
  gem "rails", "6.0.2.rc1" # errors
end

require "rack/test"
require "action_controller/railtie"

module SomeModule
  class ControllerNameSymbolController < ActionController::Base
    def some_action; render plain: "ok"; end
  end
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    scope module: :some_module do
      get :some_action, controller: :controller_name_symbol
    end
  end
end



require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/some_action"
    assert last_response.ok?
  end

  private
    def app; Rails.application; end
end
```
### Expected behavior
Test should pass

### Actual behavior
Getting error
> /Users/vasfed/.rvm/gems/ruby-2.6.1/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:353:in `add_controller_module`: undefined method `start_with?` for `:controller_name_symbol`:Symbol (NoMethodError)

### System configuration
**Rails version**: 6.0.2-rc1

**Ruby version**: 2.6.1

**Comment by eugeneius** [comment]
Thanks for the clear issue description and reproduction steps!

@rafaelfranca tagging you as release manager, https://github.com/rails/rails/commit/63256bc5d7dd77b2cce82df46c53249dab2dc2a8 needs to be backported to 6-0-2.

**Comment by rafaelfranca** [comment]
Closed by 6629ed7a5e
