### ISSUE TITLE
Sidekiq error: Undefined method `broadcast' for ActiveSupport::Logger:Class

### ISSUE THREAD

**Issue by m7madmagdy** [rails/rails#49529]
After upgrade rails to 7.1 the sidekiq service down and shows this error

```
DEPRECATION WARNING: DeprecatedConstantAccessor.deprecate_constant without a deprecator is deprecated (called from <top (required)> at /app/config/application.rb:9)
undefined method `broadcast' for ActiveSupport::Logger:Class
```

### System configuration
**Rails version**: 3.2.0

**Ruby version**: 7.1

**Comment by m7madmagdy** [comment]
/config/application.rb

```
# frozen_string_literal: true

require_relative 'boot'

require 'rails/all'

require 'active_support'

Bundler.require(*Rails.groups)

module Hive
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 7.0
    config.autoload_lib(ignore: %w[assets tasks])

    # Fix undefined method broadcast for ActiveSupport::Logger:Class
    

    # Configuration for the application, engines, and railties goes here.
    #
    # These settings can be overridden in specific environments using the files
    # in config/environments, which are processed later.
    #
    # config.time_zone = "Central Time (US & Canada)"
    # config.eager_load_paths << Rails.root.join("extras")
  end
end

```

**Comment by fatkodima** [comment]
That is already fixed on the newest Sidekiq version.
