### PR TITLE
alias_attribute: handle user defined source methods

### LINKED ISSUE #52820: alias_attribute broken in Rails 7.1.4
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activemodel", "= 7.1.4"
end

require "minitest/autorun"
require "active_model"

# Reproduce example from documentation
# https://guides.rubyonrails.org/active_model_basics.html#method-alias-attribute
class Person
  include ActiveModel::AttributeMethods

  define_attribute_methods :name
  attr_accessor :name

  alias_attribute :full_name, :name
end

class BugTest < Minitest::Test
  def test_aliased_attribute
    person = Person.new
    person.name = "Joe Doe"

    assert_equal "Joe Doe", person.name
    assert_equal "Joe Doe", person.full_name
  end
end
```

### Expected behavior
Tests pass

### Actual behavior
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Run options: --seed 61935

# Running:

E

Finished in 0.000626s, 1597.4438 runs/s, 1597.4438 assertions/s.

  1) Error:
BugTest#test_aliased_attribute:
NoMethodError: undefined method `attribute' for an instance of Person
    /Users/blangfeld/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/attribute_methods.rb:507:in `method_missing'
    /Users/blangfeld/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/attribute_methods.rb:268:in `name'
    alias.rb:31:in `test_aliased_attribute'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: 7.1.4 (works in 7.1.3.4)

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]

### PR DESCRIPTION
**Pull request by casperisfine**
Redo of: https://github.com/rails/rails/pull/52822
Fix: https://github.com/rails/rails/issues/52820

alias_attribute: handle user defined source methods

`alias_attribute` used to define a "jump method", e.g.
`alias_attribute :foo, :bar` was pretty much a macro to generate

```ruby
def foo
  bar
end
```

This is convienient because it's easy, it doesn't impose an order
of declaration or anything like that.

But it's also much less efficient than a true `alias_method`.

It also used to cause cache size explosion which we fixed in
https://github.com/rails/rails/pull/52118, but making it behave
like Ruby's `alias_method`, by doing a real alias.

But this breaks some expectations (literally from the documentation):

```ruby
  attr_accessor :name
  attribute_method_suffix '_short?'
  define_attribute_methods :name

  alias_attribute :nickname, :name
```

Here we're not supposed to alias a generated method, but a user defined one.

So this assumption can only hold for Active Record, not Active Model.

### CODE REVIEW

**Comment by krcm0209** [comment]
Are there any plans to backport this fix to 7.1.4.X?

**Comment by skipkayhil** [comment]
> Are there any plans to backport this fix to 7.1.4.X?

Yes, it has already been backported to `7-1-stable` and will be available in the next 7.1 bugfix release (7.1.5)

**Comment by benlangfeld** [comment]
This was released in 7.1.5 and 7.2.2.
