### ISSUE TITLE
ActionView::Template::Error (undefined method `safe_append=' for {:add_to_stack=>true}:Hash)

### ISSUE THREAD

**Issue by vs37559** [rails/rails#42261]
I recently moved my project from Rails 4.1 to Rails 6.1.3 and Ruby 3.0.1
Since then I am getting this error which man of my view files.
Not sure what is expected resolution for this.

ActionView::Template::Error (undefined method 'safe_append=' for {:add_to_stack=>true}:Hash):
    1: <% title = local_assigns[:title] || "PDF.js viewer"                                                                           
    2: pdf_url = local_assigns[:pdf_url] %>                                                                                             
    3: <!DOCTYPE html>                                                                                                                          
    4: <!--                                                                                                                                                 
/Users/user/Documents/projects/pdfjs-viewer/app/views/pdfjs_viewer/viewer/_viewer.html.erb:3

Rails: 6.1.3
Ruby: 3.0.1

**Comment by p8** [comment]
This seems like a Ruby named arguments problem.
Does running on 2.7 with deprecation warnings enabled give hint?

Maybe a quick fix is adding extra erb tags? Like on:
https://github.com/senny/pdfjs_viewer-rails/blob/master/app/views/pdfjs_viewer/viewer/_viewer.html.erb#L1-L2

**Comment by Bodacious** [comment]
Came across this issue today.

I can confirm that downgrading Ruby from 3.0.2 back down to 2.7.3.

**Comment by Bodacious** [comment]
I've tracked this issue down to [MiniProfiler/rack-mini-profiler](https://github.com/MiniProfiler/rack-mini-profiler)

In my case, upgrading from v1.1 to v2.3.3 resolved the issue for me.

**Comment by gazayas** [comment]
I'm still getting the error after upgrading to v2.3.3 from v2.3.2, so I'm wondering if it's the way we're calling the render method in the project I'm working on.

**Comment by JunichiIto** [comment]
FYI
In my case, xray-rails has problem.

https://github.com/brentd/xray-rails/pull/108

**Comment by gazayas** [comment]
@JunichiIto We use xray-rails in our project too, so that might be it.

I was able to work around it by monkey patching it like this:
```ruby
class ActionView::PartialRenderer
  def render_partial_template(view, locals, template, layout, block)
    ActiveSupport::Notifications.instrument(
      "render_partial.action_view",
      identifier: template.identifier,
      layout: layout && layout.virtual_path
    ) do |payload|
      content = template.render(view, locals, ActionView::OutputBuffer.new, {add_to_stack: !block}) do |*name|
        view._layout_for(*name, &block)
      end

      content = layout.render(view, locals) { content } if layout
      payload[:cache_hit] = view.view_renderer.cache_hits[template.virtual_path]
      build_rendered_template(content, template)
    end
  end
end

class ActionView::Template
  def render(view, locals, buffer = ActionView::OutputBuffer.new, flag = {add_to_stack: true}, &block)
    instrument_render_template do
      compile!(view)
      view._run(method_name, self, locals, buffer, **flag, &block)
    end
  rescue => e
    handle_render_error(view, e)
  end
end
```

**Comment by deepakmahakale** [comment]
### Fix for `xray-rails`

Ruby 3.0.1
Rails 6.1.4

**Gemfile**
```ruby
gem "xray-rails", git: "https://github.com/brentd/xray-rails.git", branch: "bugs/ruby-3.0.0"
```

**app/views/layouts/application.html.erb**
```erb
<%= javascript_include_tag 'xray', nonce: true if Rails.env.development? %>
<%= stylesheet_link_tag 'xray', nonce: true if Rails.env.development? %> 
```

**Comment by laurajaime** [comment]
> I've tracked this issue down to [MiniProfiler/rack-mini-profiler](https://github.com/MiniProfiler/rack-mini-profiler)
> 
> In my case, upgrading from v1.1 to v2.3.3 resolved the issue for me.

Thanks!!! it's works for me
