### ISSUE TITLE
undefined method `form_with_generates_remote_forms=' when upgrading to 5.1.0.rc2

### ISSUE THREAD

**Issue by betesh** [rails/rails#28824]
The rake app:update task creates `config/initializers/new_framework_defaults_5_1.rb` with this line:

```
Rails.application.config.action_view.form_with_generates_remote_forms = false
```

However, rails doesn't seem to know what to do with that line.

### Steps to reproduce
1. Generate a rails 5.0.2 app
2. Edit Gemfile:
```
-gem 'rails', '~> 5.0.2'
+gem 'rails', '~> 5.1.0.rc2'
```
3. bundle update
4. bin/rake app:update (type "y" at all prompts)
5. rails s

### Expected behavior
The Rails server should start without error

### Actual behavior
```
$ bin/rails s
=> Booting Puma
=> Rails 5.1.0.rc2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
~/.rvm/gems/ruby-2.2.2/gems/actionview-5.1.0.rc2/lib/action_view/railtie.rb:27:
in `block (3 levels) in <class:Railtie>':
undefined method `form_with_generates_remote_forms=' for
ActionView::Base:Class (NoMethodError)
```

### System configuration
**Rails version**: 5.1.0.rc2
**Ruby version**: ruby-2.2.2

**Comment by pixeltrix** [comment]
@kaspth I think you missed adding this to `ActionView::Railtie` in a4c1282:

``` ruby
    initializer "action_view.form_with_generates_remote_forms" do |app|
      ActiveSupport.on_load(:action_view) do
        ActionView::Helpers::FormHelper.form_with_generates_remote_forms =
          app.config.action_view.delete(:form_with_generates_remote_forms)
      end
    end
```

By default configs get set on `ActionView::Base` and there's no method there so it blows up.

**Comment by rafaelfranca** [comment]
Backported in 4e1c9c0127

**Comment by kaspth** [comment]
Thanks @rafaelfranca and @pixeltrix ❤️
