### ISSUE TITLE
undefined method `utc_to_local_returns_utc_offset_times' for ActiveSupport:Module

### ISSUE THREAD

**Issue by rubys** [rails/rails#40884]
### Steps to reproduce

```ruby
require 'active_support/time'
TIMEZONE = ActiveSupport::TimeZone.new('UTC')
p TIMEZONE.utc_to_local(Time.now)
```

### Expected behavior

It should print out the local time, with "UTC" appended to it.  Yes, this testcase is a bit bogus, but it was distilled from a larger application that worked with Rails 6.0 but now fails with Rails 6.1.

### Actual behavior

```
Traceback (most recent call last):
	3: from testtime.rb:4:in `<main>'
	2: from /var/lib/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:513:in `utc_to_local'
	1: from /var/lib/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:513:in `yield_self'
/var/lib/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/values/time_zone.rb:514:in `block in utc_to_local': undefined method `utc_to_local_returns_utc_offset_times' for ActiveSupport:Module (NoMethodError)
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by 8398a7** [comment]
You can work around the problem by doing the following.

```ruby
require 'active_support'
require 'active_support/time'
TIMEZONE = ActiveSupport::TimeZone.new('UTC')
p TIMEZONE.utc_to_local(Time.now)
```

**Comment by eugeneius** [comment]
You must require `active_support` before cherry-picking individual files; the fact that it worked before was a coincidence.
