### ISSUE TITLE
Can't set session in controller test http requests

### ISSUE THREAD

**Issue by murdoch** [rails/rails#25394]
### Steps to reproduce

I generated a new rails 5.0.0.rc1 app along with a home controller and a sessions controller:

``` ruby
    # in routes.rb
    get '/login', to: 'sessions#new', as: 'login'
    root to: 'home#show'

    # sessions controller
    class SessionsController < ApplicationController 
      def new
        if session[:user_id]
          redirect_to root_url, notice: 'Already logged in'
        end
      end 
    end
 ```

Now the first thing I notice is that my auto generated test file inherits from ActionDispatch::IntegrationTest:

``` ruby
    # test/controllers/sessions_controller_test.rb
    class SessionsControllerTest < ActionDispatch::IntegrationTest
    end    
```

So lets try to write a test where we set the `user_id` session key so we can ensure that our logged in user is redirected to the root path when they visit the login page. According to the [Edge Guide](http://edgeguides.rubyonrails.org/testing.html#functional-tests-for-your-controllers) we're supposed to use named arguments with HTTP requests in tests now:

``` ruby
    # test/controllers/sessions_controller_test.rb
    class SessionsControllerTest < ActionDispatch::IntegrationTest
      test 'should redirect to root path if a logged in user visits the login page' do
        get login_url, session: { user_id: 42 }
        assert_redirected_to root_url, 'Did not redirect'
      end
    end    
```

This test fails because the redirect is **not followed** and we also see the following deprecation message:

>DEPRECATION WARNING: ActionDispatch::IntegrationTest HTTP request methods will accept only
the following keyword arguments in future Rails versions:
params, headers, env, xhr

>Examples:

>get '/profile',
  params: { id: 1 },
  headers: { 'X-Extra-Header' => '123' },
  env: { 'action_dispatch.custom' => 'custom' },
  xhr: true

So rails is not letting us set the session in the way we are advised to in the Edge Guide.

It looks like the code that enables the use of a kw_arg named 'session' lives in [ActionController::TestCase](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L462) and in order to fix this issue I had to do the following:

1 - Change SessionsControllerTest to inherit from ActionControllerTestCase:

``` ruby
    class SessionsControllerTest < ActionController::TestCase
```

2 - Use symbolized action names instead of URL's with http verbs

``` ruby
    # changed from 
    get '/login', session: { user_id: 42 }

   # to
   get :new, session: { user_id: 42 }
```

It's worth pointing out that we can't even set session variables manually when inheriting from ActionDispatch::IntegrationTest i.e:

``` ruby
    test 'some test' do
      session[:user_id] = 42
      assert something
    end
```
>NoMethodError: undefined method `session' for nil:NilClass

### Expected behavior
I was expecting to be able to pass keyword arguments to HTTP verbs in my controller tests like so:

    get '/some-url', session: { cart_id: 42 }

### Actual behavior
Keyword arguments appear to be ignored unless you inherit from ActionController::TestCase

### System configuration
**Rails version**:
5.0.0.rc1

**Ruby version**:
mri 2.3.0p0

**Comment by rafaelfranca** [comment]
Yeah, the guide is incorrect. Integration tests doesn't allow you to set session.

**Comment by prathamesh-sonpatki** [comment]
I am working on testing guide for 5.0 compatibility and will have update in next 2 3 days.

**Comment by murdoch** [comment]
So are we discouraged from setting the session in controller tests now that they inherit from ActionDispatch::IntegrationTest?

**Comment by rafaelfranca** [comment]
Yes.

**Comment by murdoch** [comment]
Ah, I see from [here](http://blog.bigbinary.com/2016/04/19/changes-to-test-controllers-in-rails-5.html) that ActionController::TestCase is to be deprecated for Rails 5.1. 

Cool, I'll read up on it. Thanks.

**Comment by eileencodes** [comment]
@prathamesh-sonpatki do you have PR for this? This is 1 of 2 blockers for Rails 5 release so if you can't get to this let me know and I'll update the docs.

**Comment by prathamesh-sonpatki** [comment]
@eileencodes Opened https://github.com/rails/rails/pull/25450.
