### ISSUE TITLE
railties-5.2.0 `log_to_stdout': undefined method `formatter' for nil:NilClass (NoMethodError) after migration from rails 4 to 5

### ISSUE THREAD

**Issue by nadavb** [rails/rails#33675]
I am trying to migrate from Rails 4 to 5 (because Rails 4 is not supported anymore),

And I get:
```

/home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:92:in `log_to_stdout': undefined method `formatter' for nil:NilClass (NoMethodError)
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:51:in `start'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	from /home/nadav/.rvm/gems/ruby-2.2.7/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
```

**Comment by rafaelfranca** [comment]
This is a problem in your application. Your Rails.logger is `nil` for some reason.
