### ISSUE TITLE
Add steps to upgrade active storage when upgrading from rails 6.0 to 6.1

### ISSUE THREAD

**Issue by clark-upserv** [rails/rails#41887]
### Steps to reproduce
upgrade rails 6.0 app that uses active storage to 6.1

### Expected behavior
I expected ActiveStorage::Blob to function without error

### Actual behavior
recieved this error message:  
```
NoMethodError (undefined method `service_name' for #<ActiveStorage::Blob:0x00007f88e7eb0ba0>)
Did you mean?  service
```

### System configuration
**Rails version**: 
upgrading from 6.0.3 to 6.1.3.1

**Ruby version**: 
2.7.3

### Solution
run this and ActiveStorage::Blob will work:
```
$ rails active_storage:update
$ rails db:migrate
```

### Request
Can the above solution be put in the upgrade instructions page [here](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1)?
https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1 

it is not mentioned in the documentation and might be helpful for others who are trying to upgrade.

**Comment by gmcgibbon** [comment]
> it is not mentioned in the documentation and might be helpful for others who are trying to upgrade.

This is mentioned in the [release notes](https://edgeguides.rubyonrails.org/6_1_release_notes.html#active-storage-notable-changes), which the upgrade guide links to. This was previously raised in https://github.com/rails/rails/issues/40895, so I'm going to close this.
