### ISSUE TITLE
Rails 7 and `Net::SMTP` errors are different when used in `rspec`

### ISSUE THREAD

**Issue by mobilutz** [rails/rails#44105]
### Steps to reproduce

I setup a test repository to show this problem:
https://github.com/mobilutz/rspec-rails7

Maybe this is not related to Rails itself, but the problem is only visible when updating rails from 6.1.4.4 to >= 7.0

The error I am with Rails 7.0 is the following:
```
expected SomeError, got #<NoMethodError: undefined method `message' for "Authentication Error":String> with backtrace:
         # ./app/services/test_class.rb:9:in `rescue in perform'
         # ./app/services/test_class.rb:6:in `perform'
         # ./spec/test_class_spec.rb:17:in `block (3 levels) in <top (required)>'
         # ./spec/test_class_spec.rb:17:in `block (2 levels) in <top (required)>'
```

But before Rails 7.0 there is no error in the specs.

I think it might be related, how `Net::SMTPError` are instantiated, and in combination with rspec are mocked, but it looks strange that this error is only there with rails 7.0 upgrade and not before.
Here the code where net-smpt error are instatiated:
https://github.com/ruby/net-smtp/blob/master/lib/net/smtp.rb#L37-L40

PLEASE see the linked repo above, where there is more information on actual code example to reproduce the error is shown.

### Expected behavior

The `NoMethodError` is not raised.

### Actual behavior

`NoMethodError` is raised.

### System configuration
**Rails version**:  7.0.1

**Ruby version**: 2.7.5

**Rspec version**: 3.10.0

**Comment by andrehjr** [comment]
This happens when you use an updated net-smtp gem. And you're probably getting this gem updated on 7.0 because It's on actionmailer's gemspec now.

If you add `gem 'net-smtp', '~> 0.3.1'` to your Gemfile with Rails 6.1 the same error will happen. Because the interface of Net::SMTPError changed on https://github.com/ruby/net-smtp/pull/26, so you also need to match it when mocking that error. Something like this would work :
 
 ```ruby
 allow(::Mailer).to receive(:something).and_raise(Net::SMTPAuthenticationError.new(nil, message: error_message))
```

Or you keep using an old version of net-smtp on your app (like: `gem 'net-smtp', '0.2.1'`).

**Comment by mobilutz** [comment]
@andrehjr  Thanks for pointing me to the change that caused the issue. And awesome that you also provided an example how to write my spec correctly ❤️ 

I will look into this myself now and this issue can kept closed.
