### PR TITLE
Fix `rails new --dev`

### LINKED ISSUE #38459: Creating an application from local branch of Rails fails.
### Steps to reproduce

[As per Guides](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#running-an-application-against-your-local-branch), run `bundle exec rails new ~/my-test-app --dev`

### Expected behavior
New Rails app should be generated linked to local copy of Rails.

### Actual behavior
The command fails:
```
/vagrant/rails/railties/lib/rails/generators/actions.rb:255:in `block in rails_command': undefined method `silence_warnings' for #<Rails::Generators::AppGenerator:0x000055d32b413328> (NoMethodError)
```

I think this may have been introduced in f6f51632e83d9a1f209b03834ec26adb27bd74c9. I tried to fix this, adding
```
require "active_support/core_ext/kernel/reporting"
```
in `railties/lib/rails/generators/actions.rb` and running again which results in:

```
invalid option: --dev
```

This is probably related to `rails_command "webpacker:install"`.

### System configuration
**Rails version**:
Edge Rails at df186bd16f0d4a798e626297277fc6b490c1419e

**Ruby version**:
2.5.5p157

### PR DESCRIPTION
**Pull request by jonathanhefner**
Follow-up to #38429.

`Rails::Command.invoke` passes arguments through to the appropriate command class.  However, some command classes were ignoring those arguments, and instead relying on the contents of `ARGV`.  In particular, `RakeCommand` expected `ARGV` to contain the arguments necessary to the Rake task, and no other arguments.  This caused the `webpacker:install` task to fail when the `--dev` option from `rails new --dev` remained in `ARGV`.

This commit changes the relevant command classes to not rely on the previous contents of `ARGV`.  This commit also adds a missing `require` for use of `Kernel#silence_warnings`.

Fixes #38459.

### CODE REVIEW

**Comment by eugeneius** [comment]
Is it feasible to add test coverage for the `ARGV` changes? It's not obvious from the diff what the problem was or why this patch solves it.

**Comment by jonathanhefner** [comment]
@eugeneius  Something I considered was clearing `ARGV` entirely in `Rails::Command.invoke`.  That way, in the future, it would be impossible for commands to accidentally depend on its previous contents.

However, looking at the test failures, it seems like this change has far-reaching implications.  I'm not sure if it is a workable solution.

**Comment by eugeneius** [comment]
Those test failures are also happening on master, I don't think they're caused by this change:
https://buildkite.com/rails/rails/builds/67011

**Comment by jonathanhefner** [comment]
@eugeneius  :pray: :pray: :pray:  I saw `rails/railties/lib/rails/commands/rake/rake_command.rb` in the stack trace, and so I just assumed...

Once master is fixed I will trigger another build to test these changes.  Do you think I should add the change I mentioned regarding clearing `ARGV`?

**Comment by kaspth** [comment]
Cool! Yeah, I'm not quite sure how to test this, I guess we can pass `--dev` in railties tests?

Clearing ARGV is interesting! It was definitely a nuisance when I wrote all this, so if we can find a standard way to handle it, that would be great 🙏
