### ISSUE TITLE
Unable to access private class methods from a Scope

### ISSUE THREAD

**Issue by ryofu1210** [rails/rails#38405]
### Steps to reproduce
When i upgrade rails version from 5.2 to 6.0, private class methods can no longer be accessed from a scope

```ruby
class Post < ApplicationRecord

  scope :with_active, -> {filter_active}

  class << self

    private

    def filter_active
      where(status: 1)
    end
  end
end
```

```
Post.with_active 
```

### Expected behavior
```
Post.with_active 
#=> [<Post id: 1, ..>, ....]
```

### Actual behavior
```
Post.with_active 
#=> NoMethodError (undefined method `filter_active' for #<Post::ActiveRecord_Relation:0x0000563ecd045440>)
```

### System configuration
**Rails version**: rails6.0.2.1
**Ruby version**: ruby2.6.5

**Comment by kamipo** [comment]
That accessibility is already deprecated in 5.2 and removed in 6.0 #32355.
