### PR TITLE
Exception throw when new record column increment!

### PR DESCRIPTION
**Pull request by akicho8**
https://github.com/rails/rails/issues/26420

As of Rails4, I tried so as to save.
https://github.com/akicho8/rails/commit/7ca004fda5e971e978dabf7e8521a4ed1e884936

But, I thought it was not good specification.
This is because, a new record, do not notice, without validation, because the will to save. This is dangerous.

So, I think in the same way as update_columns, in the case of the new record, it is good to throw an exception.

How about that?

### CODE REVIEW

File: activerecord/test/cases/persistence_test.rb [hunk 1]
```diff
@@ -131,6 +131,13 @@ def test_increment_updates_counter_in_db_using_offset
     assert_equal initial_credit + 2, a1.reload.credit_limit
   end
 
+  def test_increment_new_record
```
Comment (dmitry) [inline activerecord/test/cases/persistence_test.rb]: What about `destroyed?`?

Comment (akicho8) [inline activerecord/test/cases/persistence_test.rb]: Certainly. Also add test of destroyed

**Comment by TiSer** [comment]
Is it still not fixed? After update from Rails 4.2 to 5.1 I have an error:

> undefined method `-' for #<Balance:0x007fa9c270a8a0>

> Extracted source (around line #359):
>  def increment!(attribute, by = 1, touch: nil)
>       increment(attribute, by)
> #359      change = public_send(attribute) - (attribute_in_database(attribute.to_s) || 0)

**Review by gmcgibbon — COMMENTED** [review]
Still relevant in Rails 6 (11581afc01927565d57dd0e0156e983f92f8c2e0) I would also add coverage for `#decrement!`.
