### ISSUE TITLE
Passing an existing db symbol into ActiveRecord::Base.establish_connection fails with Method Not Found

### ISSUE THREAD

**Issue by ferrettmerr** [rails/rails#22931]
Hi All, I started looking into this while migrating to 5.0.0.beta1. http://edgeapi.rubyonrails.org/ still says the method of passing in a symbol is acceptable. Any ideas why it is doing this?

Code:
class PhpbbGroup < ActiveRecord::Base
  establish_connection "phpbb_#{Rails.env}".to_sym
...

or

class PhpbbGroup < ActiveRecord::Base
  establish_connection "phpbb_#{Rails.env}"
...

Both failed in the same error.

Error line is here:
https://github.com/rails/rails/blob/v5.0.0.beta1/activerecord/lib/active_record/connection_adapters/connection_specification.rb#L36

Start of stack:
ruby/2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/connection_adapters/connection_specification.rb:36:in `initialize': undefined method `tr' for nil:NilClass (NoMethodError)

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by al2o3cr** [comment]
@ferrettmerr The trace you provided appears to indicate that AR correctly attempted to load the specified configuration, but the configuration was incorrect. In particular, the leading line of that trace indicates that the config has *something* URI-ish that parses successfully but does not have a schema. Can you provide a sanitized example of the configuration in `config/database.yml`?

**Comment by ferrettmerr** [comment]
@al2o3cr This was working perfectly with rails 4.0.0 before I upgraded. I have pasted the cleaned database.yml below.

Thanks for your help!

database.yml: 

        development:
          adapter: mysql2
          encoding: utf8
          database: proj
          username: proj
          password: asdasdasd
          host: localhost

        test:
          adapter: mysql2
          encoding: utf8
          database: proj_test
          username: proj
          password: asdasdasd
          host: localhost

        import_db:
          adapter: mysql2
          encoding: utf8
          database: import_db
          username: proj
          password: asdasdasd
          host: localhost

        phpbb_development:
          adapter: mysql2
          encoding: utf8
          database: phpbb_development
          username: proj
          password: asdasdasd
          host: localhost

**Comment by al2o3cr** [comment]
@ferrettmerr Nothing looks odd in that (I was looking for any unusual `url` keys).

On further digging, it looks like my assumption that `URI::Parser` would raise an exception on an invalid URI was incorrect - it does not. That makes me wonder if you're encountering a consequence of https://github.com/rails/rails/commit/efdc20f36ccc37afbb2705eb9acca76dd8aabd4f, which removed a behavior where passing a `String` to `establish_connection` that *happened* to match a DB configuration name triggered different behavior. This was deprecated in https://github.com/rails/rails/commit/ec11807368318845a2542e8f5f51f3f5280135f5 (part of the 4.1 release) and then removed entirely in 5.0.

The only thing that change doesn't explain is the first example you gave (the one with `to_sym`). Can you verify that still triggers the bug? You may also want to verify there's nothing unexpected in your environment's `DATABASE_URL` - I wouldn't expect anything, but it's good to check. :)

**Comment by ferrettmerr** [comment]
@al2o3cr Thanks again for looking into this!

I saw that it was deprecated and was quite surprised to find the .to-sym failed. I will double check that tomorrow. 

Should the documentation be updated to remove the passing of a none URI string? I would be more than willing to submit a PR for updating the docs.

**Comment by maclover7** [comment]
@ferrettmerr - what ended up being the issue here? Feel free to send in a PR to update docs if that will prevent an error like this from occurring in the future.

**Comment by maclover7** [comment]
Closed via #23366, updated the documentation about connections.

**Comment by maclover7** [comment]
Looking back on this, looks like this is already properly documented here --> https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_handling.rb#L38-L43

**Comment by jhaesus** [comment]
When using a string to do the connection it fails on first attempt with undefined method tr for nil:nilClass,
but apparently everything is fine after that first error, connects to the correct database and everything.

When using symbol it doesn't appear to connect at all to the second database and the models supposedly on a different database are queried from the main database.

How to get rid of that first error?

Rails 5.0.0.beta2
