### ISSUE TITLE
config_for raises an error for arrays when there's only a shared key

### ISSUE THREAD

**Issue by skelz0r** [rails/rails#42698]
### Steps to reproduce

I'm using a config files to blacklist some jwt tokens like this:

```yaml
# config/jwt_blacklist.yml
---
shared:
  - token1
  - token2
```

In `application.rb`

```ruby
config.jwt_whitelist = config_for(:jwt_whitelist)
```

### Expected behavior

```ruby
Rails.configuration.jwt_whitelist
=> ["token1", "token2"]
```

### Actual behavior

```ruby
railties-6.1.4/lib/rails/application.rb:252:in `config_for': undefined method `deep_merge' for ["token1", "token2"]:Array (NoMethodError)
```

It worked on rails 6.1.3.2, I think it has been introduced with https://github.com/rails/rails/commit/3fe0ab52dff018ed940ad45885c9d90208eb3cac (related issue: https://github.com/rails/rails/issues/42037 )

Thanks to [this issue](https://github.com/rails/rails/issues/37800) I think it should accepts arrays.

Moreover, I tried the following:

```yaml
production: []
test: []
development: []
shared:
  - token1
  - token2
```

And it returns an empty array:

```ruby
Rails.configuration.jwt_whitelist
=> []
```

Not sure if it's a normal behaviour too.

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.7.2p137

**Comment by intrip** [comment]
@skelz0r I think `config_for` requires that root values should be associated to an hash key, for example this should be a valid:

```yaml
# config/jwt_blacklist.yml
---
shared:
  blacklist:
    - token1
    - token2
```

Whilst your configuration is valid YAML I'm not sure if we want to allow non-hash root values 

@byroot WDYT?

**Comment by skelz0r** [comment]
I hesitated indeed to open an issue, but I saw [this issue](https://github.com/rails/rails/issues/37800) which has a specific example (and bug) with root arrays. 

Moreover, it works on 6.1.3.2, that's why I considered it as a regression.

In any case, that's strange to have a runtime error with only a `shared` key, and no errors when there's `production`, `test` or `development` defined as empty arrays, it should be fixed imo.

**Comment by ghiculescu** [comment]
Agree it's a bug. I think a fix would be to change this line https://github.com/rails/rails/blob/398561bfbb7d156a141918df20b2fc622a94975d/railties/lib/rails/application.rb#L251 to `if config.is_a?(Hash) && shared.is_a?(Hash)`

**Comment by intrip** [comment]
@ghiculescu thanks! 

@skelz0r Would you like to make a PR since you opened the issue ? Otherwise I'll make one.

**Comment by skelz0r** [comment]
@intrip Yes I can do that!

**Comment by skelz0r** [comment]
I have a question: what the expected behaviour when shared is an array and another environment key is not ? 

For example:

```yaml
---
production:
  key: 'value'
shared:
  - foo
  - bar
```

In my opinion it should raise an error with a message like this: `"shared and #{env} have a mismatch type: one is an array and the other an hash"` (if you have a better message I'll take it btw 🙃)

Moreover, should I make 2 different PRs or 2 commits on the same PR ?

**Comment by skelz0r** [comment]
I have an additional question: when there's 2 arrays it should concatenate them right ?

For example:

```yaml
production:
  - baz
shared:
  - foo
  - bar
```

It should returns `%w( foo bar baz )` right ? It's not the case right now.

**Comment by byroot** [comment]
> what the expected behaviour

That's kind of the whole problem of this feature, the expected behavior isn't clearly defined.

But yeah, I think raising an error is the only reasonable thing to do.

**Comment by byroot** [comment]
> I have an additional question: when there's 2 arrays it should concatenate them right ?

No, only hashes should be merged.

**Comment by skelz0r** [comment]
Thanks for the quick replies!

> > I have an additional question: when there's 2 arrays it should concatenate them right ?
> 
> No, only hashes should be merged.

So it should only returns the env key and ignore the shared key ? Should I write a test for this in order to clarify the behaviour ?

**Comment by byroot** [comment]
> So it should only returns the env key and ignore the shared key ?

Yes, unless they're both hashes in which case we deep merge.

> Should I write a test for this in order to clarify the behaviour ?

Absolutely.

**Comment by skelz0r** [comment]
Here we go https://github.com/rails/rails/pull/42707

**Comment by MatheusRich** [comment]
@byroot, I'm sorry to revive this, but show we get this also fixed on 6-1-stable?

**Comment by byroot** [comment]
6.1 is supposed to only receive security fixes: https://guides.rubyonrails.org/maintenance_policy.html

**Comment by MatheusRich** [comment]
Gotcha. Thank you!
