### PR TITLE
alias_attribute: handle user defined source methods

### LINKED ISSUE #52820: alias_attribute broken in Rails 7.1.4
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activemodel", "= 7.1.4"
end

require "minitest/autorun"
require "active_model"

# Reproduce example from documentation
# https://guides.rubyonrails.org/active_model_basics.html#method-alias-attribute
class Person
  include ActiveModel::AttributeMethods

  define_attribute_methods :name
  attr_accessor :name

  alias_attribute :full_name, :name
end

class BugTest < Minitest::Test
  def test_aliased_attribute
    person = Person.new
    person.name = "Joe Doe"

    assert_equal "Joe Doe", person.name
    assert_equal "Joe Doe", person.full_name
  end
end
```

### Expected behavior
Tests pass

### Actual behavior
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Run options: --seed 61935

# Running:

E

Finished in 0.000626s, 1597.4438 runs/s, 1597.4438 assertions/s.

  1) Error:
BugTest#test_aliased_attribute:
NoMethodError: undefined method `attribute' for an instance of Person
    /Users/blangfeld/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/attribute_methods.rb:507:in `method_missing'
    /Users/blangfeld/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/attribute_methods.rb:268:in `name'
    alias.rb:31:in `test_aliased_attribute'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: 7.1.4 (works in 7.1.3.4)

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]

### PR DESCRIPTION
**Pull request by byroot**
Fix: https://github.com/rails/rails/issues/52820

`alias_attribute` used to define a "jump method", e.g. `alias_attribute :foo, :bar` was pretty much a macro to generate

```ruby
def foo
  bar
end
```

This is convienient because it's easy, it doesn't impose an order of declaration or anything like that.

But it's also much less efficient than a true `alias_method`.

It also used to cause cache size explosion which we fixed in https://github.com/rails/rails/pull/52118, but making it behave like Ruby's `alias_method`, by doing a real alias.

But this breaks some expectations (literally from the documentation):

```ruby
  attr_accessor :name
  attribute_method_suffix '_short?'
  define_attribute_methods :name

  alias_attribute :nickname, :name
```

Here we're not aliasing a generated method, but a user defined one.

A solution is to check if the method exist in the class itself, and if it does, alias that user defined method instead of generating one.

It solves the issue at hand, but still is more restrictive than the original implementation, as the user method has to be defined before the `alias_attribute` call, but I think that's an OK limitation.

Another limitation is that user defined methods have to be defined in the class itself. If they are defined in an ancestor the issue remains.

TODO: write a test, and think of a potential better solution.

### CODE REVIEW

**Comment by benlangfeld** [comment]
> It solves the issue at hand, but still is more restrictive than the original implementation, as the user method has to be defined before the `alias_attribute` call, but I think that's an OK limitation.

I think this one is probably fine.

> Another limitation is that user defined methods have to be defined in the class itself. If they are defined in an ancestor the issue remains.

This one might still break some legitimate use cases, which makes me think it could only be shipped in Rails 8.0 per semver.

**Comment by byroot** [comment]
SemVer isn't the only versioning policy out there, and Rails doesn't follow SemVer.

**Comment by benlangfeld** [comment]
> SemVer isn't the only versioning policy out there, and Rails doesn't follow SemVer.

Ok, then I misspoke and should have said Rails 7.2.x.

**Comment by byroot** [comment]
I can probably find a way to handle inheritance too anyway.
