### ISSUE TITLE
[Rails 7.2.0.beta3] ActiveStorage::Attached::One (NameError) after reloading

### ISSUE THREAD

**Issue by bendillinger** [rails/rails#52429]
Hi! We're really excited to try out all the new improvements coming as a part of #51349 (and related) 🎉

After upgrading we noticed an intermittent failing test (when it was the first one ran in the context) that deals with a `has_one_attached` and weird behavior that wasn't present in Rails 7.1

### Steps to reproduce

I couldn't get a script-able reproduction that highlighted the issue so I'll do my best to walk through a reproduction using a new rails app
```zsh
rails new blog
cd blog
bin/rails generate model User avatar:attachment
bin/rails active_storage:install
bin/rails db:migrate
```

Now we're all set up

### Expected behavior
In rails 7.1, we're expecting a `user.avatar.blob` to always be `nil` (until it's attached of course)
```zsh
bin/rails console
```
```ruby
> User.create!
#<User:0x000000013c01a940 id: 1, ...>
> User.first.avatar.blob
nil
> reload!
> User.first.avatar.blob
nil
```

### Actual behavior
```zsh
bin/rails console
```
```ruby
> User.create!
#<User:0x000000013c01a940 id: 1, ...>
> User.first.avatar.blob
nil
> reload!
> User.first.avatar.blob
undefined local variable or method `blob` for an instance of ActiveStorage::Attached::One (NameError)
> User.first.avatar.blob # now it works fine
nil
```

And then interestingly, it happens when calling `blob` -> `reload!` -> `blob`, not only the first `blob` after a `reload`:
```zsh
bin/rails console
```

```ruby
> reload! # note the first reload
> User.first.avatar.blob # works after a reload
nil
> reload!
> User.first.avatar.blob
undefined local variable or method `blob` for an instance of ActiveStorage::Attached::One (NameError)
> User.first.avatar.blob # now it works fine
nil
```

### System configuration
**Rails version**:
```
rails -v
Rails 7.2.0.beta3
```
**Ruby version**:
```
ruby -v
ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
```

### Final notes

I've tried stepping through but couldn't figure out exactly where it's happening. We've noticed significant changes in `ActiveSupport::Delegation` since 7.1 but that's just an educated guess.

**Comment by Vagab** [comment]
I think the pr that causes this is _maybe_ [this one](https://github.com/rails/rails/pull/50872). For some reason `super` [here](https://github.com/rails/rails/blob/f856fcc5bf487f5211008b7f9f13553cfa18369b/activesupport/lib/active_support/delegation.rb#L170) for some reason produces `NameError` instead of `NoMethodError`

**Comment by Earlopain** [comment]
I've bisected this to https://github.com/rails/rails/pull/51230 of all places. On main, it seems fixed by https://github.com/rails/rails/pull/50396. I did not manage to come up with a reproducable testcase but the instructions from op are good.

cc @casperisfine

**Comment by casperisfine** [comment]
Ok, fix is here: https://github.com/rails/rails/pull/52437

The refactoring only exposed a pre-existing bug in `delegate_missing_to`.
