### ISSUE TITLE
Component 'json' of Ruby on Rails not working with Ruby 2.4.0

### ISSUE THREAD

**Issue by Sega100500** [rails/rails#27450]
Install Ruby 2.4.0
In projects with RoR 3.2.xx, 4.2.xxx bundle install is fail:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/home/ruby/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20161225-17221-ivjmjg.rb extconf.rb
creating Makefile

current directory: /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^
generator.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign"
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
Makefile:241: ошибка выполнения рецепта для цели «generator.o»
make: *** [generator.o] Ошибка 1

make failed, exit code 2

Gem files will remain installed in /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
Results logged to /home/ruby/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by Drenmi** [comment]
The JSON gem only supports the `Integer` unification in Ruby 2.4 starting from [2.0.0](https://github.com/flori/json/blob/master/CHANGES.md#2015-09-11-200), and the Rails dependency is set to `~> 1.8`, so you won't be able to run Rails 4.2 with Ruby 2.4 for now.

**Comment by Sega100500** [comment]
@Drenmi 
gem json -v 1.8.5 is perfectly support it! On both RoR - 3.2.xx and 4.2.xx
Only  with ```gem 'json', github: 'flori/json', branch: 'v1.8'```
For many projects - is problem edit each Gemfile

Can still easier to fix this dependence in RoR?

**Comment by HarlemSquirrel** [comment]
It looks like this commit fixes it so we only have to wait for the next release.
https://github.com/rails/rails/commit/47c49242913abbcdb8f798f53324769892d18c97

**Comment by Sega100500** [comment]
@rafaelfranca 
When RoR 4.2.xx and 3.2.xx will be released to work with Ruby 2.4 ? When correct gem json will be released?

**Comment by rafaelfranca** [comment]
Rails 3.2 is not supported anymore so it may never be released to work with Ruby 2.4. About json gem I don't know.

**Comment by kapso** [comment]
How about RoR 4.2.x.x? Any plans for releasing a fix to support Ruby 2.4 ?

**Comment by matthewd** [comment]
See https://github.com/rails/rails/pull/27473 for a start on getting 4.2 working with 2.4.

**Comment by rickyc** [comment]
It's also failing for RoR 5.0.1.

**Comment by VarusSeptimus** [comment]
With **Rails 5.0.1** & **ruby 2.4.0**, when doing `bundle update` (or `gem install json -v '1.8.3'`) : `Gem::Ext::BuildError: ERROR: Failed to build gem native extension. [...] error: ‘rb_cFixnum’ undeclared (first use in this function) [...] error: ‘rb_cBignum’ undeclared (first use in this function)`

**Comment by VarusSeptimus** [comment]
Solved: I just commented out, in my `Gemfile`, the offending gem, `sdoc (~> 0.4.0)` which resolved to 0.4.0 and depended on `json (~> 1.8)`... and re-run `bundle update` all right...

**Comment by z0ph** [comment]
Same issue here with gem 'github-pages', trying to install json.. same error.

**Comment by espen** [comment]
@rickyc try forcing json v2 in Gemfile: ```gem 'json', '~> 2'```

**Comment by gowabash** [comment]
No dice on forcing json version
```
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    json (~> 2)

    rails (= 4.2.7.1) was resolved to 4.2.7.1, which depends on
      activesupport (= 4.2.7.1) was resolved to 4.2.7.1, which depends on
        json (>= 1.7.7, ~> 1.7)```

**Comment by Drenmi** [comment]
> gem json -v 1.8.5 is perfectly support it!

JSON 1.8.5 is [not published to RubyGems](https://github.com/flori/json/issues/311).

**Comment by redox** [comment]
> JSON 1.8.5 is not published to RubyGems.

It has just been published 👍

**Comment by nxmohamad** [comment]
@VarusSeptimus can you explain why commenting out sdoc does no harm to the project?

**Comment by evanrmurphy** [comment]
Thanks for the helpful comments. Editing Gemfile.lock and changing json's version from 1.8.3 to 1.8.5 fixed the issue for me. After that I could run `bundle install` without getting this error.

I got another error of course, but no longer this one. :laughing:
