### ISSUE TITLE
Creating an application from local branch of Rails fails.

### ISSUE THREAD

**Issue by peterb** [rails/rails#38459]
### Steps to reproduce

[As per Guides](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#running-an-application-against-your-local-branch), run `bundle exec rails new ~/my-test-app --dev`

### Expected behavior
New Rails app should be generated linked to local copy of Rails.

### Actual behavior
The command fails:
```
/vagrant/rails/railties/lib/rails/generators/actions.rb:255:in `block in rails_command': undefined method `silence_warnings' for #<Rails::Generators::AppGenerator:0x000055d32b413328> (NoMethodError)
```

I think this may have been introduced in f6f51632e83d9a1f209b03834ec26adb27bd74c9. I tried to fix this, adding
```
require "active_support/core_ext/kernel/reporting"
```
in `railties/lib/rails/generators/actions.rb` and running again which results in:

```
invalid option: --dev
```

This is probably related to `rails_command "webpacker:install"`.

### System configuration
**Rails version**:
Edge Rails at df186bd16f0d4a798e626297277fc6b490c1419e

**Ruby version**:
2.5.5p157
