### PR TITLE
Find inverse associations with plural names

### PR DESCRIPTION
**Pull request by kddnewton**
Previously ActiveRecord couldn't find inverse associations if they were plural, which is a pretty standard use case. This commit changes the behavior to first attempt to find the singular version, then attempt to find the plural version. That makes it work and find plural associations as in the example below:

```ruby
class Post
  has_many :comments
end

class Comment
  belongs_to :post
end
```

Previously the `:post` association reflection would only attempt to find a `comment` inverse, as opposed to both a `comment` and `comments` inverse. This drastically cuts down on the number of associations that don't have inverses, and can end up fixing a lot of strange behavior where the parent doesn't save the child records.

### CODE REVIEW

File: activerecord/lib/active_record/reflection.rb [hunk 1]
```diff
@@ -612,47 +631,30 @@ def inverse_name
...
-        def can_find_inverse_of_automatically?(reflection)
-          reflection.options[:inverse_of] != false &&
-            VALID_AUTOMATIC_INVERSE_MACROS.include?(reflection.macro) &&
-            !INVALID_AUTOMATIC_INVERSE_OPTIONS.any? { |opt| reflection.options[opt] } &&
-            !reflection.scope
+          inverse_name_candidates.detect do |candidate|
+            begin
+              reflection = klass._reflect_on_association(candidate)
+              klass <= reflection.active_record && reflection.can_find_inverse_of_automatically?
+            rescue NameError
```
Comment (rafaelfranca) [inline activerecord/lib/active_record/reflection.rb]: We should scope this recue to only the method we are expecting to raise it.

**Comment by kddeisz** [comment]
@rafaelfranca any other feedback on this one?

**Comment by yahonda** [comment]
Let me inform this test fails with Ruby 2.5.1 and ruby-head. Working fine with 2.4.4.

CI shows the same failure. https://travis-ci.org/rails/rails/jobs/422266836

```ruby
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
$ for i in sqlite3 postgresql mysql2 ; do ARCONN=$i bundle exec ruby -w -Itest test/cases/associations/inverse_associations_test.rb -n test_finds_inverse_of_for_plural_associations;  done
Using sqlite3
Run options: -n test_finds_inverse_of_for_plural_associations --seed 49610

# Running:

E

Error:
InversePolymorphicBelongsToTests#test_finds_inverse_of_for_plural_associations:
NoMethodError: undefined method `name' for nil:NilClass
    test/cases/associations/inverse_associations_test.rb:735:in `test_finds_inverse_of_for_plural_associations'


rails test test/cases/associations/inverse_associations_test.rb:734



Finished in 0.026777s, 37.3462 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
Using postgresql
Run options: -n test_finds_inverse_of_for_plural_associations --seed 42043

# Running:

E

Error:
InversePolymorphicBelongsToTests#test_finds_inverse_of_for_plural_associations:
NoMethodError: undefined method `name' for nil:NilClass
    test/cases/associations/inverse_associations_test.rb:735:in `test_finds_inverse_of_for_plural_associations'


rails test test/cases/associations/inverse_associations_test.rb:734



Finished in 0.088667s, 11.2782 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
Using mysql2
Run options: -n test_finds_inverse_of_for_plural_associations --seed 15896

# Running:

E

Error:
InversePolymorphicBelongsToTests#test_finds_inverse_of_for_plural_associations:
NoMethodError: undefined method `name' for nil:NilClass
    test/cases/associations/inverse_associations_test.rb:735:in `test_finds_inverse_of_for_plural_associations'


rails test test/cases/associations/inverse_associations_test.rb:734



Finished in 0.073057s, 13.6879 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by yahonda** [comment]
Addressed by https://github.com/rails/rails/commit/fa132efe8232ad374f30532c9ed25f7414f89483
