### ISSUE TITLE
Using scaffold generator with namespace lets Controller use undefined privat method for whitelist strong parameters 

### ISSUE THREAD

**Issue by ryabrody** [rails/rails#20446]
With Rails 4.1.0, if I use `rails generate scaffold admin/categories name:string --no-assets` my `Admin::CategoriesController` uses the privat method `category_params` instead of `admin_category_params` (namespace is missing) as parameter for updating a resource.

See generated code with wrong parameter fat highlighted:

<pre>
class Admin::CategoriesController < ApplicationController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @admin_categories = Admin::Category.all
    respond_with(@admin_categories)
  end

  def show
    respond_with(@admin_category)
  end

  def new
    @admin_category = Admin::Category.new
    respond_with(@admin_category)
  end

  def edit
  end

  def create
    @admin_category = Admin::Category.new(<b>category_params</b>)
    flash[:notice] = 'Admin::Category was successfully created.' if @admin_category.save
    respond_with(@admin_category)
  end

  def update
    flash[:notice] = 'Admin::Category was successfully updated.' if @admin_category.update(<b>category_params</b>)
    respond_with(@admin_category)
  end

  def destroy
    @admin_category.destroy
    respond_with(@admin_category)
  end

  private
    def set_admin_category
      @admin_category = Admin::Category.find(params[:id])
    end

    def <b>admin_</b>category_params
      params.require(:admin_category).permit(:name)
    end
end
</pre>

This causes following Error when updating a resource:
```
undefined local variable or method `category_params' for #<Admin::CategoriesController:0x007f81d7832330>
```
Updating the record with following changes works. Changes are also highlighted fat:

<pre>
class Admin::CategoriesController < ApplicationController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @admin_categories = Admin::Category.all
    respond_with(@admin_categories)
  end

  def show
    respond_with(@admin_category)
  end

  def new
    @admin_category = Admin::Category.new
    respond_with(@admin_category)
  end

  def edit
  end

  def create
    @admin_category = Admin::Category.new(<b>admin_</b>category_params)
    flash[:notice] = 'Admin::Category was successfully created.' if @admin_category.save
    respond_with(@admin_category)
  end

  def update
    flash[:notice] = 'Admin::Category was successfully updated.' if @admin_category.update(<b>admin_</b>category_params)
    respond_with(@admin_category)
  end

  def destroy
    @admin_category.destroy
    respond_with(@admin_category)
  end

  private
    def set_admin_category
      @admin_category = Admin::Category.find(params[:id])
    end

    def admin_category_params
      params.require(:admin_category).permit(:name)
    end
end
</pre>

**Comment by repinel** [comment]
It is working fine with `4.1.10`.

**Comment by 8398a7** [comment]
My environment is working fine with ```4.1.0```.

**Comment by repinel** [comment]
@rafaelfranca should this be closed?

**Comment by arthurnn** [comment]
Closing this as seems like @repinel and @8398a7 had this working. Please reopen if it is indeed a problem.
