### ISSUE TITLE
Cannot push an object into a collection

### ISSUE THREAD

**Issue by jonathansimmons** [rails/rails#25906]
### Steps to reproduce
1.) Create a basic model
2.) Assign a collection subset of that model to a variable: 

```ruby
@hours = Hour.all
```

3.) Try to push another instance of the model into that collection
```ruby
@hours << Hour.new()
```
### Expected behavior
A new blank hour should be appended to the array

### Actual behavior
A undefined method error fires with: 
`undefined method '<<' for #<ActiveRecord::Relation []>`

### System configuration
**Rails version**: 5.0

**Ruby version**: 2.3.0

______________________
It's worth noting this works fine in rails 4.2.6

**Comment by st0012** [comment]
I think this is related to https://github.com/rails/rails/commit/9d79334a1dee67e31222c790e231772deafcaeb8

**Comment by jonathansimmons** [comment]
@sgrif Looking at the commit @st0012 referenced above is there a suggestion on how I should adjust my code?

**Comment by st0012** [comment]
And I guess the reason they don't support `<<` anymore is because the array that stores all records will be frozen. So you shouldn't change it. See: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L587
Am I guess right?  @sgrif

**Comment by sgrif** [comment]
No this is a bug

**Comment by sgrif** [comment]
Well perhaps not. I do not think we want to support the shovel operator here but we should deprecate if it was working before.

**Comment by matthewd** [comment]
@sgrif "fixing" it would seem to involve a pretty dramatic change, making relations secretly mutable again. :confused:

Your stated purpose in the linked commit was to fill in gaps in the blacklist, including for the reported case of `[]=`...

---

@jonathansimmons `@hours = Hour.all.to_a`.

**Comment by sgrif** [comment]
I'm debating whether we should have had a deprecation cycle though

**Comment by jonathansimmons** [comment]
I assumed I could use` to_a` but wanted to be sure it was intentionally removed before I went that route. I'll admit a depreciation cycle would have been nice. I feel like it was a commonly used solution.

**Comment by sgrif** [comment]
Since adding a deprecation cycle at this point would mean re-enabling dangerous behavior which we explicitly wanted to remove, I don't think it's worth doing. Closing, as there's no action to take.

**Comment by alosada** [comment]
@sgrif  `@group.avatars << Avatar.new` method is still showing in the docs http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

**Comment by sgrif** [comment]
That's because an association is not the same thing as an arbitrary relation.

**Comment by Ch4s3** [comment]
Is this still not documented anywhere other than this issue?
