### ISSUE TITLE
Error after upgrading: undefined method `content_tag' for ActionView::Base:Class.

### ISSUE THREAD

**Issue by gregschmit** [rails/rails#45165]
I found this in a large project by upgrading to Rails 7 and I noticed a ton of Active Scaffold errors but after turning `BACKTRACE=1` on I found the culprit. In a Rails 6.0 project I can run `ActionView::Base.field_error_proc.call` and I get `"<div class=\"field_with_errors\"></div>"`, but in Rails 7 I get:

```
[1] pry(main)> ActionView::Base.field_error_proc.call
NoMethodError: undefined method `content_tag' for ActionView::Base:Class
Did you mean?  const_get
from /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:145:in `block in <class:Base>'
```

### Steps to reproduce
Open console in a Rail 7.0.3 project and run `ActionView::Base.field_error_proc.call`.

### Expected behavior
I would assume that `ActionView::Base.field_error_proc.call` should work just like it did in Rails 6.

### Actual behavior
```
[1] pry(main)> ActionView::Base.field_error_proc.call
NoMethodError: undefined method `content_tag' for ActionView::Base:Class
Did you mean?  const_get
from /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:145:in `block in <class:Base>'
```

### System configuration
**Rails version**: 7.0.3

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]

**Comment by ghiculescu** [comment]
It looks like this broke with https://github.com/rails/rails/pull/42755

I'm not sure the `ActionView::Base.field_error_proc.call` API was ever intended, but it sounds like it's causing issues when running in tests (so, presumably, in actual requests)? Could you share a bit more details about your setup?

cc @seanpdoyle

**Comment by gregschmit** [comment]
Yeah, here is the full traceback, though like I mentioned, I figured out that directly calling `ActionView::Base.field_error_proc.call` was an easy way I could replicate the issue even in a brand-new empty Rails 7 project. Currently it's being called like this in active scaffold: `html = self.class.field_error_proc.call(html, self) if record.errors[column.name].any?`.

```
Error:
Admin::Scaffolds::DevicesControllerTest#test_post_create:
ActionView::Template::Error: undefined method `content_tag' for ActionView::Base:Class
Did you mean?  const_get
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:145:in `block in <class:Base>'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/bridges/record_select/helpers.rb:54:in `active_scaffold_record_select'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/bridges/record_select/helpers.rb:17:in `active_scaffold_input_record_select'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/helpers/form_column_helpers.rb:22:in `active_scaffold_render_input'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/helpers/form_column_helpers.rb:10:in `active_scaffold_input_for'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/helpers/form_column_helpers.rb:176:in `form_attribute'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/helpers/form_column_helpers.rb:155:in `render_column'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/app/views/active_scaffold_overrides/_form.html.erb:27:in `block in _vendor_cache_active_scaffold___a_bab_cbde_app_views_active_scaffold_overrides__form_html_erb__2560108517672964021_102120'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/data_structures/action_columns.rb:84:in `block in each_column'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/data_structures/set.rb:52:in `block in each'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/data_structures/set.rb:52:in `each'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/data_structures/set.rb:52:in `each'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/data_structures/action_columns.rb:106:in `each'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/data_structures/action_columns.rb:75:in `each_column'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/app/views/active_scaffold_overrides/_form.html.erb:7:in `_vendor_cache_active_scaffold___a_bab_cbde_app_views_active_scaffold_overrides__form_html_erb__2560108517672964021_102120'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:237:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:22:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:188:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:270:in `in_rendering_context'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:180:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:69:in `render'
    /Users/gns/git/rxg/console/app/views/active_scaffold_overrides/_base_form.html.erb:50:in `_app_views_active_scaffold_overrides__base_form_html_erb__3755086588243223203_102060'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:237:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:22:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:188:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:270:in `in_rendering_context'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:180:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:69:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/app/views/active_scaffold_overrides/_create_form.html.erb:3:in `_vendor_cache_active_scaffold___a_bab_cbde_app_views_active_scaffold_overrides__create_form_html_erb__76194532113348003_103200'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/partial_renderer.rb:237:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:27:in `render_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:22:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:188:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:270:in `in_rendering_context'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:180:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_view_rendering.rb:69:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/app/views/active_scaffold_overrides/on_create.js.erb:46:in `_vendor_cache_active_scaffold___a_bab_cbde_app_views_active_scaffold_overrides_on_create_js_erb__1591855607419689045_103180'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `public_send'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:244:in `_run'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:157:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:361:in `instrument_render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/template.rb:155:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:79:in `render_with_layout'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/rendering.rb:117:in `block in _render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/base.rb:270:in `in_rendering_context'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/rendering.rb:116:in `_render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/streaming.rb:216:in `_render_template'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/rendering.rb:103:in `render_to_body'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:46:in `render_to_body'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/abstract_controller/rendering.rb:25:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:30:in `render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
    /Users/gns/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:22:in `block in render'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activerecord-7.0.3/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:21:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/extensions/action_controller_rendering.rb:15:in `render'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/actions/create.rb:67:in `create_respond_to_js'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/actions/core.rb:451:in `block (3 levels) in respond_to_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/actions/core.rb:447:in `respond_to_action'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/actions/create.rb:14:in `create'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:215:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
    /Users/gns/git/rxg/console/vendor/cache/active_scaffold-42a8bab7cbde/lib/active_scaffold/actions/core.rb:311:in `clear_storage'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actiontext-7.0.3/lib/action_text/rendering.rb:20:in `with_renderer'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actiontext-7.0.3/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `instance_exec'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/notifications.rb:206:in `instrument'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activerecord-7.0.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/abstract_controller/base.rb:151:in `process'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionview-7.0.3/lib/action_view/rendering.rb:39:in `process'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/metal.rb:188:in `dispatch'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/test_case.rb:601:in `block in process_controller_response'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/activesupport-7.0.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/test_case.rb:591:in `wrap_execution'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/test_case.rb:601:in `process_controller_response'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/test_case.rb:511:in `process'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
    /Users/gns/.rvm/gems/ruby-2.7.2@rxg/gems/actionpack-7.0.3/lib/action_controller/test_case.rb:412:in `post'
    /Users/gns/git/rxg/console/test/controllers/admin/scaffolds_test_helper.rb:57:in `block in test_post_create'
    /Users/gns/git/rxg/console/test/controllers/admin/scaffolds_test_helper.rb:55:in `each'
    /Users/gns/git/rxg/console/test/controllers/admin/scaffolds_test_helper.rb:55:in `test_post_create'
```

**Comment by ghiculescu** [comment]
Thanks, that helps narrow it down. I'm not sure if this is public API or not, but right now https://github.com/activescaffold/active_scaffold/blob/35748d9681bbec3fc3fe1c18be6f92608d084440/lib/active_scaffold/bridges/record_select/helpers.rb#L54 would need to be updated to work with Rails 7.

**Comment by gregschmit** [comment]
I'm happy to submit a PR to active scaffold; I will try to figure it out myself but I could always use assistance. I'll check out `error_wrapping` for the moment as I notice it uses `field_error_proc`. Actually, probably I should just wrap the call in the context of an ActionView instance (a la `ActionView::Base.new(nil, {}, nil).instance_exec(nil, nil, &ActionView::Base.field_error_proc)`).

**Comment by etiennebarrie** [comment]
> Actually, probably I should just wrap the call in the context of an ActionView instance (a la `ActionView::Base.new(nil, {}, nil).instance_exec(nil, nil, &ActionView::Base.field_error_proc)`).

Why not `error_wrapping`? That's the correct fix in my understanding. `ActionView::Base.new` is not part of the public API either.

**Comment by gardnerapp** [comment]
Just submitted a pull request[ 45240](https://github.com/rails/rails/pull/45240) to solve this problem. Basically we needed ActionView::Base to have access to content_tag as a class wide method. To achieve this I extended ActionVIew::Helpers::TagHelpers into ActionView::Base. 

Let me know what you guys think, thanks !

**Comment by etiennebarrie** [comment]
Sorry indeed `error_wrapping` comes from `ActionView::Helpers::ActiveModelInstanceTag`, which is included in `ActionView::Helpers::Tags::Base`, and it's also not a public API. When you're using the normal helpers, it just works, like [this call to `text_helper`](https://github.com/activescaffold/active_scaffold/blob/aefcf6b724ddf7b4283cdcd81f328b216728ec31/lib/active_scaffold/helpers/form_column_helpers.rb#L48) has proper error wrapping on Rails 7.0.

The only uses cases of `field_error_proc` I see in the gem are in an integration with another gem, recordselect, and I don't have a good way to reproduce this, [the wiki just mentions it's straightforward](https://github.com/activescaffold/active_scaffold/wiki/Record-Select-Integration) but I have no idea how to reproduce.

The way you fixed in `active_scaffold` seems ok to me, even it's not a public API to use the `field_error_proc`, it continues to work by supporting the new default for that value.
```ruby
html = self.instance_exec(html, self, &self.class.field_error_proc) if record.errors[column.name].any?
```

Without changing `active_scaffold`, I'm pretty sure the workaround from @jhawthorn should work, it's removing the problematic call. https://github.com/rails/rails/issues/45165#issuecomment-1144152238

We can close this issue, it's unrelated to Action View directly, it's in `active_scaffold`.
