### ISSUE TITLE
undefined method `cache' for nil:NilClass in ActionView after upgrading to 4.1.14.1

### ISSUE THREAD

**Issue by gingerlime** [rails/rails#23258]
we're getting an error in one of our specs after applying the latest security update in 4.1.14.1 (which prevents us from applying the update on our production unfortunately)

Here's a trace from running the spec. It happens even if we remove cache directives inside the view. Not sure what else to test or other details to provide to reproduce this.

```
  1) TrainerController#summary assigns to the presenter with training data assigns without redirect
     Failure/Error: get :summary, :locale => :en
     NoMethodError:
       undefined method `cache' for nil:NilClass
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/template/resolver.rb:150:in `cached'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/template/resolver.rb:120:in `find_all_anywhere'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:68:in `block (2 levels) in _find_all'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:66:in `each'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:66:in `block in _find_all'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:65:in `each'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:65:in `_find_all'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:50:in `find_file'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/lookup_context.rb:129:in `find_file'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_file'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/template_renderer.rb:33:in `block in determine_template'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/lookup_context.rb:149:in `with_fallbacks'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/abstract_renderer.rb:18:in `with_fallbacks'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/template_renderer.rb:33:in `determine_template'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/template_renderer.rb:8:in `render'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/renderer/renderer.rb:23:in `render'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/rendering.rb:99:in `_render_template'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # /usr/lib/ruby/gems/2.2.0/gems/actionview-4.1.14.1/lib/action_view/rendering.rb:82:in `render_to_body'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/abstract_controller/rendering.rb:25:in `render'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/rendering.rb:16:in `render'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.1.14.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
     # /usr/lib/ruby/gems/2.2.0/gems/activesupport-4.1.14.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # /usr/lib/ruby/gems/2.2.0/gems/activerecord-4.1.14.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /usr/lib/ruby/gems/2.2.0/gems/actionpack-4.1.14.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # ./app/controllers/trainer_controller.rb:41:in `summary'
...
```

Caching is turned off on our test environment as far as I can tell (we're using `config.cache_classes = false`, `config.action_controller.perform_caching = false` and `config.cache_store = :null_store`)

The render call on the controller looks like this

```ruby
render 'quizzes/show'  # renders a view on a different controller / action
```

**Comment by gingerlime** [comment]
might be (loosely) related to #23253 ?

**Comment by vipulnsward** [comment]
@gingerlime this is related to https://github.com/rails/rails/issues/23244
Can you confirm you are on rspec?

**Comment by gingerlime** [comment]
yes, I'm using rspec

**Comment by vipulnsward** [comment]
Cool, going to close, this bug is on rspec, you can follow it here - https://github.com/rspec/rspec-rails/issues/1532

**Comment by gingerlime** [comment]
Ok, thanks for clarifying!! so looks like it should be safe to deploy the security updates on production :)

**Comment by vipulnsward** [comment]
Yup. You can verify if all's good for you with this patch- https://github.com/rspec/rspec-rails/issues/1532#issuecomment-174679485
