### ISSUE TITLE
DeserializationError in YAML.load_dj()

### ISSUE THREAD

**Issue by ccelestial** [rails/rails#34311]
### Description

After upgrading from Rails 5.1.6 to 5.2.1, getting ActiveRecord Object from YAML parsed from 5.1.6 is returning me this error.
```
Delayed::DeserializationError: Job failed to load: undefined method `allocate' for "ActiveModel::AttributeSet":String
```

### Steps to reproduce
1 . From Rails 5.1.6 console, convert an ActiveRecord to yaml
``` ruby
>> Dashboard.first.to_yaml
"--- !ruby/object:Dashboard\nraw_attributes:\n  id: 1\n  user_id: 1\nattributes: !ruby/object:ActiveRecord::AttributeSet\n  attributes: !ruby/object:ActiveRecord::LazyAttributeHash\n    delegate_hash:\n      id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: id\n        value_before_type_cast: 1\n        type: &1 !ruby/object:ActiveModel::Type::Integer\n          precision: \n          scale: \n          limit: \n          range: !ruby/range\n            begin: -2147483648\n            end: 2147483648\n            excl: true\n        original_attribute: \n      user_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: user_id\n        value_before_type_cast: 1\n        type: *1\n        original_attribute: \nnew_record: false\nactive_record_yaml_version: 1\n"
```
2. To Rails 5.2.1 console, try to load object from the output above
```ruby
>> YAML.load_dj("--- !ruby/object:Dashboard\nraw_attributes:\n  id: 1\n  user_id: 1\nattributes: !ruby/object:ActiveRecord::AttributeSet\n  attributes: !ruby/object:ActiveRecord::LazyAttributeHash\n    delegate_hash:\n      id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: id\n        value_before_type_cast: 1\n        type: &1 !ruby/object:ActiveModel::Type::Integer\n          precision: \n          scale: \n          limit: \n          range: !ruby/range\n            begin: -2147483648\n            end: 2147483648\n            excl: true\n        original_attribute: \n      user_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: user_id\n        value_before_type_cast: 1\n        type: *1\n        original_attribute: \nnew_record: false\nactive_record_yaml_version: 1\n")
```

### Expected behavior
It should return the same ActiveRecord object

### Actual behavior
Delayed::DeserializationError: Job failed to load: undefined method `allocate' for "ActiveModel::AttributeSet":String

### System configuration
**Rails version**:
5.2.1
**Ruby version**:
2.4.1

**Comment by Erol** [comment]
I don't think this is Rails-related at all. You might want to file this issue on https://github.com/collectiveidea/delayed_job

**Comment by ccelestial** [comment]
@Erol, I think this is more on the YAML/Psych integration with of AR versions than Delayed::Job.

**Comment by ccelestial** [comment]
I was finding a way to make the older yaml version still Deserializable with Rails 5.2+.

**Comment by adampope** [comment]
We had this exact same `allocate` error.  We diff'd a job serialised on 5.1 and 5.2 and found that

`!ruby/object:ActiveRecord::Attribute::FromDatabase`

is now

`!ruby/object:ActiveModel::Attribute::FromDatabase`

We found that doing a string replace of these values was enough to make the job deserialise with `load_dj` under 5.2
