### ISSUE TITLE
Join error for Associations: NoMethodError (undefined method `expr' for nil:NilClass)

### ISSUE THREAD

**Issue by nbulaj** [rails/rails#32671]
We have one application that was updated from Rails 5.1.6 to 5.2.0 and during this process we've issued a problem with the broken test suite. The problem from my point of view was introduced in 2a211802f3f55b8b7d64f9fbb1942c86be686dc7 .

[`ActiveRecord::Associations::JoinDependency::JoinAssociation` `join_constraints` method was refactored to work with right joins](https://github.com/gen1321/rails/commit/2a211802f3f55b8b7d64f9fbb1942c86be686dc7#diff-7d2190f5cc2af538347085d7551fea1dR46), but in our case it seems that we have left joins. By hijacking into `joins.last` and debugging of ActiveRecord source we could see that `joins.last` has the next value:

`[#<Arel::Nodes::StringJoin:0x0000000008475060 @left="INNER JOIN talents_categories ON talents_categories.id = talents.category_id AND talents_categories.deleted = 'f'", @right=nil>]`

So `@right` variable of this object is `nil`, and next lines of code ( `right.expr = right.expr.and(join_scope.arel.constraints)` ) throws an error.

@kamipo @gen1321

### Steps to reproduce

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "http://rubygems.org"
  gem "activerecord", "5.2.0"
  gem "sqlite3"
  gem "pry"
end

require "pry"
require "active_record"
require "minitest/autorun"
require "logger"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

# Some our models
ActiveRecord::Schema.define do
  create_table "users", force: :cascade do |t|
    t.string   "username",       null: false
    t.boolean  "deleted",        default: false, null: false
  end

  create_table "talents", force: :cascade do |t|
    t.string   "name",             default: "",    null: false
    t.boolean  "deleted",        default: false, null: false
    t.integer  "category_id" 
  end

  create_table "talents_categories", force: :cascade do |t|
    t.string   "name",       default: "", null: false
    t.integer  "priority",   default: 0,  null: false
    t.boolean  "deleted"
  end

  create_table "users_talents", force: :cascade do |t|
    t.integer  "user_id",                      default: 0,     null: false
    t.integer  "talent_id",                    default: 0,     null: false
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class ArchiveableRecord < ApplicationRecord
  self.abstract_class = true

  scope :with_deleted, (-> { unscope(where: :deleted) })
  default_scope { where(deleted: false) }
end

class Talent < ApplicationRecord
  belongs_to :talents_category, foreign_key: :category_id
  has_many :users_talents, foreign_key: :talent_id
  has_many :users, -> { distinct }, through: :users_talents

  scope :with_deleted, (-> { unscoped })

  # Yeeah, that sucks :(
  default_scope do
    joins("INNER JOIN talents_categories ON talents_categories.id = talents.category_id AND talents_categories.deleted = 'f'")
      .where(deleted: false)
  end
end

class TalentsCategory < ArchiveableRecord
  has_many :talents, foreign_key: :category_id
  has_many :users_talents, through: :talents
end

class User < ArchiveableRecord 
  has_many :users_talents, foreign_key: :user_id
  has_many :talents, -> { distinct }, through: :users_talents
end

class UsersTalent < ApplicationRecord
  belongs_to :talent, foreign_key: :talent_id
  belongs_to :user, foreign_key: :user_id

  default_scope { joins(talent: :talents_category) }  
end

class BugTest < Minitest::Test
  def setup
    category = TalentsCategory.create!(name: 'S', priority: 1)
    talent = Talent.create!(name: 'Ruby', category_id: category.id)

    @user = User.create!(username: 'John')
    @user.talents << talent
  end

  def teardown
    @user.destroy
  end

  def test_count_works
    assert_equal 1, User.first.users_talents.count
  end
end

test = BugTest.new('Join error :(')

test.setup
test.test_count_works
test.teardown
```

### Expected behavior

Everything must work, `#count` must return 1 and test pass.

### Actual behavior

`NoMethodError` exception raised.

Error backtrace:

> Traceback (most recent call last):
> 
>        16: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/calculations.rb:145:in `calculate'
>        15: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/calculations.rb:238:in `perform_calculation'
>        14: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/calculations.rb:279:in `execute_simple_calculation'
>        13: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:903:in `arel'
>        12: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:928:in `build_arel'
>        11: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:1008:in `build_joins'
>        10: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:1026:in `build_join_query'
>         9: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:103:in `join_constraints'
>         8: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:103:in `flat_map'
>         7: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:103:in `each'
>         6: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:104:in `block in join_constraints'
>         5: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:177:in `make_join_constraints'
>         4: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency.rb:167:in `make_constraints'
>         3: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency/join_association.rb:33:in `join_constraints'
>         2: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency/join_association.rb:33:in `reverse_each'
>         1: from ./gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/join_dependency/join_association.rb:49:in `block in join_constraints'

### System configuration

**Rails version**: 5.2.0

**Ruby version**: 2.5.1

**Comment by tgturner** [comment]
I would love to look into this one!

**Comment by tgturner** [comment]
Alright, I think I've about reached the limits of my knowledge on how ActiveRecord functions on this one. Best I can tell if `right` is `nil` here https://github.com/tgturner/rails/blob/master/activerecord/lib/active_record/associations/join_dependency/join_association.rb#L46 (which seems to occur for string joins) then it needs to be set to some sort of  `Arel::Node` that represent the `where` query the precedes the `joins` in the scope. I would be happy to keep working on this if someone wants to point me in the right direction or wants to pair.

As a side note, @nbulaj if your test was passing before Rails 5.2, then it seems like its because the join was being dropped from the scope. As far as I can tell, joins didn't work correctly in scopes until 5.2

**Comment by nbulaj** [comment]
@tgturner can't say you right now, but there are was not any problem with the joins (as for  business logic, as for tests, as for production usage). So I'm not sure `join` was being dropped from the scope

**Comment by kamipo** [comment]
Right, for now the line expects only inner/left join nodes which are created in the following line since I missed the consideration of string join.

https://github.com/rails/rails/blob/a3ecf4ff1dbb92259e1627bdd09546211f25d906/activerecord/lib/active_record/associations/join_dependency/join_association.rb#L39

Since association scope does not ignore all joins after #29413, we need to care about string joins too.

**Comment by tgturner** [comment]
@kamipo, what would it look like to correctly create a join node for string joins in the proper place?

**Comment by kamipo** [comment]
I don't see what you mean, but if you mean which line we should address, just address the lines here:

https://github.com/rails/rails/blob/03721d9379c0eeb8b0c93c92301ba7a9caa436a2/activerecord/lib/active_record/associations/join_dependency/join_association.rb#L46-L47

```diff
diff --git a/activerecord/lib/active_record/associations/join_dependency/join_association.rb b/activerecord/lib/active_record/associations/join_dependency/join_association.rb
index c36386ec7e..72196ee3ee 100644
--- a/activerecord/lib/active_record/associations/join_dependency/join_association.rb
+++ b/activerecord/lib/active_record/associations/join_dependency/join_association.rb
@@ -43,8 +43,7 @@ def join_constraints(foreign_table, foreign_klass, join_type, tables, chain)
 
             if arel.constraints.any?
               joins.concat arel.join_sources
-              right = joins.last.right
-              right.expr = right.expr.and(arel.constraints)
+              joins[-1] = append_constraints(table, joins.last, arel.constraints)
             end
 
             # The current table in this iteration becomes the foreign table in the next
```

I've already confirmed this issue could be fixed locally.

**Comment by tgturner** [comment]
I'm not sure I understand ActiveRecord and Arel enough to know what the `append_constraints` method would need to look like. Here are somethings I've tried sticking in the `if arel.constraints.any?` block that haven't worked for me.

```ruby
if arel.constraints.any?
   joins.concat arel.join_sources
   right = joins.last.right
   if right
      right.expr = right.expr.and(arel.constraints)
   else
       joins[-1].right = Arel::Nodes::On.new(arel.constraints)
end
```

```ruby
if arel.constraints.any?
   joins.concat arel.join_sources
   joins[-1] = table.create_join(table, table.create_on(arel.constraints), joins[-1].class)
end
```

```ruby
if arel.constraints.any?
   joins.concat arel.join_sources
   joins[-1] = table.create_join(table, table.create_on(arel.constraints),  join_type)
end
```

These are all my rough estimates at how Arel and ActiveRecord are interacting here. I can never seem to get the sting join and the where to show up in the final query. Let me know if I'm on the right track.

**Comment by gaganawhad** [comment]
Hi @tgturner, thanks for taking a shot at this. Really appreciate it! 

@kamipo  Thanks for your suggestion. Can you comment more on what your `append_constraints` method is so that @tgturner  can move ahead on this? We are hitting this issue as well, so would appreciate this getting resolved :smile: 

Thanks for your work on this, all!

**Comment by tgturner** [comment]
Would love to pick this back up if I can get a little guidance!

**Comment by gaganawhad** [comment]
Hello @kamipo and @rafaelfranca 

I would appreciate your help here, I am trying to take a shot at fixing this one myself. As mentioned earlier, the interaction here between AR and Arel is pretty complicated. Any chance either of you could point me in the right direction? Even after reading through the code and related PRs, it's not been easy to understand where / how to append the constraint on `Arel::Nodes::StringJoin` that gets concatenated to `joins` array. 

Thanks!

**Comment by samdec** [comment]
I'm running into this trying to upgrade our app from 5.1 to 5.2. @kamipo is there any chance you remember what the solution you had locally was that fixed this?
