### ISSUE TITLE
[ActiveRecord] NoMethodError: undefined method `first' for nil:NilClass in ActiveRecord::FinderMethods#find_take

### ISSUE THREAD

**Issue by kidlab** [rails/rails#19305]
This problem occurred when I used `#take` on a loaded association and the association is empty.
Here is the example to reproduce this issue.

**Models**
```ruby
class User < ActiveRecord::Base
  has_many :photos, dependent: :destroy
end

class Photo < ActiveRecord::Base
  belongs_to :user
end
```

**Try it out**
```ruby
$ user.photos.take
=> nil # ok

$ user.photos.to_a
$ user.photos.take
NoMethodError: undefined method `first' for nil:NilClass
from .../gems/activerecord-4.1.7/lib/active_record/relation/finder_methods.rb:458:in `find_take'
```

Here is my monkey patch for `ActiveRecord::FinderMethods#find_take`:
```ruby
module ActiveRecord
  module FinderMethods
   def find_take
      if loaded?
        @records.first if @records
      else
        @take ||= limit(1).to_a.first
      end
    end
  end
end
```

**Comment by schneems** [comment]
Did this code work before? What version did it work on? What version are you using now?

**Comment by kidlab** [comment]
I don't know whether it works before, because this is the new code and I've
just figured out it. I'm using Rails 4.1.7. But I believe we also have this
problem in master branch.

**Comment by kuldeepaggarwal** [comment]
Code is working on master branch.

**Comment by rafaelfranca** [comment]
How about 4-1-stable?

**Comment by kuldeepaggarwal** [comment]
I have to verify it. Will do it after weekend.

**Comment by kuldeepaggarwal** [comment]
It is also working on 4.1.9(I think this is the stable branch).
![19305_1](https://cloud.githubusercontent.com/assets/1930730/6660305/6b0de36c-cbbc-11e4-9b01-b65f9961b789.PNG)


In `post.rb`

```ruby
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

```

In `comment.rb`

```ruby
class Comment < ActiveRecord::Base
  belongs_to :post
end

```

**Comment by kidlab** [comment]
I just upgraded to Rails 4.1.9, the problem was still there :(  If @kuldeepaggarwal cannot reproduce, it seems that there is something wrong with my gems set, I suspect. BTW, I'm using AR with PostgreSQL (`pg` gem `0.18.1`). I will try to debug the root cause of this when I have more time...

**Comment by kuldeepaggarwal** [comment]
This is my Gemfile.

```ruby
source 'https://rubygems.org'
gem 'rails', '4.1.9'
gem 'pg', '0.18.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'

group :development, :test do
  gem 'byebug'
  gem 'method_source'
end

```

**Comment by imanel** [comment]
Interesting. Following template:
``` ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.2.1'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :number
  end
end

module Blog
  class Post < ActiveRecord::Base
    has_many :comments
  end

  class Comment < ActiveRecord::Base
    belongs_to :post
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Blog::Post.create(name: "test")

    assert_equal nil, post.comments.take
    post.comments.to_a
    assert_equal nil, post.comments.take
  end
end
```
This is passing on 4.2.1 and 4.1.10, but failing (with error mentioned in first post) on 4.2.0 and 4.1.9. This is however interesting, since there was no recent changes related to [finder_methods](https://github.com/rails/rails/commits/4-1-stable/activerecord/lib/active_record/relation/finder_methods.rb) that could influence this.

**Comment by jonatack** [comment]
@imanel's template passes on Rails master too.

**Comment by mike-stewart** [comment]
Looks like this was fixed by #16935.
